@startuml
!define MANUAL_TRIGGER <color:blue>**Manual Trigger**</color>
!define AUTOMATIC_TRIGGER <color:green>**Automatic Trigger**</color>
!define WEEKLY_TRIGGER <color:purple>**Weekly Trigger (Monday Morning)**</color>

skinparam rectangle {
    BackgroundColor<<Environment>> LightGreen
    BackgroundColor<<Branch>> Wheat
}

rectangle "feature/x" as feature <<Branch>> {
    [Development is done here]
}

rectangle "master" as master <<Branch>> {
    [Development is merged here]
}

rectangle "devops/deploy-to-dev" as dev <<Branch>> {
    [Deploy to dev.statbus.org] <<Environment>>
}
rectangle "devops/deploy-to-no" as no <<Branch>> {
    [Deploy to no.statbus.org] <<Environment>>
}
rectangle "devops/deploy-to-tcc" as tcc <<Branch>> {
    [Deploy to tcc.statbus.org] <<Environment>>
}
rectangle "devops/deploy-to-production" as prod <<Branch>> {
    [Intermediate Production Branch]
}

feature --> dev : MANUAL_TRIGGER\n(push for PR testing)
feature --> master : MANUAL_TRIGGER\nMerge PR
master --> dev : AUTOMATIC_TRIGGER\n(push on every commit)
master --> prod : MANUAL_TRIGGER\n(push for production)
prod --> no : AUTOMATIC_TRIGGER\n(deploys to no.statbus.org)
prod --> tcc : AUTOMATIC_TRIGGER\n(deploys to tcc.statbus.org)
master --> no : MANUAL_TRIGGER\n(specific deploy)
master --> tcc : MANUAL_TRIGGER\n(specific deploy)
master -right-> prod : WEEKLY_TRIGGER\n(regular releases)

@enduml
