@startuml

title Domain Overview for Formal Economy

cloud "Physical" {
  rectangle "Establishment" AS ES
}

cloud "Legal" {
  rectangle "Legal Unit" AS LU
  rectangle "Legal Relationship" AS LR
}

cloud "Statistical" {
  rectangle "Enterprise" AS EN
}

cloud "Political" {
  rectangle "Power Group" AS PG
}


LU -up-> EN : always has one
LU -up-> PG : optionally has one
LR -down-> LU : influencing
LR -down-> LU : influenced
ES -left-> LU : has one
@enduml


