services:
  worker:
    container_name: ${COMPOSE_INSTANCE_NAME}-worker
    build:
      context: ./cli
    platform: linux/arm64
    profiles:
      - "all"
      - "required"
      - "worker"
    environment:
      # Docker environment detection
      RUNNING_IN_DOCKER: "true"
      # Only expose variables needed by the CLI config
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # Logging variables
      SEQ_SERVER_URL: ${SEQ_SERVER_URL:-https://log.statbus.org}
      SEQ_API_KEY: ${SEQ_API_KEY}
      VERSION: ${VERSION}
      # Debug flags from .env
      VERBOSE: ${VERBOSE:-0}
      DEBUG: ${DEBUG:-0}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
