---
version: '3.4'
services:
  server:
    container_name: nscreg-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    image: ghcr.io/statisticsnorway/nscreg:latest
    pull_policy: build
    build:
      context: .
      dockerfile: src/nscreg.Server/Dockerfile
      args:
        CONFIGURATION: Release
      tags:
        - "dev"
    ports:
      - 80:80
    volumes:
      - ./Library/Keychains/:/root/.aspnet/https
      - ./uploads:/app/uploads
      - ./sampleframes:/app/sampleframes
      - keys:/app/keys
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - elastic
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql19-latest
    user: root
    ports:
      - "1433:1433"
    restart: always
    secrets:
      - nscreg-sql-password
    environment:
      SA_PASSWORD: /run/secrets/nscreg-sql-password
      ACCEPT_EULA: Y
      MSSQL_LCID: 1033
      MSSQL_COLLATION: SQL_Latin1_General_CP1_CI_AS
    healthcheck:
      test: '/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P $$(cat $$SA_PASSWORD) -Q "Select 1"'
      interval: 20s
      retries: 5
    volumes:
      - nscreg-sql-data:/var/opt/mssql/data:rw
    networks:
      - elastic
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
      - discovery.type=single-node
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

secrets:
  nscreg-sql-password:
    file: mssql_password.txt

volumes:
  elasticsearch-data:
  nscreg-sql-data:
  keys:
  certs:
