version: "3.4"
services:
  postgres:
    # We use the same version supported by the latest Ubuntu LTS release
    image: postgres:14
    container_name: statbus-postgres
    user: postgres
    ports:
      - "6543:5432"
    restart: always
    secrets:
      - nscreg-sql-password
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/nscreg-sql-password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      # Local mount of directory fails due to docker file system ownership problems.
      # So instead of the line below, we must use a volume
      #- ./postgres-data:/var/lib/postgresql/data:rw
      - statbus-postgres-data:/var/lib/postgresql/data:rw
      - ./postgres-initdb.d:/docker-entrypoint-initdb.d:r
    networks:
      - elastic

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@statbus.org
      PGADMIN_DEFAULT_PASSWORD: boo8baequoopo5Eoneez
      #PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/nscreg-sql-password
      PGADMIN_DISABLE_POSTFIX: true
    ports:
      - 6480:80
    depends_on:
      - "postgres"

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
      - discovery.type=single-node
    networks:
      - elastic

  seq:
    image: datalust/seq
    volumes:
      - statbus-logging-data:/data
    restart: always
    environment:
      - "ACCEPT_EULA=Y"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 6342:80
      - 6341:5341

networks:
  elastic:
    driver: bridge

secrets:
  # The containers using this secret can read it from the file
  # /run/secrets/nscreg-sql-password
  nscreg-sql-password:
    file: mssql_password.txt

volumes:
  statbus-postgres-data:
    # This volume is independent, and therefore protected from accidental deletion
    # when using docker compose.
    #   docker volume create --name=statbus-postgres-data
    # and to remove use
    #   docker volume remove statbus-postgres-data
    # When external is not used, then remove with
    #   docker compose down --volumes
    #external: true
  elasticsearch-data:
  statbus-logging-data:
  keys:
