# Adapt Supabase.
services:
  kong:
    # Expose API endpoint
    ports:
      - ${SUPABASE_BIND_ADDRESS}:8000/tcp
  rest:
    environment:
      # Enable group by counting for getting the available filter values with counts
      # for statistical_unit
      # Available with the query `select=count(),primary_activity_category_id`
      # and `select=count(),physical_region_id`
      # and uses indices for this.
      PGRST_DB_AGGREGATES_ENABLED: true
  db:
    # Use a custom build with sql_saga extension for temporal tables.
    image: ghcr.io/veridit/supabase_postgres:latest
    #image: veridit/supabase_postgres:latest
    # Prevent the database from using too much memory.
    shm_size: 1g
    ports:
      - ${DB_PUBLIC_LOCALHOST_PORT}:5432
