# Caddy web server configuration
services:
  caddy:
    container_name: ${COMPOSE_INSTANCE_NAME:-statbus}-caddy
    image: caddy:2.7-alpine
    restart: unless-stopped
    ports:
      - "${CADDY_HTTP_PORT:-80}:80"
      - "${CADDY_HTTPS_PORT:-443}:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - caddy_logs:/var/log/caddy
    environment:
      # These variables will be used in the Caddyfile
      APP_HOST: app
      APP_PORT: 3000
      REST_HOST: rest
      REST_PORT: 3000
      SITE_ADDRESS: ${SITE_ADDRESS:-localhost}
      DEPLOYMENT_SLOT_CODE: ${NEXT_PUBLIC_DEPLOYMENT_SLOT_CODE:-dev}
    depends_on:
      - app
      - rest
    profiles:
      - "all"
      - "not_app"

volumes:
  caddy_data:
  caddy_config:
  caddy_logs:
