# Adapt Supabase.
services:
  kong:
    # Expose API endpoint
    ports:
      - ${SUPABASE_BIND_ADDRESS}:8000/tcp
  rest:
    environment:
      # Enable group by counting for getting the available filter values with counts
      # for statistical_unit
      # Available with the query `select=count(),primary_activity_category_id`
      # and `select=count(),physical_region_id`
      # and uses indices for this.
      PGRST_DB_AGGREGATES_ENABLED: true
  db:
    # Use a custom build with sql_saga extension for temporal tables.
    image: ghcr.io/veridit/supabase_postgres:latest
    #image: veridit/supabase_postgres:latest
    # Prevent the database from using too much memory.
    shm_size: 1g
    ports:
      - 127.0.0.1:${DB_PUBLIC_LOCALHOST_PORT}:5432
    volumes:
      # Make all files available for running tests.
      - ..:/statbus
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
      - -c
      - log_min_messages=fatal # prevents Realtime polling queries from appearing in logs
      - -c # Give PostgreSQL more RAM and work around slow disks in hosting.
      - synchronous_commit=off
      - -c
      - wal_writer_delay=500ms
      - -c
      - checkpoint_timeout=15min
      - -c
      - checkpoint_completion_target=0.9
      - -c
      - shared_buffers=1GB
      - -c
      - work_mem=256MB
      - -c
      - wal_buffers=64MB
