# This file requires a `.env` file that contains
#   COMPOSE_FILE=docker-compose.app.yml
#   COMPOSE_INSTANCE_NAME=statbus-dev
#   PUBLIC_PORT=127.0.0.1:3000
#   SUPABASE_ANON_KEY=...
#   SUPABASE_URL=...
#
version: '3.4'
name: ${COMPOSE_INSTANCE_NAME}
services:
  app:
    build:
      context: ./app
    ports:
      - "${PUBLIC_PORT}:3000"
    environment:
      - SUPABASE_ANON_KEY
      - SUPABASE_URL
    restart: unless-stopped
