using System.ComponentModel.DataAnnotations;
using nscreg.Utilities.Attributes;
using nscreg.Utilities.Enums;

namespace nscreg.Data.Entities
{
    /// <summary>
    ///  Class entity address
    /// </summary>
    public class Address : IModelWithId
    {
        public int Id { get; set; }  //	ID generated by the system

        [MaxLength(200)]
        public string AddressPart1 { get; set; }    //	First line of the address as used in the country (for instance street name and number)
        [MaxLength(200)]
        public string AddressPart2 { get; set; }    //	Second line of address (for instance city and zip code)
        [MaxLength(200)]
        public string AddressPart3 { get; set; }    //	
        public virtual Region Region { get; set; }
        [NotMappedFor(ActionsEnum.Create | ActionsEnum.Edit | ActionsEnum.View)]
        public int RegionId { get; set; }
        public double? Latitude { get; set; }
        public double? Longitude { get; set; }
    }
}
