BEGIN;

INSERT INTO "unit_size" ("id", "name", "name_language1", "name_language2", "code") VALUES ('1', 'Small', NULL, NULL, '1');
INSERT INTO "unit_size" ("id", "name", "name_language1", "name_language2", "code") VALUES ('2', 'Medium', NULL, NULL, '2');
INSERT INTO "unit_size" ("id", "name", "name_language1", "name_language2", "code") VALUES ('3', 'Large', NULL, NULL, '3');

SELECT setval(pg_get_serial_sequence('"unit_size"', 'id'), COALESCE((SELECT MAX("id")+1 FROM "unit_size"), 1), false);

INSERT INTO "registration_reason" ("id", "code", "name") VALUES ('1', '1', 'Whatever');

SELECT setval(pg_get_serial_sequence('"registration_reason"', 'id'), COALESCE((SELECT MAX("id")+1 FROM "registration_reason"), 1), false);

INSERT INTO "person_type" ("id", "name") VALUES ('1', 'DIRECTOR');
INSERT INTO "person_type" ("id", "name") VALUES ('2', 'OWNER');
INSERT INTO "person_type" ("id", "name") VALUES ('3', 'MANAGER');
INSERT INTO "person_type" ("id", "name") VALUES ('4', 'PROPRIETOR');
INSERT INTO "person_type" ("id", "name") VALUES ('5', 'ACCOUNTANT');
INSERT INTO "person_type" ("id", "name") VALUES ('6', 'PRINCIPAL');
INSERT INTO "person_type" ("id", "name") VALUES ('7', 'SUPERVISOR');
INSERT INTO "person_type" ("id", "name") VALUES ('8', 'EMPLOYEE');
INSERT INTO "person_type" ("id", "name") VALUES ('9', 'HEADTEACHER');
INSERT INTO "person_type" ("id", "name") VALUES ('10', 'CONTACT PERSON/UNKNOWN');

SELECT setval(pg_get_serial_sequence('"person_type"', 'id'), COALESCE((SELECT MAX("id")+1 FROM "person_type"), 1), false);


INSERT INTO "enterprise_group_role" ("id", "name", "name_language1", "name_language2", "code") VALUES (1, 'Management/control unit', NULL, NULL, '1');
INSERT INTO "enterprise_group_role" ("id", "name", "name_language1", "name_language2", "code") VALUES (2, 'Global group head (controlling unit)', NULL, NULL, '2');
INSERT INTO "enterprise_group_role" ("id", "name", "name_language1", "name_language2", "code") VALUES (3, 'Global decision centre (managing unit)', NULL, NULL, '3');
INSERT INTO "enterprise_group_role" ("id", "name", "name_language1", "name_language2", "code") VALUES (4, 'Highest level consolidation unit', NULL, NULL, '4');
INSERT INTO "enterprise_group_role" ("id", "name", "name_language1", "name_language2", "code") VALUES (5, 'Other', NULL, NULL, '5');

SELECT setval(pg_get_serial_sequence('"enterprise_group_role"', 'id'), COALESCE((SELECT MAX("id")+1 FROM "enterprise_group_role"), 1), false);


INSERT INTO "enterprise_group_type" ("id", "name", "name_language1", "name_language2", "code") VALUES (1, 'All-residents', 'Все резиденты', 'Бардык резидент', '1');
INSERT INTO "enterprise_group_type" ("id", "name", "name_language1", "name_language2", "code") VALUES (2, 'Multinational domestically controlled ', 'Многонациональный внутренний контроль', 'Көп улуттуу өлкө башкарылат', '2');
INSERT INTO "enterprise_group_type" ("id", "name", "name_language1", "name_language2", "code") VALUES (3, 'Multinational foreign controlled', 'Многонациональный иностранный контроль', 'Көп улуттуу чет элдик көзөмөлдө', '3');

SELECT setval(pg_get_serial_sequence('"enterprise_group_type"', 'id'), COALESCE((SELECT MAX("id")+1 FROM "enterprise_group_type"), 1), false);


INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('1', NULL, '03', 'Oslo', NULL, 'Oslo', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('2', NULL, '11', 'Rogaland', NULL, 'Rogaland', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('3', NULL, '15', 'Møre og Romsdal', NULL, 'Møre og Romsdal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('4', NULL, '18', 'Nordland', NULL, 'Nordland', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('5', NULL, '30', 'Viken', NULL, 'Viken', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('6', NULL, '34', 'Innlandet', NULL, 'Innlandet', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('7', NULL, '38', 'Vestfold og Telemark', NULL, 'Vestfold og Telemark', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('8', NULL, '42', 'Agder', NULL, 'Agder', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('9', NULL, '46', 'Vestland', NULL, 'Vestland', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('10', NULL, '50', 'Trøndelag - Trööndelage', NULL, 'Trøndelag - Trööndelage', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('11', NULL, '54', 'Troms og Finnmark - Romsa ja Finnm�rku', NULL, 'Troms og Finnmark - Romsa ja Finnm�rku', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('12', NULL, '99', 'Uoppgitt', NULL, 'Uoppgitt', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('13', NULL, '0301', 'Oslo', '1', 'Oslo, Oslo', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('14', NULL, '1101', 'Eigersund', '2', 'Rogaland, Eigersund', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('15', NULL, '1103', 'Stavanger', '2', 'Rogaland, Stavanger', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('16', NULL, '1106', 'Haugesund', '2', 'Rogaland, Haugesund', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('17', NULL, '1108', 'Sandnes', '2', 'Rogaland, Sandnes', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('18', NULL, '1111', 'Sokndal', '2', 'Rogaland, Sokndal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('19', NULL, '1112', 'Lund', '2', 'Rogaland, Lund', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('20', NULL, '1114', 'Bjerkreim', '2', 'Rogaland, Bjerkreim', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('21', NULL, '1119', 'Hå', '2', 'Rogaland, Hå', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('22', NULL, '1120', 'Klepp', '2', 'Rogaland, Klepp', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('23', NULL, '1121', 'Time', '2', 'Rogaland, Time', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('24', NULL, '1122', 'Gjesdal', '2', 'Rogaland, Gjesdal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('25', NULL, '1124', 'Sola', '2', 'Rogaland, Sola', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('26', NULL, '1127', 'Randaberg', '2', 'Rogaland, Randaberg', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('27', NULL, '1130', 'Strand', '2', 'Rogaland, Strand', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('28', NULL, '1133', 'Hjelmeland', '2', 'Rogaland, Hjelmeland', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('29', NULL, '1134', 'Suldal', '2', 'Rogaland, Suldal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('30', NULL, '1135', 'Sauda', '2', 'Rogaland, Sauda', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('31', NULL, '1144', 'Kvitsøy', '2', 'Rogaland, Kvitsøy', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('32', NULL, '1145', 'Bokn', '2', 'Rogaland, Bokn', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('33', NULL, '1146', 'Tysvær', '2', 'Rogaland, Tysvær', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('34', NULL, '1149', 'Karmøy', '2', 'Rogaland, Karmøy', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('35', NULL, '1151', 'Utsira', '2', 'Rogaland, Utsira', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('36', NULL, '1160', 'Vindafjord', '2', 'Rogaland, Vindafjord', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('37', NULL, '1505', 'Kristiansund', '3', 'Møre og Romsdal, Kristiansund', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('38', NULL, '1506', 'Molde', '3', 'Møre og Romsdal, Molde', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('39', NULL, '1507', 'Ålesund', '3', 'Møre og Romsdal, Ålesund', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('40', NULL, '1511', 'Vanylven', '3', 'Møre og Romsdal, Vanylven', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('41', NULL, '1514', 'Sande', '3', 'Møre og Romsdal, Sande', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('42', NULL, '1515', 'Herøy (Møre og Romsdal)', '3', 'Møre og Romsdal, Herøy (Møre og Romsdal)', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('43', NULL, '1516', 'Ulstein', '3', 'Møre og Romsdal, Ulstein', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('44', NULL, '1517', 'Hareid', '3', 'Møre og Romsdal, Hareid', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('45', NULL, '1520', 'Ørsta', '3', 'Møre og Romsdal, Ørsta', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('46', NULL, '1525', 'Stranda', '3', 'Møre og Romsdal, Stranda', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('47', NULL, '1528', 'Sykkylven', '3', 'Møre og Romsdal, Sykkylven', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('48', NULL, '1531', 'Sula', '3', 'Møre og Romsdal, Sula', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('49', NULL, '1532', 'Giske', '3', 'Møre og Romsdal, Giske', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('50', NULL, '1535', 'Vestnes', '3', 'Møre og Romsdal, Vestnes', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('51', NULL, '1539', 'Rauma', '3', 'Møre og Romsdal, Rauma', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('52', NULL, '1547', 'Aukra', '3', 'Møre og Romsdal, Aukra', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('53', NULL, '1554', 'Averøy', '3', 'Møre og Romsdal, Averøy', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('54', NULL, '1557', 'Gjemnes', '3', 'Møre og Romsdal, Gjemnes', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('55', NULL, '1560', 'Tingvoll', '3', 'Møre og Romsdal, Tingvoll', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('56', NULL, '1563', 'Sunndal', '3', 'Møre og Romsdal, Sunndal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('57', NULL, '1566', 'Surnadal', '3', 'Møre og Romsdal, Surnadal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('58', NULL, '1573', 'Smøla', '3', 'Møre og Romsdal, Smøla', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('59', NULL, '1576', 'Aure', '3', 'Møre og Romsdal, Aure', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('60', NULL, '1577', 'Volda', '3', 'Møre og Romsdal, Volda', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('61', NULL, '1578', 'Fjord', '3', 'Møre og Romsdal, Fjord', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('62', NULL, '1579', 'Hustadvika', '3', 'Møre og Romsdal, Hustadvika', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('63', NULL, '1804', 'Bodø', '4', 'Nordland, Bodø', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('64', NULL, '1806', 'Narvik', '4', 'Nordland, Narvik', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('65', NULL, '1811', 'Bindal', '4', 'Nordland, Bindal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('66', NULL, '1812', 'Sømna', '4', 'Nordland, Sømna', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('67', NULL, '1813', 'Brønnøy', '4', 'Nordland, Brønnøy', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('68', NULL, '1815', 'Vega', '4', 'Nordland, Vega', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('69', NULL, '1816', 'Vevelstad', '4', 'Nordland, Vevelstad', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('70', NULL, '1818', 'Herøy (Nordland)', '4', 'Nordland, Herøy (Nordland)', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('71', NULL, '1820', 'Alstahaug', '4', 'Nordland, Alstahaug', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('72', NULL, '1822', 'Leirfjord', '4', 'Nordland, Leirfjord', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('73', NULL, '1824', 'Vefsn', '4', 'Nordland, Vefsn', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('74', NULL, '1825', 'Grane', '4', 'Nordland, Grane', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('75', NULL, '1826', 'Aarborte - Hattfjelldal', '4', 'Nordland, Aarborte - Hattfjelldal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('76', NULL, '1827', 'Dønna', '4', 'Nordland, Dønna', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('77', NULL, '1828', 'Nesna', '4', 'Nordland, Nesna', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('78', NULL, '1832', 'Hemnes', '4', 'Nordland, Hemnes', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('79', NULL, '1833', 'Rana', '4', 'Nordland, Rana', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('80', NULL, '1834', 'Lurøy', '4', 'Nordland, Lurøy', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('81', NULL, '1835', 'Træna', '4', 'Nordland, Træna', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('82', NULL, '1836', 'Rødøy', '4', 'Nordland, Rødøy', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('83', NULL, '1837', 'Meløy', '4', 'Nordland, Meløy', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('84', NULL, '1838', 'Gildeskål', '4', 'Nordland, Gildeskål', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('85', NULL, '1839', 'Beiarn', '4', 'Nordland, Beiarn', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('86', NULL, '1840', 'Saltdal', '4', 'Nordland, Saltdal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('87', NULL, '1841', 'Fauske - Fuossko', '4', 'Nordland, Fauske - Fuossko', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('88', NULL, '1845', 'Sørfold', '4', 'Nordland, Sørfold', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('89', NULL, '1848', 'Steigen', '4', 'Nordland, Steigen', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('90', NULL, '1851', 'Lødingen', '4', 'Nordland, Lødingen', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('91', NULL, '1853', 'Evenes', '4', 'Nordland, Evenes', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('92', NULL, '1856', 'Røst', '4', 'Nordland, Røst', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('93', NULL, '1857', 'Værøy', '4', 'Nordland, Værøy', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('94', NULL, '1859', 'Flakstad', '4', 'Nordland, Flakstad', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('95', NULL, '1860', 'Vestvågøy', '4', 'Nordland, Vestvågøy', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('96', NULL, '1865', 'Vågan', '4', 'Nordland, Vågan', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('97', NULL, '1866', 'Hadsel', '4', 'Nordland, Hadsel', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('98', NULL, '1867', 'Bø', '4', 'Nordland, Bø', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('99', NULL, '1868', 'Øksnes', '4', 'Nordland, Øksnes', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('100', NULL, '1870', 'Sortland', '4', 'Nordland, Sortland', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('101', NULL, '1871', 'Andøy', '4', 'Nordland, Andøy', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('102', NULL, '1874', 'Moskenes', '4', 'Nordland, Moskenes', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('103', NULL, '1875', 'Hamarøy - Hábmer', '4', 'Nordland, Hamarøy - Hábmer', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('104', NULL, '3001', 'Halden', '5', 'Viken, Halden', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('105', NULL, '3002', 'Moss', '5', 'Viken, Moss', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('106', NULL, '3003', 'Sarpsborg', '5', 'Viken, Sarpsborg', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('107', NULL, '3004', 'Fredrikstad', '5', 'Viken, Fredrikstad', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('108', NULL, '3005', 'Drammen', '5', 'Viken, Drammen', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('109', NULL, '3006', 'Kongsberg', '5', 'Viken, Kongsberg', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('110', NULL, '3007', 'Ringerike', '5', 'Viken, Ringerike', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('111', NULL, '3011', 'Hvaler', '5', 'Viken, Hvaler', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('112', NULL, '3012', 'Aremark', '5', 'Viken, Aremark', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('113', NULL, '3013', 'Marker', '5', 'Viken, Marker', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('114', NULL, '3014', 'Indre Østfold', '5', 'Viken, Indre Østfold', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('115', NULL, '3015', 'Skiptvet', '5', 'Viken, Skiptvet', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('116', NULL, '3016', 'Rakkestad', '5', 'Viken, Rakkestad', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('117', NULL, '3017', 'Råde', '5', 'Viken, Råde', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('118', NULL, '3018', 'Våler (Viken)', '5', 'Viken, Våler (Viken)', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('119', NULL, '3019', 'Vestby', '5', 'Viken, Vestby', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('120', NULL, '3020', 'Nordre Follo', '5', 'Viken, Nordre Follo', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('121', NULL, '3021', 'Ås', '5', 'Viken, Ås', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('122', NULL, '3022', 'Frogn', '5', 'Viken, Frogn', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('123', NULL, '3023', 'Nesodden', '5', 'Viken, Nesodden', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('124', NULL, '3024', 'Bærum', '5', 'Viken, Bærum', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('125', NULL, '3025', 'Asker', '5', 'Viken, Asker', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('126', NULL, '3026', 'Aurskog-Høland', '5', 'Viken, Aurskog-Høland', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('127', NULL, '3027', 'Rælingen', '5', 'Viken, Rælingen', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('128', NULL, '3028', 'Enebakk', '5', 'Viken, Enebakk', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('129', NULL, '3029', 'Lørenskog', '5', 'Viken, Lørenskog', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('130', NULL, '3030', 'Lillestrøm', '5', 'Viken, Lillestrøm', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('131', NULL, '3031', 'Nittedal', '5', 'Viken, Nittedal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('132', NULL, '3032', 'Gjerdrum', '5', 'Viken, Gjerdrum', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('133', NULL, '3033', 'Ullensaker', '5', 'Viken, Ullensaker', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('134', NULL, '3034', 'Nes', '5', 'Viken, Nes', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('135', NULL, '3035', 'Eidsvoll', '5', 'Viken, Eidsvoll', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('136', NULL, '3036', 'Nannestad', '5', 'Viken, Nannestad', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('137', NULL, '3037', 'Hurdal', '5', 'Viken, Hurdal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('138', NULL, '3038', 'Hole', '5', 'Viken, Hole', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('139', NULL, '3039', 'Flå', '5', 'Viken, Flå', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('140', NULL, '3040', 'Nesbyen', '5', 'Viken, Nesbyen', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('141', NULL, '3041', 'Gol', '5', 'Viken, Gol', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('142', NULL, '3042', 'Hemsedal', '5', 'Viken, Hemsedal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('143', NULL, '3043', 'Ål', '5', 'Viken, Ål', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('144', NULL, '3044', 'Hol', '5', 'Viken, Hol', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('145', NULL, '3045', 'Sigdal', '5', 'Viken, Sigdal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('146', NULL, '3046', 'Krødsherad', '5', 'Viken, Krødsherad', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('147', NULL, '3047', 'Modum', '5', 'Viken, Modum', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('148', NULL, '3048', 'Øvre Eiker', '5', 'Viken, Øvre Eiker', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('149', NULL, '3049', 'Lier', '5', 'Viken, Lier', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('150', NULL, '3050', 'Flesberg', '5', 'Viken, Flesberg', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('151', NULL, '3051', 'Rollag', '5', 'Viken, Rollag', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('152', NULL, '3052', 'Nore og Uvdal', '5', 'Viken, Nore og Uvdal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('153', NULL, '3053', 'Jevnaker', '5', 'Viken, Jevnaker', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('154', NULL, '3054', 'Lunner', '5', 'Viken, Lunner', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('155', NULL, '3401', 'Kongsvinger', '6', 'Innlandet, Kongsvinger', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('156', NULL, '3403', 'Hamar', '6', 'Innlandet, Hamar', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('157', NULL, '3405', 'Lillehammer', '6', 'Innlandet, Lillehammer', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('158', NULL, '3407', 'Gjøvik', '6', 'Innlandet, Gjøvik', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('159', NULL, '3411', 'Ringsaker', '6', 'Innlandet, Ringsaker', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('160', NULL, '3412', 'Løten', '6', 'Innlandet, Løten', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('161', NULL, '3413', 'Stange', '6', 'Innlandet, Stange', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('162', NULL, '3414', 'Nord-Odal', '6', 'Innlandet, Nord-Odal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('163', NULL, '3415', 'Sør-Odal', '6', 'Innlandet, Sør-Odal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('164', NULL, '3416', 'Eidskog', '6', 'Innlandet, Eidskog', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('165', NULL, '3417', 'Grue', '6', 'Innlandet, Grue', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('166', NULL, '3418', 'Åsnes', '6', 'Innlandet, Åsnes', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('167', NULL, '3419', 'Våler (Innlandet)', '6', 'Innlandet, Våler (Innlandet)', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('168', NULL, '3420', 'Elverum', '6', 'Innlandet, Elverum', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('169', NULL, '3421', 'Trysil', '6', 'Innlandet, Trysil', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('170', NULL, '3422', 'Åmot', '6', 'Innlandet, Åmot', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('171', NULL, '3423', 'Stor-Elvdal', '6', 'Innlandet, Stor-Elvdal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('172', NULL, '3424', 'Rendalen', '6', 'Innlandet, Rendalen', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('173', NULL, '3425', 'Engerdal', '6', 'Innlandet, Engerdal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('174', NULL, '3426', 'Tolga', '6', 'Innlandet, Tolga', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('175', NULL, '3427', 'Tynset', '6', 'Innlandet, Tynset', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('176', NULL, '3428', 'Alvdal', '6', 'Innlandet, Alvdal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('177', NULL, '3429', 'Folldal', '6', 'Innlandet, Folldal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('178', NULL, '3430', 'Os', '6', 'Innlandet, Os', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('179', NULL, '3431', 'Dovre', '6', 'Innlandet, Dovre', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('180', NULL, '3432', 'Lesja', '6', 'Innlandet, Lesja', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('181', NULL, '3433', 'Skjåk', '6', 'Innlandet, Skjåk', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('182', NULL, '3434', 'Lom', '6', 'Innlandet, Lom', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('183', NULL, '3435', 'Vågå', '6', 'Innlandet, Vågå', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('184', NULL, '3436', 'Nord-Fron', '6', 'Innlandet, Nord-Fron', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('185', NULL, '3437', 'Sel', '6', 'Innlandet, Sel', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('186', NULL, '3438', 'Sør-Fron', '6', 'Innlandet, Sør-Fron', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('187', NULL, '3439', 'Ringebu', '6', 'Innlandet, Ringebu', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('188', NULL, '3440', 'Øyer', '6', 'Innlandet, Øyer', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('189', NULL, '3441', 'Gausdal', '6', 'Innlandet, Gausdal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('190', NULL, '3442', 'Østre Toten', '6', 'Innlandet, Østre Toten', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('191', NULL, '3443', 'Vestre Toten', '6', 'Innlandet, Vestre Toten', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('192', NULL, '3446', 'Gran', '6', 'Innlandet, Gran', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('193', NULL, '3447', 'Søndre Land', '6', 'Innlandet, Søndre Land', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('194', NULL, '3448', 'Nordre Land', '6', 'Innlandet, Nordre Land', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('195', NULL, '3449', 'Sør-Aurdal', '6', 'Innlandet, Sør-Aurdal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('196', NULL, '3450', 'Etnedal', '6', 'Innlandet, Etnedal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('197', NULL, '3451', 'Nord-Aurdal', '6', 'Innlandet, Nord-Aurdal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('198', NULL, '3452', 'Vestre Slidre', '6', 'Innlandet, Vestre Slidre', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('199', NULL, '3453', 'Øystre Slidre', '6', 'Innlandet, Øystre Slidre', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('200', NULL, '3454', 'Vang', '6', 'Innlandet, Vang', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('201', NULL, '3801', 'Horten', '7', 'Vestfold og Telemark, Horten', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('202', NULL, '3802', 'Holmestrand', '7', 'Vestfold og Telemark, Holmestrand', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('203', NULL, '3803', 'Tønsberg', '7', 'Vestfold og Telemark, Tønsberg', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('204', NULL, '3804', 'Sandefjord', '7', 'Vestfold og Telemark, Sandefjord', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('205', NULL, '3805', 'Larvik', '7', 'Vestfold og Telemark, Larvik', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('206', NULL, '3806', 'Porsgrunn', '7', 'Vestfold og Telemark, Porsgrunn', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('207', NULL, '3807', 'Skien', '7', 'Vestfold og Telemark, Skien', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('208', NULL, '3808', 'Notodden', '7', 'Vestfold og Telemark, Notodden', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('209', NULL, '3811', 'Færder', '7', 'Vestfold og Telemark, Færder', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('210', NULL, '3812', 'Siljan', '7', 'Vestfold og Telemark, Siljan', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('211', NULL, '3813', 'Bamble', '7', 'Vestfold og Telemark, Bamble', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('212', NULL, '3814', 'Kragerø', '7', 'Vestfold og Telemark, Kragerø', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('213', NULL, '3815', 'Drangedal', '7', 'Vestfold og Telemark, Drangedal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('214', NULL, '3816', 'Nome', '7', 'Vestfold og Telemark, Nome', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('215', NULL, '3817', 'Midt-Telemark', '7', 'Vestfold og Telemark, Midt-Telemark', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('216', NULL, '3818', 'Tinn', '7', 'Vestfold og Telemark, Tinn', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('217', NULL, '3819', 'Hjartdal', '7', 'Vestfold og Telemark, Hjartdal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('218', NULL, '3820', 'Seljord', '7', 'Vestfold og Telemark, Seljord', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('219', NULL, '3821', 'Kviteseid', '7', 'Vestfold og Telemark, Kviteseid', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('220', NULL, '3822', 'Nissedal', '7', 'Vestfold og Telemark, Nissedal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('221', NULL, '3823', 'Fyresdal', '7', 'Vestfold og Telemark, Fyresdal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('222', NULL, '3824', 'Tokke', '7', 'Vestfold og Telemark, Tokke', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('223', NULL, '3825', 'Vinje', '7', 'Vestfold og Telemark, Vinje', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('224', NULL, '4201', 'Risør', '8', 'Agder, Risør', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('225', NULL, '4202', 'Grimstad', '8', 'Agder, Grimstad', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('226', NULL, '4203', 'Arendal', '8', 'Agder, Arendal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('227', NULL, '4204', 'Kristiansand', '8', 'Agder, Kristiansand', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('228', NULL, '4205', 'Lindesnes', '8', 'Agder, Lindesnes', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('229', NULL, '4206', 'Farsund', '8', 'Agder, Farsund', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('230', NULL, '4207', 'Flekkefjord', '8', 'Agder, Flekkefjord', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('231', NULL, '4211', 'Gjerstad', '8', 'Agder, Gjerstad', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('232', NULL, '4212', 'Vegårshei', '8', 'Agder, Vegårshei', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('233', NULL, '4213', 'Tvedestrand', '8', 'Agder, Tvedestrand', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('234', NULL, '4214', 'Froland', '8', 'Agder, Froland', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('235', NULL, '4215', 'Lillesand', '8', 'Agder, Lillesand', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('236', NULL, '4216', 'Birkenes', '8', 'Agder, Birkenes', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('237', NULL, '4217', 'Åmli', '8', 'Agder, Åmli', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('238', NULL, '4218', 'Iveland', '8', 'Agder, Iveland', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('239', NULL, '4219', 'Evje og Hornnes', '8', 'Agder, Evje og Hornnes', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('240', NULL, '4220', 'Bygland', '8', 'Agder, Bygland', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('241', NULL, '4221', 'Valle', '8', 'Agder, Valle', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('242', NULL, '4222', 'Bykle', '8', 'Agder, Bykle', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('243', NULL, '4223', 'Vennesla', '8', 'Agder, Vennesla', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('244', NULL, '4224', 'Åseral', '8', 'Agder, Åseral', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('245', NULL, '4225', 'Lyngdal', '8', 'Agder, Lyngdal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('246', NULL, '4226', 'Hægebostad', '8', 'Agder, Hægebostad', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('247', NULL, '4227', 'Kvinesdal', '8', 'Agder, Kvinesdal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('248', NULL, '4228', 'Sirdal', '8', 'Agder, Sirdal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('249', NULL, '4601', 'Bergen', '9', 'Vestland, Bergen', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('250', NULL, '4602', 'Kinn', '9', 'Vestland, Kinn', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('251', NULL, '4611', 'Etne', '9', 'Vestland, Etne', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('252', NULL, '4612', 'Sveio', '9', 'Vestland, Sveio', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('253', NULL, '4613', 'Bømlo', '9', 'Vestland, Bømlo', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('254', NULL, '4614', 'Stord', '9', 'Vestland, Stord', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('255', NULL, '4615', 'Fitjar', '9', 'Vestland, Fitjar', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('256', NULL, '4616', 'Tysnes', '9', 'Vestland, Tysnes', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('257', NULL, '4617', 'Kvinnherad', '9', 'Vestland, Kvinnherad', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('258', NULL, '4618', 'Ullensvang', '9', 'Vestland, Ullensvang', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('259', NULL, '4619', 'Eidfjord', '9', 'Vestland, Eidfjord', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('260', NULL, '4620', 'Ulvik', '9', 'Vestland, Ulvik', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('261', NULL, '4621', 'Voss', '9', 'Vestland, Voss', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('262', NULL, '4622', 'Kvam', '9', 'Vestland, Kvam', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('263', NULL, '4623', 'Samnanger', '9', 'Vestland, Samnanger', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('264', NULL, '4624', 'Bjørnafjorden', '9', 'Vestland, Bjørnafjorden', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('265', NULL, '4625', 'Austevoll', '9', 'Vestland, Austevoll', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('266', NULL, '4626', 'Øygarden', '9', 'Vestland, Øygarden', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('267', NULL, '4627', 'Askøy', '9', 'Vestland, Askøy', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('268', NULL, '4628', 'Vaksdal', '9', 'Vestland, Vaksdal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('269', NULL, '4629', 'Modalen', '9', 'Vestland, Modalen', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('270', NULL, '4630', 'Osterøy', '9', 'Vestland, Osterøy', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('271', NULL, '4631', 'Alver', '9', 'Vestland, Alver', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('272', NULL, '4632', 'Austrheim', '9', 'Vestland, Austrheim', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('273', NULL, '4633', 'Fedje', '9', 'Vestland, Fedje', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('274', NULL, '4634', 'Masfjorden', '9', 'Vestland, Masfjorden', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('275', NULL, '4635', 'Gulen', '9', 'Vestland, Gulen', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('276', NULL, '4636', 'Solund', '9', 'Vestland, Solund', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('277', NULL, '4637', 'Hyllestad', '9', 'Vestland, Hyllestad', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('278', NULL, '4638', 'Høyanger', '9', 'Vestland, Høyanger', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('279', NULL, '4639', 'Vik', '9', 'Vestland, Vik', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('280', NULL, '4640', 'Sogndal', '9', 'Vestland, Sogndal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('281', NULL, '4641', 'Aurland', '9', 'Vestland, Aurland', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('282', NULL, '4642', 'Lærdal', '9', 'Vestland, Lærdal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('283', NULL, '4643', 'Årdal', '9', 'Vestland, Årdal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('284', NULL, '4644', 'Luster', '9', 'Vestland, Luster', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('285', NULL, '4645', 'Askvoll', '9', 'Vestland, Askvoll', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('286', NULL, '4646', 'Fjaler', '9', 'Vestland, Fjaler', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('287', NULL, '4647', 'Sunnfjord', '9', 'Vestland, Sunnfjord', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('288', NULL, '4648', 'Bremanger', '9', 'Vestland, Bremanger', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('289', NULL, '4649', 'Stad', '9', 'Vestland, Stad', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('290', NULL, '4650', 'Gloppen', '9', 'Vestland, Gloppen', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('291', NULL, '4651', 'Stryn', '9', 'Vestland, Stryn', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('292', NULL, '5001', 'Trondheim', '10', 'Trøndelag - Trööndelage, Trondheim', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('293', NULL, '5006', 'Steinkjer', '10', 'Trøndelag - Trööndelage, Steinkjer', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('294', NULL, '5007', 'Namsos', '10', 'Trøndelag - Trööndelage, Namsos', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('295', NULL, '5014', 'Frøya', '10', 'Trøndelag - Trööndelage, Frøya', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('296', NULL, '5020', 'Osen', '10', 'Trøndelag - Trööndelage, Osen', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('297', NULL, '5021', 'Oppdal', '10', 'Trøndelag - Trööndelage, Oppdal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('298', NULL, '5022', 'Rennebu', '10', 'Trøndelag - Trööndelage, Rennebu', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('299', NULL, '5025', 'Røros', '10', 'Trøndelag - Trööndelage, Røros', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('300', NULL, '5026', 'Holtålen', '10', 'Trøndelag - Trööndelage, Holtålen', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('301', NULL, '5027', 'Midtre Gauldal', '10', 'Trøndelag - Trööndelage, Midtre Gauldal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('302', NULL, '5028', 'Melhus', '10', 'Trøndelag - Trööndelage, Melhus', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('303', NULL, '5029', 'Skaun', '10', 'Trøndelag - Trööndelage, Skaun', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('304', NULL, '5031', 'Malvik', '10', 'Trøndelag - Trööndelage, Malvik', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('305', NULL, '5032', 'Selbu', '10', 'Trøndelag - Trööndelage, Selbu', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('306', NULL, '5033', 'Tydal', '10', 'Trøndelag - Trööndelage, Tydal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('307', NULL, '5034', 'Meråker', '10', 'Trøndelag - Trööndelage, Meråker', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('308', NULL, '5035', 'Stjørdal', '10', 'Trøndelag - Trööndelage, Stjørdal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('309', NULL, '5036', 'Frosta', '10', 'Trøndelag - Trööndelage, Frosta', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('310', NULL, '5037', 'Levanger', '10', 'Trøndelag - Trööndelage, Levanger', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('311', NULL, '5038', 'Verdal', '10', 'Trøndelag - Trööndelage, Verdal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('312', NULL, '5041', 'Snåase - Snåsa', '10', 'Trøndelag - Trööndelage, Snåase - Snåsa', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('313', NULL, '5042', 'Lierne', '10', 'Trøndelag - Trööndelage, Lierne', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('314', NULL, '5043', 'Raarvihke - Røyrvik', '10', 'Trøndelag - Trööndelage, Raarvihke - Røyrvik', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('315', NULL, '5044', 'Namsskogan', '10', 'Trøndelag - Trööndelage, Namsskogan', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('316', NULL, '5045', 'Grong', '10', 'Trøndelag - Trööndelage, Grong', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('317', NULL, '5046', 'Høylandet', '10', 'Trøndelag - Trööndelage, Høylandet', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('318', NULL, '5047', 'Overhalla', '10', 'Trøndelag - Trööndelage, Overhalla', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('319', NULL, '5049', 'Flatanger', '10', 'Trøndelag - Trööndelage, Flatanger', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('320', NULL, '5052', 'Leka', '10', 'Trøndelag - Trööndelage, Leka', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('321', NULL, '5053', 'Inderøy', '10', 'Trøndelag - Trööndelage, Inderøy', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('322', NULL, '5054', 'Indre Fosen', '10', 'Trøndelag - Trööndelage, Indre Fosen', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('323', NULL, '5055', 'Heim', '10', 'Trøndelag - Trööndelage, Heim', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('324', NULL, '5056', 'Hitra', '10', 'Trøndelag - Trööndelage, Hitra', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('325', NULL, '5057', 'Ørland', '10', 'Trøndelag - Trööndelage, Ørland', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('326', NULL, '5058', 'Åfjord', '10', 'Trøndelag - Trööndelage, Åfjord', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('327', NULL, '5059', 'Orkland', '10', 'Trøndelag - Trööndelage, Orkland', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('328', NULL, '5060', 'Nærøysund', '10', 'Trøndelag - Trööndelage, Nærøysund', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('329', NULL, '5061', 'Rindal', '10', 'Trøndelag - Trööndelage, Rindal', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('330', NULL, '5401', 'Tromsø', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Tromsø', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('331', NULL, '5402', 'Harstad - Hárstták', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Harstad - Hárstták', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('332', NULL, '5403', 'Alta', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Alta', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('333', NULL, '5404', 'Vardø', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Vardø', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('334', NULL, '5405', 'Vadsø', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Vadsø', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('335', NULL, '5406', 'Hammerfest', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Hammerfest', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('336', NULL, '5411', 'Kvæfjord', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Kvæfjord', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('337', NULL, '5412', 'Tjeldsund', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Tjeldsund', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('338', NULL, '5413', 'Ibestad', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Ibestad', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('339', NULL, '5414', 'Gratangen', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Gratangen', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('340', NULL, '5415', 'Loabák - Lavangen', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Loabák - Lavangen', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('341', NULL, '5416', 'Bardu', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Bardu', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('342', NULL, '5417', 'Salangen', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Salangen', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('343', NULL, '5418', 'Målselv', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Målselv', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('344', NULL, '5419', 'Sørreisa', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Sørreisa', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('345', NULL, '5420', 'Dyrøy', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Dyrøy', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('346', NULL, '5421', 'Senja', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Senja', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('347', NULL, '5422', 'Balsfjord', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Balsfjord', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('348', NULL, '5423', 'Karlsøy', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Karlsøy', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('349', NULL, '5424', 'Lyngen', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Lyngen', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('350', NULL, '5425', 'Storfjord - Omasvuotna - Omasvuono', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Storfjord - Omasvuotna - Omasvuono', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('351', NULL, '5426', 'Gáivuotna - Kåfjord - Kaivuono', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Gáivuotna - Kåfjord - Kaivuono', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('352', NULL, '5427', 'Skjervøy', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Skjervøy', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('353', NULL, '5428', 'Nordreisa - Ráisa - Raisi', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Nordreisa - Ráisa - Raisi', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('354', NULL, '5429', 'Kvænangen', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Kvænangen', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('355', NULL, '5430', 'Guovdageaidnu - Kautokeino', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Guovdageaidnu - Kautokeino', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('356', NULL, '5432', 'Loppa', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Loppa', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('357', NULL, '5433', 'Hasvik', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Hasvik', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('358', NULL, '5434', 'Måsøy', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Måsøy', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('359', NULL, '5435', 'Nordkapp', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Nordkapp', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('360', NULL, '5436', 'Porsanger - Porsá?gu - Porsanki', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Porsanger - Porsá?gu - Porsanki', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('361', NULL, '5437', 'Kárá?johka - Karasjok', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Kárá?johka - Karasjok', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('362', NULL, '5438', 'Lebesby', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Lebesby', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('363', NULL, '5439', 'Gamvik', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Gamvik', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('364', NULL, '5440', 'Berlevåg', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Berlevåg', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('365', NULL, '5441', 'Deatnu - Tana', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Deatnu - Tana', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('366', NULL, '5442', 'Unjárga - Nesseby', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Unjárga - Nesseby', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('367', NULL, '5443', 'Båtsfjord', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Båtsfjord', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('368', NULL, '5444', 'Sør-Varanger', '11', 'Troms og Finnmark - Romsa ja Finnm�rku, Sør-Varanger', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('369', NULL, '9999', 'Uoppgitt', '12', 'Uoppgitt, Uoppgitt', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('370', NULL, '21', 'Svalbard', NULL, 'Svalbard', '1');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('371', NULL, '2100', 'Svalbard', NULL, 'Svalbard', '2');
INSERT INTO "region" ("id", "adminstrative_center", "code", "name", "parent_id", "full_path", "region_level") VALUES ('372', NULL, '0', 'Utlandet', NULL, 'Utlandet', '1');

SELECT setval(pg_get_serial_sequence('"region"', 'id'), COALESCE((SELECT MAX("id")+1 FROM "region"), 1), false);

END;

