BEGIN;

CREATE TABLE public.person_for_unit (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    valid_range daterange NOT NULL,
    valid_from date NOT NULL,
    valid_to date,
    valid_until date,
    person_id integer NOT NULL REFERENCES public.person(id) ON DELETE RESTRICT,
    person_role_id integer REFERENCES public.person_role(id),
    data_source_id integer REFERENCES public.data_source(id) ON DELETE RESTRICT,
    establishment_id integer,
    legal_unit_id integer,
    CONSTRAINT "One and only one statistical unit id must be set"
    CHECK( establishment_id IS NOT NULL AND legal_unit_id IS     NULL
        OR establishment_id IS     NULL AND legal_unit_id IS NOT NULL
        )
);
CREATE INDEX ix_person_for_unit_person_id ON public.person_for_unit USING btree (person_id);
CREATE INDEX ix_person_for_unit_person_role_id ON public.person_for_unit USING btree (person_role_id);
CREATE INDEX ix_person_for_unit_data_source_id ON public.person_for_unit USING btree (data_source_id);
CREATE INDEX ix_person_for_unit_legal_unit_id ON public.person_for_unit USING btree (legal_unit_id);
CREATE INDEX ix_person_for_unit_establishment_id ON public.person_for_unit USING btree (establishment_id);
CREATE INDEX ix_person_for_unit_legal_unit_id_valid_range ON public.person_for_unit USING gist (legal_unit_id, valid_range);
CREATE INDEX ix_person_for_unit_establishment_id_valid_range ON public.person_for_unit USING gist (establishment_id, valid_range);
CREATE INDEX ix_person_for_unit_valid_range ON public.person_for_unit USING gist (valid_range);

-- Activate era handling with valid_range as the authoritative column.
-- The trigger will synchronize valid_from, valid_until, and valid_to from valid_range.
SELECT sql_saga.add_era('public.person_for_unit', 'valid_range');
-- This creates a PRIMARY KEY with WITHOUT OVERLAPS to ensure that
-- there are no overlapping time periods for the same person_for_unit ID.
SELECT sql_saga.add_unique_key(
    table_oid => 'public.person_for_unit'::regclass,
    key_type => 'primary',
    column_names => ARRAY['id'],
    unique_key_name => 'person_for_unit_id_valid'
);
-- This creates a GIST exclusion constraint (`person_for_unit_natural_key_valid_excl`)
-- to ensure a person cannot have the same role for the same statistical unit (either
-- legal unit or establishment) at the same time. This single key provides the correct
-- signature for sql_saga's temporal_merge to identify entities correctly.
SELECT sql_saga.add_unique_key(
    table_oid => 'public.person_for_unit'::regclass,
    key_type => 'natural',
    column_names => ARRAY['person_id', 'person_role_id', 'legal_unit_id', 'establishment_id'],
    mutually_exclusive_columns => ARRAY['legal_unit_id', 'establishment_id'],
    unique_key_name => 'person_for_unit_natural_key_valid'
);
-- This creates triggers to enforce that a person_for_unit's validity period is always contained
-- within the validity period of its parent establishment.
SELECT sql_saga.add_foreign_key(
    fk_table_oid => 'public.person_for_unit'::regclass,
    fk_column_names => ARRAY['establishment_id'],
    pk_table_oid => 'public.establishment',
    pk_column_names => ARRAY['id']
);
-- This creates triggers to enforce that a person_for_unit's validity period is always contained
-- within the validity period of its parent legal unit.
SELECT sql_saga.add_foreign_key(
    fk_table_oid => 'public.person_for_unit'::regclass,
    fk_column_names => ARRAY['legal_unit_id'],
    pk_table_oid => 'public.legal_unit',
    pk_column_names => ARRAY['id']
);

-- Add a view for portion-of updates, allowing for easier updates to specific time slices.
SELECT sql_saga.add_for_portion_of_view('public.person_for_unit');

END;
