-- Migration: import_job_procedures_for_contact
-- Implements the analyse and operation procedures for the Contact import step.

BEGIN;

-- Procedure to analyse contact data (Batch Oriented)
CREATE OR REPLACE PROCEDURE import.analyse_contact(p_job_id INT, p_batch_row_ids INTEGER[], p_step_code TEXT)
LANGUAGE plpgsql AS $analyse_contact$ -- Function name remains the same, step name changed
DECLARE
    v_job public.import_job;
    v_step public.import_step;
    v_data_table_name TEXT;
    v_sql TEXT;
    v_update_count INT := 0;
BEGIN
    RAISE DEBUG '[Job %] analyse_contact (Batch): Starting analysis for % rows', p_job_id, array_length(p_batch_row_ids, 1);

    -- Get job details
    SELECT * INTO v_job FROM public.import_job ij WHERE id = p_job_id;
    v_data_table_name := v_job.data_table_name; -- Assign separately

    -- Find the step details from the snapshot
    SELECT * INTO v_step FROM jsonb_populate_recordset(NULL::public.import_step, v_job.definition_snapshot->'import_step_list') WHERE code = 'contact';
    IF NOT FOUND THEN
        RAISE EXCEPTION '[Job %] contact step not found in snapshot', p_job_id;
    END IF;

    -- Single-pass update to advance priority and set state for non-skipped rows.
    -- Skipped rows only get their priority advanced.
    -- No new errors are generated by this step.
    v_sql := format($$
        UPDATE public.%1$I dt SET
            last_completed_priority = %2$L,
            state = 'analysing'::public.import_data_state
            -- No error column modification as this step doesn't generate errors
        WHERE dt.row_id = ANY($1);
    $$, v_data_table_name /* %1$I */, v_step.priority /* %2$L */);

    RAISE DEBUG '[Job %] analyse_contact: Updating rows: %', p_job_id, v_sql;
    
    BEGIN
        EXECUTE v_sql USING p_batch_row_ids;
        GET DIAGNOSTICS v_update_count = ROW_COUNT;
        RAISE DEBUG '[Job %] analyse_contact: Processed % rows in single pass.', p_job_id, v_update_count;
    EXCEPTION WHEN OTHERS THEN
        RAISE WARNING '[Job %] analyse_contact: Error during batch update: %', p_job_id, SQLERRM;
        UPDATE public.import_job
        SET error = jsonb_build_object('analyse_contact_batch_error', SQLERRM),
            state = 'finished'
        WHERE id = p_job_id;
        RAISE DEBUG '[Job %] analyse_contact: Marked job as failed due to error: %', p_job_id, SQLERRM;
        RAISE;
    END;

    RAISE DEBUG '[Job %] analyse_contact (Batch): Finished analysis for batch. Processed % rows.', p_job_id, v_update_count;
END;
$analyse_contact$;


-- Procedure to operate (insert/update/upsert) contact data (Batch Oriented)
-- Refactored to handle temporal nature correctly using MERGE for inserts
-- and the set-based temporal functions for replaces/updates.
CREATE OR REPLACE PROCEDURE import.process_contact(p_job_id INT, p_batch_row_ids INTEGER[], p_step_code TEXT)
LANGUAGE plpgsql AS $process_contact$
DECLARE
    v_job public.import_job;
    v_snapshot JSONB;
    v_definition public.import_definition;
    v_step public.import_step;
    v_strategy public.import_strategy;
    v_edit_by_user_id INT;
    v_timestamp TIMESTAMPTZ := clock_timestamp();
    v_data_table_name TEXT;
    v_sql TEXT;
    v_error_count INT := 0;
    v_inserted_new_contact_count INT := 0;
    v_updated_existing_contact_count INT := 0;
    error_message TEXT;
    v_batch_upsert_result RECORD;
    v_batch_upsert_error_row_ids INTEGER[] := ARRAY[]::INTEGER[];
    v_batch_upsert_success_row_ids INTEGER[] := ARRAY[]::INTEGER[];
    v_job_mode public.import_mode;
    v_select_lu_id_expr TEXT := 'NULL::INTEGER'; 
    v_select_est_id_expr TEXT := 'NULL::INTEGER'; 
    v_select_list TEXT;
    v_update_count INT; -- Declaration for v_update_count used in propagation
    v_parent_id_check_sql TEXT;
    v_parent_unavailable_error_key TEXT;
    v_parent_unavailable_error_message TEXT;
    v_parent_check_update_count INT := 0;
    v_start_time TIMESTAMPTZ;
    v_duration_ms NUMERIC;
    v_error_jsonb JSONB;
BEGIN
    v_start_time := clock_timestamp();
    RAISE DEBUG '[Job %] process_contact (Batch): Starting operation for % rows', p_job_id, array_length(p_batch_row_ids, 1);

    -- Get job details and snapshot
    SELECT * INTO v_job FROM public.import_job ij WHERE id = p_job_id;
    v_data_table_name := v_job.data_table_name;
    SELECT * INTO v_definition FROM jsonb_populate_record(NULL::public.import_definition, v_job.definition_snapshot->'import_definition');

    IF v_definition IS NULL THEN
        RAISE EXCEPTION '[Job %] Failed to load valid import_definition object from definition_snapshot', p_job_id;
    END IF;

    -- Find the step details from the snapshot
    SELECT * INTO v_step FROM jsonb_populate_recordset(NULL::public.import_step, v_job.definition_snapshot->'import_step_list') WHERE code = 'contact';
    IF NOT FOUND THEN
        RAISE EXCEPTION '[Job %] contact step not found in snapshot', p_job_id;
    END IF;

    -- Determine operation type and user ID
    v_strategy := v_definition.strategy;
    v_edit_by_user_id := v_job.user_id;

    v_job_mode := v_definition.mode;

    IF v_job_mode = 'legal_unit' THEN
        v_select_lu_id_expr := 'dt.legal_unit_id';
        v_select_est_id_expr := 'NULL::INTEGER';
    ELSIF v_job_mode = 'establishment_formal' THEN
        v_select_lu_id_expr := 'NULL::INTEGER'; -- The contact is for the establishment, not the LU it belongs to.
        v_select_est_id_expr := 'dt.establishment_id';
    ELSIF v_job_mode = 'establishment_informal' THEN
        v_select_lu_id_expr := 'NULL::INTEGER';
        v_select_est_id_expr := 'dt.establishment_id';
    ELSE
        RAISE EXCEPTION '[Job %] process_contact: Unhandled job mode % for unit ID selection. Expected one of (legal_unit, establishment_formal, establishment_informal).', p_job_id, v_job_mode;
    END IF;
    RAISE DEBUG '[Job %] process_contact: Based on mode %, using lu_id_expr: %, est_id_expr: % for table %', 
        p_job_id, v_job_mode, v_select_lu_id_expr, v_select_est_id_expr, v_data_table_name;

    -- Preliminary step: Check for missing parent unit IDs in the _data table.
    IF v_job_mode = 'legal_unit' THEN
        v_parent_id_check_sql := 'dt.legal_unit_id IS NULL';
        v_parent_unavailable_error_message := 'Parent Legal Unit ID was not available when attempting to process contact.';
    ELSIF v_job_mode = 'establishment_formal' THEN
        v_parent_id_check_sql := 'dt.establishment_id IS NULL OR dt.legal_unit_id IS NULL';
        v_parent_unavailable_error_message := 'Parent Establishment ID or Legal Unit ID was not available when attempting to process contact.';
    ELSIF v_job_mode = 'establishment_informal' THEN
        v_parent_id_check_sql := 'dt.establishment_id IS NULL';
        v_parent_unavailable_error_message := 'Parent Establishment ID was not available when attempting to process contact.';
    ELSE
        v_parent_id_check_sql := 'TRUE'; -- Should not happen
        v_parent_unavailable_error_message := format('Parent unit ID for unknown mode ''%s'' was not available when attempting to process contact.', v_job_mode);
    END IF;

    v_parent_unavailable_error_key := v_step.code; -- 'contact'

    EXECUTE format($$
        UPDATE public.%1$I dt SET
            action = 'skip',
            state = 'error',
            error = COALESCE(dt.error, '{}'::jsonb) || jsonb_build_object(%2$L, %3$L)
        WHERE dt.row_id = ANY($1)
          AND dt.action != 'skip'
          AND (%4$s); -- The check for parent ID being NULL
    $$, v_data_table_name /* %1$I */, 
        v_parent_unavailable_error_key /* %2$L */, 
        v_parent_unavailable_error_message /* %3$L */, 
        v_parent_id_check_sql /* %4$s */
    ) USING p_batch_row_ids;
    GET DIAGNOSTICS v_parent_check_update_count = ROW_COUNT;
    IF v_parent_check_update_count > 0 THEN
        RAISE DEBUG '[Job %] process_contact: Marked % rows as skipped due to missing parent unit ID.', p_job_id, v_parent_check_update_count;
    END IF;

    -- Step 1: Fetch batch data into a temporary table, including action
    IF to_regclass('pg_temp.temp_batch_data') IS NOT NULL THEN DROP TABLE temp_batch_data; END IF;
    CREATE TEMP TABLE temp_batch_data (
        data_row_id INTEGER PRIMARY KEY,
        founding_row_id INTEGER, -- Added
        legal_unit_id INT,
        establishment_id INT,
        valid_after DATE, -- Added
        valid_from DATE,
        valid_to DATE,
        data_source_id INT,
        web_address TEXT,
        email_address TEXT,
        phone_number TEXT,
        landline TEXT,
        mobile_number TEXT,
        fax_number TEXT,
        existing_contact_id INT, -- Will be populated later
        edit_by_user_id INT,
        edit_at TIMESTAMPTZ,
        edit_comment TEXT, -- Added
        action public.import_row_action_type
    ) ON COMMIT DROP;

    -- Construct the SELECT list dynamically
    v_select_list := format(
        'dt.row_id, dt.founding_row_id, %s AS legal_unit_id, %s AS establishment_id, dt.derived_valid_after, dt.derived_valid_from, dt.derived_valid_to, dt.data_source_id, dt.web_address, dt.email_address, dt.phone_number, dt.landline, dt.mobile_number, dt.fax_number, dt.edit_by_user_id, dt.edit_at, dt.edit_comment, dt.action', -- Added dt.derived_valid_after, dt.edit_comment, and dt.founding_row_id
        v_select_lu_id_expr, -- Use the correctly set expression
        v_select_est_id_expr  -- Use the correctly set expression
    );

    v_sql := format($$
        INSERT INTO temp_batch_data (
            data_row_id, founding_row_id, legal_unit_id, establishment_id, valid_after, valid_from, valid_to, data_source_id, -- Added valid_after, founding_row_id
            web_address, email_address, phone_number, landline, mobile_number, fax_number,
            edit_by_user_id, edit_at, edit_comment, action -- Added edit_comment
        )
        SELECT %1$s
        FROM public.%2$I dt -- Alias dt is already correctly here, no change needed for this specific line.
        WHERE dt.row_id = ANY($1) AND dt.action != 'skip'
          AND ( -- Ensure at least one contact field has data
            dt.web_address IS NOT NULL OR dt.email_address IS NOT NULL OR dt.phone_number IS NOT NULL OR
            dt.landline IS NOT NULL OR dt.mobile_number IS NOT NULL OR dt.fax_number IS NOT NULL
          );
    $$, v_select_list /* %1$s */, v_data_table_name /* %2$I */);
    RAISE DEBUG '[Job %] process_contact: Fetching batch data: %', p_job_id, v_sql;
    EXECUTE v_sql USING p_batch_row_ids;

    -- Step 2: Determine existing contact IDs
    -- Uses a CTE and founding_row_id to correctly associate all rows of a single unit with one existing contact record.
    v_sql := format($$
        UPDATE temp_batch_data tbd
        SET existing_contact_id = (
            SELECT c.id
            FROM public.contact c
            WHERE CASE
                    WHEN %1$L = 'legal_unit' THEN c.legal_unit_id = tbd.legal_unit_id AND c.establishment_id IS NULL
                    WHEN %1$L IN ('establishment_formal', 'establishment_informal') THEN c.establishment_id = tbd.establishment_id AND c.legal_unit_id IS NULL
                    ELSE FALSE
                  END
            LIMIT 1
        );
    $$, v_job_mode);
    RAISE DEBUG '[Job %] process_contact: Determining existing contact IDs (simplified): %', p_job_id, v_sql;
    EXECUTE v_sql;

    -- Temp table to store newly created contact IDs
    IF to_regclass('pg_temp.temp_created_contacts') IS NOT NULL THEN DROP TABLE temp_created_contacts; END IF;
    CREATE TEMP TABLE temp_created_contacts (
        data_row_id INTEGER PRIMARY KEY,
        new_contact_id INT NOT NULL
    ) ON COMMIT DROP;

    -- Temp table for INSERT action
    IF to_regclass('pg_temp.temp_contact_insert_source') IS NOT NULL THEN DROP TABLE temp_contact_insert_source; END IF;
    CREATE TEMP TABLE temp_contact_insert_source (
        row_id INTEGER PRIMARY KEY, id INT, valid_after DATE NOT NULL, valid_to DATE NOT NULL,
        legal_unit_id INT, establishment_id INT, data_source_id INT,
        web_address TEXT, email_address TEXT, phone_number TEXT, landline TEXT, mobile_number TEXT, fax_number TEXT,
        edit_by_user_id INT, edit_at TIMESTAMPTZ, edit_comment TEXT
    ) ON COMMIT DROP;

    -- Temp table for UPDATE/REPLACE action
    IF to_regclass('pg_temp.temp_contact_upsert_source') IS NOT NULL THEN DROP TABLE temp_contact_upsert_source; END IF;
    CREATE TEMP TABLE temp_contact_upsert_source (
        row_id INTEGER PRIMARY KEY, id INT, valid_after DATE NOT NULL, valid_to DATE NOT NULL,
        legal_unit_id INT, establishment_id INT, data_source_id INT,
        web_address TEXT, email_address TEXT, phone_number TEXT, landline TEXT, mobile_number TEXT, fax_number TEXT,
        edit_by_user_id INT, edit_at TIMESTAMPTZ, edit_comment TEXT
    ) ON COMMIT DROP;

    -- Temp table to gather all processed IDs
    IF to_regclass('pg_temp.temp_processed_action_ids') IS NOT NULL THEN DROP TABLE temp_processed_action_ids; END IF;
    CREATE TEMP TABLE temp_processed_action_ids (
        data_row_id INTEGER PRIMARY KEY,
        actual_contact_id INT NOT NULL
    ) ON COMMIT DROP;

    BEGIN
        -- Stage 1: Handle INSERT actions for new contacts
        RAISE DEBUG '[Job %] process_contact: Handling INSERT actions for new contacts.', p_job_id;
        INSERT INTO temp_contact_insert_source(row_id, id, valid_after, valid_to, legal_unit_id, establishment_id, data_source_id, web_address, email_address, phone_number, landline, mobile_number, fax_number, edit_by_user_id, edit_at, edit_comment)
        SELECT tbd.data_row_id, tbd.existing_contact_id, tbd.valid_after, tbd.valid_to,
               CASE WHEN v_job_mode = 'legal_unit' THEN tbd.legal_unit_id ELSE NULL END,
               CASE WHEN v_job_mode IN ('establishment_formal', 'establishment_informal') THEN tbd.establishment_id ELSE NULL END,
               tbd.data_source_id, tbd.web_address, tbd.email_address, tbd.phone_number, tbd.landline, tbd.mobile_number, tbd.fax_number,
               tbd.edit_by_user_id, tbd.edit_at, tbd.edit_comment
        FROM temp_batch_data tbd
        WHERE (tbd.action = 'insert' OR (tbd.action IN ('replace', 'update') AND tbd.existing_contact_id IS NULL)) -- This is a local INSERT
        ORDER BY tbd.data_row_id;
        GET DIAGNOSTICS v_inserted_new_contact_count = ROW_COUNT;
        
        IF v_inserted_new_contact_count > 0 THEN
            v_batch_upsert_error_row_ids := ARRAY[]::INTEGER[];
            DELETE FROM temp_created_contacts;

            FOR v_batch_upsert_result IN
                SELECT * FROM import.temporal_merge(
                    p_target_schema_name => 'public', p_target_table_name => 'contact', p_source_schema_name => 'pg_temp',
                    p_source_table_name => 'temp_contact_insert_source', p_entity_id_column_names => ARRAY['id'],
                    p_mode => CASE v_strategy WHEN 'insert_or_replace' THEN 'upsert_replace'::import.set_operation_mode WHEN 'insert_or_update'  THEN 'upsert_patch'::import.set_operation_mode WHEN 'insert_only' THEN 'insert_only'::import.set_operation_mode ELSE 'upsert_replace'::import.set_operation_mode END,
                    p_source_row_ids => NULL, p_ephemeral_columns => ARRAY['edit_comment', 'edit_by_user_id', 'edit_at'],
                    p_insert_defaulted_columns => ARRAY['id']
                )
            LOOP
                IF v_batch_upsert_result.status = 'ERROR' THEN v_batch_upsert_error_row_ids := array_append(v_batch_upsert_error_row_ids, v_batch_upsert_result.source_row_id);
                ELSE INSERT INTO temp_created_contacts (data_row_id, new_contact_id) VALUES (v_batch_upsert_result.source_row_id, ((v_batch_upsert_result.target_entity_ids[0]) ->> 'id')::INT); END IF;
            END LOOP;

            -- ID Propagation
            UPDATE temp_batch_data tbd_target SET existing_contact_id = tcc.new_contact_id
            FROM temp_created_contacts tcc
            JOIN temp_batch_data tbd_source ON tcc.data_row_id = tbd_source.data_row_id
            WHERE tbd_target.founding_row_id = tbd_source.founding_row_id;
        END IF;

        -- Stage 2: Handle REPLACE and UPDATE actions
        RAISE DEBUG '[Job %] process_contact: Handling REPLACE/UPDATE actions for existing contacts.', p_job_id;

        INSERT INTO temp_contact_upsert_source(row_id, id, valid_after, valid_to, legal_unit_id, establishment_id, data_source_id, web_address, email_address, phone_number, landline, mobile_number, fax_number, edit_by_user_id, edit_at, edit_comment)
        SELECT tbd.data_row_id, tbd.existing_contact_id, tbd.valid_after, tbd.valid_to,
               CASE WHEN v_job_mode = 'legal_unit' THEN tbd.legal_unit_id ELSE NULL END,
               CASE WHEN v_job_mode IN ('establishment_formal', 'establishment_informal') THEN tbd.establishment_id ELSE NULL END,
               tbd.data_source_id, tbd.web_address, tbd.email_address, tbd.phone_number, tbd.landline, tbd.mobile_number, tbd.fax_number,
               tbd.edit_by_user_id, tbd.edit_at, tbd.edit_comment
        FROM temp_batch_data tbd
        WHERE tbd.action IN ('replace', 'update') AND tbd.data_row_id NOT IN (SELECT row_id FROM temp_contact_insert_source) -- This is a local UPDATE/REPLACE
        ORDER BY tbd.data_row_id;
        GET DIAGNOSTICS v_updated_existing_contact_count = ROW_COUNT;

        IF v_updated_existing_contact_count > 0 THEN
            v_batch_upsert_error_row_ids := ARRAY[]::INTEGER[];
            DELETE FROM temp_processed_action_ids;

            FOR v_batch_upsert_result IN
                SELECT * FROM import.temporal_merge(
                    p_target_schema_name => 'public', p_target_table_name => 'contact', p_source_schema_name => 'pg_temp',
                    p_source_table_name => 'temp_contact_upsert_source', p_entity_id_column_names => ARRAY['id'],
                    p_mode => CASE v_strategy WHEN 'insert_or_replace' THEN 'replace_only'::import.set_operation_mode WHEN 'replace_only' THEN 'replace_only'::import.set_operation_mode WHEN 'insert_or_update'  THEN 'patch_only'::import.set_operation_mode WHEN 'update_only' THEN 'patch_only'::import.set_operation_mode ELSE 'replace_only'::import.set_operation_mode END,
                    p_source_row_ids => NULL, p_ephemeral_columns => ARRAY['edit_comment', 'edit_by_user_id', 'edit_at'],
                    p_insert_defaulted_columns => ARRAY['id']
                )
            LOOP
                IF v_batch_upsert_result.status = 'ERROR' THEN
                    v_batch_upsert_error_row_ids := array_append(v_batch_upsert_error_row_ids, v_batch_upsert_result.source_row_id);
                ELSIF v_batch_upsert_result.status = 'SUCCESS' THEN
                    INSERT INTO temp_processed_action_ids (data_row_id, actual_contact_id) VALUES (v_batch_upsert_result.source_row_id, ((v_batch_upsert_result.target_entity_ids[0]) ->> 'id')::INT);
                END IF; -- MISSING_TARGET is ignored
            END LOOP;
        END IF;

        -- Finalization
        INSERT INTO temp_processed_action_ids (data_row_id, actual_contact_id)
        SELECT data_row_id, new_contact_id FROM temp_created_contacts
        ON CONFLICT (data_row_id) DO NOTHING;

        v_update_count := (SELECT count(*) FROM temp_processed_action_ids);
        v_error_count := v_error_count + array_length(v_batch_upsert_error_row_ids, 1);
        SELECT array_agg(data_row_id) INTO v_batch_upsert_success_row_ids FROM temp_processed_action_ids;

        IF v_update_count > 0 THEN
             EXECUTE format($$
                UPDATE public.%1$I dt SET
                    contact_id = tpai.actual_contact_id,
                    error = NULL,
                    state = 'processed',
                    last_completed_priority = %2$s
                FROM temp_processed_action_ids tpai
                WHERE dt.row_id = tpai.data_row_id AND dt.row_id = ANY($1);
            $$, v_data_table_name, v_step.priority) USING v_batch_upsert_success_row_ids;
        END IF;

    EXCEPTION WHEN OTHERS THEN
        GET STACKED DIAGNOSTICS error_message = MESSAGE_TEXT;
        RAISE WARNING '[Job %] process_contact: Error during operation: %', p_job_id, replace(error_message, '%', '%%');
        UPDATE public.import_job SET error = jsonb_build_object('process_contact_error', error_message), state = 'finished' WHERE id = p_job_id;
        RAISE;
    END;


    -- The framework now handles advancing priority for all rows, including unprocessed and skipped rows. No update needed here.

    v_duration_ms := (EXTRACT(EPOCH FROM (clock_timestamp() - v_start_time)) * 1000);
    RAISE DEBUG '[Job %] process_contact (Batch): Finished operation in % ms. New: %, Replaced: %. Errors: %',
        p_job_id, round(v_duration_ms, 2), v_inserted_new_contact_count, v_updated_existing_contact_count, v_error_count;
END;
$process_contact$;


COMMIT;
