-- Migration: import_job_procedures_for_contact
-- Implements the analyse and operation procedures for the Contact import step.

BEGIN;

-- Procedure to analyse contact data (Batch Oriented)
CREATE OR REPLACE PROCEDURE import.analyse_contact(p_job_id INT, p_batch_row_ids BIGINT[], p_step_code TEXT)
LANGUAGE plpgsql AS $analyse_contact$ -- Function name remains the same, step name changed
DECLARE
    v_job public.import_job;
    v_step RECORD;
    v_data_table_name TEXT;
    v_sql TEXT;
    v_update_count INT := 0;
BEGIN
    RAISE DEBUG '[Job %] analyse_contact (Batch): Starting analysis for % rows', p_job_id, array_length(p_batch_row_ids, 1);

    -- Get job details
    SELECT * INTO v_job FROM public.import_job ij WHERE id = p_job_id;
    v_data_table_name := v_job.data_table_name; -- Assign separately

    -- Find the step details
    SELECT * INTO v_step FROM public.import_step WHERE code = 'contact'; -- Use new step name
    IF NOT FOUND THEN
        RAISE EXCEPTION '[Job %] contact step not found', p_job_id;
    END IF;

    -- Single-pass update to advance priority and set state for non-skipped rows.
    -- Skipped rows only get their priority advanced.
    -- No new errors are generated by this step.
    v_sql := format($$
        UPDATE public.%I dt SET
            last_completed_priority = %L,
            state = CASE
                        WHEN dt.action = 'skip' THEN dt.state -- Keep existing state if skipped
                        ELSE 'analysing'::public.import_data_state -- Set to analysing for non-skipped
                    END
            -- No error column modification as this step doesn't generate errors
        WHERE dt.row_id = ANY(%L);
    $$, v_data_table_name, v_step.priority, p_batch_row_ids);

    RAISE DEBUG '[Job %] analyse_contact: Updating rows: %', p_job_id, v_sql;
    
    BEGIN
        EXECUTE v_sql;
        GET DIAGNOSTICS v_update_count = ROW_COUNT;
        RAISE DEBUG '[Job %] analyse_contact: Processed % rows in single pass.', p_job_id, v_update_count;
    EXCEPTION WHEN OTHERS THEN
        RAISE WARNING '[Job %] analyse_contact: Error during batch update: %', p_job_id, SQLERRM;
        UPDATE public.import_job
        SET error = jsonb_build_object('analyse_contact_batch_error', SQLERRM),
            state = 'finished'
        WHERE id = p_job_id;
        RAISE DEBUG '[Job %] analyse_contact: Marked job as failed due to error: %', p_job_id, SQLERRM;
        RAISE;
    END;

    RAISE DEBUG '[Job %] analyse_contact (Batch): Finished analysis for batch. Processed % rows.', p_job_id, v_update_count;
END;
$analyse_contact$;


-- Procedure to operate (insert/update/upsert) contact data (Batch Oriented)
-- Refactored to handle temporal nature correctly using MERGE for inserts
-- and batch_insert_or_replace for replaces.
CREATE OR REPLACE PROCEDURE import.process_contact(p_job_id INT, p_batch_row_ids BIGINT[], p_step_code TEXT)
LANGUAGE plpgsql AS $process_contact$
DECLARE
    v_job public.import_job;
    v_snapshot JSONB;
    v_definition JSONB;
    v_step RECORD;
    v_strategy public.import_strategy;
    v_edit_by_user_id INT;
    v_timestamp TIMESTAMPTZ := clock_timestamp();
    v_data_table_name TEXT;
    v_sql TEXT;
    v_error_count INT := 0;
    v_inserted_new_contact_count INT := 0;
    v_updated_existing_contact_count INT := 0;
    error_message TEXT;
    v_batch_upsert_result RECORD;
    v_batch_upsert_error_row_ids BIGINT[] := ARRAY[]::BIGINT[];
    v_batch_upsert_success_row_ids BIGINT[] := ARRAY[]::BIGINT[];
    v_job_mode public.import_mode;
    v_select_lu_id_expr TEXT := 'NULL::INTEGER'; 
    v_select_est_id_expr TEXT := 'NULL::INTEGER'; 
    v_select_list TEXT;
BEGIN
    RAISE DEBUG '[Job %] process_contact (Batch): Starting operation for % rows', p_job_id, array_length(p_batch_row_ids, 1);

    -- Get job details and snapshot
    SELECT * INTO v_job FROM public.import_job ij WHERE id = p_job_id;
    v_data_table_name := v_job.data_table_name;
    v_definition := v_job.definition_snapshot->'import_definition';

    IF v_definition IS NULL OR jsonb_typeof(v_definition) != 'object' THEN
        RAISE EXCEPTION '[Job %] Failed to load valid import_definition object from definition_snapshot', p_job_id;
    END IF;

    -- Find the step details
    SELECT * INTO v_step FROM public.import_step WHERE code = 'contact';
    IF NOT FOUND THEN
        RAISE EXCEPTION '[Job %] contact step not found', p_job_id;
    END IF;

    -- Determine operation type and user ID
    v_strategy := (v_definition->>'strategy')::public.import_strategy;
    v_edit_by_user_id := v_job.user_id;

    v_job_mode := (v_job.definition_snapshot->'import_definition'->>'mode')::public.import_mode;

    IF v_job_mode = 'legal_unit' THEN
        v_select_lu_id_expr := 'dt.legal_unit_id';
        v_select_est_id_expr := 'NULL::INTEGER';
    ELSIF v_job_mode = 'establishment_formal' THEN
        v_select_lu_id_expr := 'dt.legal_unit_id';
        v_select_est_id_expr := 'dt.establishment_id';
    ELSIF v_job_mode = 'establishment_informal' THEN
        v_select_lu_id_expr := 'NULL::INTEGER';
        v_select_est_id_expr := 'dt.establishment_id';
    ELSE
        RAISE EXCEPTION '[Job %] process_contact: Unhandled job mode % for unit ID selection. Expected one of (legal_unit, establishment_formal, establishment_informal).', p_job_id, v_job_mode;
    END IF;
    RAISE DEBUG '[Job %] process_contact: Based on mode %, using lu_id_expr: %, est_id_expr: % for table %', 
        p_job_id, v_job_mode, v_select_lu_id_expr, v_select_est_id_expr, v_data_table_name;

    -- Step 1: Fetch batch data into a temporary table, including action
    CREATE TEMP TABLE temp_batch_data (
        data_row_id BIGINT PRIMARY KEY,
        legal_unit_id INT,
        establishment_id INT,
        valid_after DATE, -- Added
        valid_from DATE,
        valid_to DATE,
        data_source_id INT,
        web_address TEXT,
        email_address TEXT,
        phone_number TEXT,
        landline TEXT,
        mobile_number TEXT,
        fax_number TEXT,
        existing_contact_id INT, -- Will be populated later
        edit_by_user_id INT,
        edit_at TIMESTAMPTZ,
        edit_comment TEXT, -- Added
        action public.import_row_action_type
    ) ON COMMIT DROP;

    -- Construct the SELECT list dynamically
    v_select_list := format(
        'dt.row_id, %s AS legal_unit_id, %s AS establishment_id, dt.derived_valid_after, dt.derived_valid_from, dt.derived_valid_to, dt.data_source_id, dt.web_address, dt.email_address, dt.phone_number, dt.landline, dt.mobile_number, dt.fax_number, dt.edit_by_user_id, dt.edit_at, dt.edit_comment, dt.action', -- Added dt.derived_valid_after and dt.edit_comment
        v_select_lu_id_expr, -- Use the correctly set expression
        v_select_est_id_expr  -- Use the correctly set expression
    );

    v_sql := format($$
        INSERT INTO temp_batch_data (
            data_row_id, legal_unit_id, establishment_id, valid_after, valid_from, valid_to, data_source_id, -- Added valid_after
            web_address, email_address, phone_number, landline, mobile_number, fax_number,
            edit_by_user_id, edit_at, edit_comment, action -- Added edit_comment
        )
        SELECT %s
        FROM public.%I dt -- Alias dt is already correctly here, no change needed for this specific line.
        WHERE dt.row_id = ANY(%L) AND dt.action != 'skip'
          AND ( -- Ensure at least one contact field has data
            dt.web_address IS NOT NULL OR dt.email_address IS NOT NULL OR dt.phone_number IS NOT NULL OR
            dt.landline IS NOT NULL OR dt.mobile_number IS NOT NULL OR dt.fax_number IS NOT NULL
          );
    $$, v_select_list, v_data_table_name, p_batch_row_ids);
    RAISE DEBUG '[Job %] process_contact: Fetching batch data: %', p_job_id, v_sql;
    EXECUTE v_sql;

    -- Step 2: Determine existing contact IDs (for the specific unit, ignoring time for now)
    -- This is a simplification; batch_insert_or_replace handles the temporal lookup.
    v_sql := format($$
        UPDATE temp_batch_data tbd SET
            existing_contact_id = c.id
        FROM public.contact c
        WHERE c.legal_unit_id IS NOT DISTINCT FROM tbd.legal_unit_id
          AND c.establishment_id IS NOT DISTINCT FROM tbd.establishment_id;
    $$);
    RAISE DEBUG '[Job %] process_contact: Determining existing contact IDs (simplified): %', p_job_id, v_sql;
    EXECUTE v_sql;

    -- Temp table to store newly created contact IDs
    CREATE TEMP TABLE temp_created_contacts (
        data_row_id BIGINT PRIMARY KEY,
        new_contact_id INT NOT NULL
    ) ON COMMIT DROP;

    BEGIN
        -- Handle INSERTs for new contacts (action = 'insert') using MERGE
        RAISE DEBUG '[Job %] process_contact: Handling INSERTS for new contacts using MERGE.', p_job_id;

        WITH source_for_insert AS (
            SELECT * FROM temp_batch_data WHERE action = 'insert'
        ),
        merged_contacts AS (
            MERGE INTO public.contact c
            USING source_for_insert sfi
            ON 1 = 0 -- Always false to force INSERT
            WHEN NOT MATCHED THEN
                INSERT (
                    legal_unit_id, establishment_id, data_source_id,
                    web_address, email_address, phone_number, landline, mobile_number, fax_number,
                    valid_after, valid_to, edit_by_user_id, edit_at, edit_comment -- Changed
                )
                VALUES (
                    CASE WHEN v_job_mode = 'legal_unit' THEN sfi.legal_unit_id ELSE NULL END,
                    CASE WHEN v_job_mode IN ('establishment_formal', 'establishment_informal') THEN sfi.establishment_id ELSE NULL END,
                    sfi.data_source_id,
                    sfi.web_address, sfi.email_address, sfi.phone_number, sfi.landline, sfi.mobile_number, sfi.fax_number,
                    sfi.valid_after, sfi.valid_to, sfi.edit_by_user_id, sfi.edit_at, sfi.edit_comment -- Use sfi.edit_comment
                )
            RETURNING c.id AS new_contact_id, sfi.data_row_id AS data_row_id
        )
        INSERT INTO temp_created_contacts (data_row_id, new_contact_id)
        SELECT data_row_id, new_contact_id
        FROM merged_contacts;

        GET DIAGNOSTICS v_inserted_new_contact_count = ROW_COUNT;
        RAISE DEBUG '[Job %] process_contact: Inserted % new contacts into temp_created_contacts via MERGE.', p_job_id, v_inserted_new_contact_count;

        IF v_inserted_new_contact_count > 0 THEN
            EXECUTE format($$
                UPDATE public.%I dt SET
                    contact_id = tcc.new_contact_id,
                    last_completed_priority = %L,
                    error = NULL,
                    state = %L
                FROM temp_created_contacts tcc
                WHERE dt.row_id = tcc.data_row_id AND dt.state != 'error';
            $$, v_data_table_name, v_step.priority, 'processing'::public.import_data_state);
            RAISE DEBUG '[Job %] process_contact: Updated _data table for % new contacts.', p_job_id, v_inserted_new_contact_count;
        END IF;

        -- Handle REPLACES for existing contacts (action = 'replace') using batch_insert_or_replace
        RAISE DEBUG '[Job %] process_contact: Handling REPLACES for existing contacts via batch_upsert.', p_job_id;

        CREATE TEMP TABLE temp_contact_upsert_source (
            data_row_id BIGINT PRIMARY KEY, 
            id INT, 
            valid_after DATE NOT NULL, -- Changed
            valid_to DATE NOT NULL,
            legal_unit_id INT,
            establishment_id INT,
            data_source_id INT,
            web_address TEXT,
            email_address TEXT,
            phone_number TEXT,
            landline TEXT,
            mobile_number TEXT,
            fax_number TEXT,
            edit_by_user_id INT,
            edit_at TIMESTAMPTZ,
            edit_comment TEXT
        ) ON COMMIT DROP;

        INSERT INTO temp_contact_upsert_source (
            data_row_id, id, valid_after, valid_to, legal_unit_id, establishment_id, data_source_id, -- Changed valid_from to valid_after
            web_address, email_address, phone_number, landline, mobile_number, fax_number,
            edit_by_user_id, edit_at, edit_comment
        )
        SELECT
            tbd.data_row_id,
            tbd.existing_contact_id, 
            tbd.valid_after, -- Changed
            tbd.valid_to,
            CASE WHEN v_job_mode = 'legal_unit' THEN tbd.legal_unit_id ELSE NULL END,
            CASE WHEN v_job_mode IN ('establishment_formal', 'establishment_informal') THEN tbd.establishment_id ELSE NULL END,
            tbd.data_source_id,
            tbd.web_address, tbd.email_address, tbd.phone_number, tbd.landline, tbd.mobile_number, tbd.fax_number,
            tbd.edit_by_user_id,
            tbd.edit_at,
            tbd.edit_comment -- Use tbd.edit_comment
        FROM temp_batch_data tbd
        WHERE tbd.action = 'replace' AND tbd.existing_contact_id IS NOT NULL; 

        GET DIAGNOSTICS v_updated_existing_contact_count = ROW_COUNT;
        RAISE DEBUG '[Job %] process_contact: Populated temp_contact_upsert_source with % rows for batch replace.', p_job_id, v_updated_existing_contact_count;

        IF v_updated_existing_contact_count > 0 THEN
            RAISE DEBUG '[Job %] process_contact: Calling batch_insert_or_replace_generic_valid_time_table for contact.', p_job_id;
            FOR v_batch_upsert_result IN
                SELECT * FROM import.batch_insert_or_replace_generic_valid_time_table(
                    p_target_schema_name => 'public',
                    p_target_table_name => 'contact',
                    p_source_schema_name => 'pg_temp',
                    p_source_table_name => 'temp_contact_upsert_source',
                    p_source_row_id_column_name => 'data_row_id',
                    p_unique_columns => '[]'::jsonb, 
                    p_temporal_columns => ARRAY['valid_after', 'valid_to'], -- Changed
                    p_ephemeral_columns => ARRAY['edit_comment', 'edit_by_user_id', 'edit_at'],
                    p_id_column_name => 'id'
                )
            LOOP
                IF v_batch_upsert_result.status = 'ERROR' THEN
                    v_batch_upsert_error_row_ids := array_append(v_batch_upsert_error_row_ids, v_batch_upsert_result.source_row_id);
                    EXECUTE format($$
                        UPDATE public.%I SET
                            state = %L,
                            error = COALESCE(error, '{}'::jsonb) || jsonb_build_object('batch_replace_contact_error', %L),
                            last_completed_priority = %L
                        WHERE row_id = %L;
                    $$, v_data_table_name, 'error'::public.import_data_state, v_batch_upsert_result.error_message, v_step.priority - 1, v_batch_upsert_result.source_row_id);
                ELSE
                    v_batch_upsert_success_row_ids := array_append(v_batch_upsert_success_row_ids, v_batch_upsert_result.source_row_id);
                END IF;
            END LOOP;

            v_error_count := array_length(v_batch_upsert_error_row_ids, 1);
            RAISE DEBUG '[Job %] process_contact: Batch replace finished. Success: %, Errors: %', p_job_id, array_length(v_batch_upsert_success_row_ids, 1), v_error_count;

            IF array_length(v_batch_upsert_success_row_ids, 1) > 0 THEN
                EXECUTE format($$
                    UPDATE public.%I dt SET
                        contact_id = tbd.existing_contact_id, -- Use the existing ID for replaces
                        last_completed_priority = %L,
                        error = NULL,
                        state = %L
                    FROM temp_batch_data tbd
                    WHERE dt.row_id = tbd.data_row_id
                      AND dt.row_id = ANY(%L);
                $$, v_data_table_name, v_step.priority, 'processing'::public.import_data_state, v_batch_upsert_success_row_ids);
                RAISE DEBUG '[Job %] process_contact: Updated _data table for % successfully replaced contacts.', p_job_id, array_length(v_batch_upsert_success_row_ids, 1);
            END IF;
        END IF;
        DROP TABLE IF EXISTS temp_contact_upsert_source;

    EXCEPTION WHEN OTHERS THEN
        GET STACKED DIAGNOSTICS error_message = MESSAGE_TEXT;
        RAISE WARNING '[Job %] process_contact: Error during batch operation: %', p_job_id, replace(error_message, '%', '%%');
        UPDATE public.import_job
        SET error = jsonb_build_object('process_contact_error', error_message),
            state = 'finished'
        WHERE id = p_job_id;
        RAISE DEBUG '[Job %] process_contact: Marked job as failed due to error: %', p_job_id, error_message;
        RAISE;
    END;

    -- Update priority for rows that didn't have any contact info or were not processed
    v_sql := format($$
        UPDATE public.%I dt SET
            last_completed_priority = %L
        WHERE dt.row_id = ANY(%L)
          AND dt.action != 'skip'
          AND dt.state NOT IN ('error', 'processing'); -- Only update rows not already handled
    $$, v_data_table_name, v_step.priority, p_batch_row_ids);
    RAISE DEBUG '[Job %] process_contact: Updating priority for unprocessed/no-data rows: %', p_job_id, v_sql;
    EXECUTE v_sql;

    -- Update priority for skipped rows
    EXECUTE format($$UPDATE public.%I SET last_completed_priority = %L WHERE row_id = ANY(%L) AND action = 'skip'$$,
                   v_data_table_name, v_step.priority, p_batch_row_ids);

    RAISE DEBUG '[Job %] process_contact (Batch): Finished operation. New: %, Replaced: %. Errors: %',
        p_job_id, v_inserted_new_contact_count, v_updated_existing_contact_count, v_error_count;

    DROP TABLE IF EXISTS temp_batch_data;
    DROP TABLE IF EXISTS temp_created_contacts;
END;
$process_contact$;


COMMIT;
