-- Migration 20260906173739: statbus_349_upgrade_failure_code
BEGIN;

CREATE TYPE public.upgrade_failure_code AS ENUM (
    'MIGRATION_FAILED',
    'BACKUP_FAILED',
    'DOCKER_UP_FAILED',
    'HEALTHCHECK_REST_DOWN',
    'HEALTHCHECK_APP_DOWN',
    'HEALTHCHECK_DB_DOWN',
    'ROLLBACK_FAILED_GIT_CORRUPT',
    'ROLLBACK_FAILED_DB_RESTORE',
    'UPGRADE_STOPPED_NOTHING_CHANGED',
    'ROLLBACK_FAILED_SERVICES_UP',
    'ROLLBACK_FAILED_SERVICES_NOT_STOPPED',
    'ROLLBACK_FAILED_BINARY_CORRUPT',
    'BINARY_REPLACE_FAILED',
    'BINARY_BUILD_FAILED',
    'INSTALL_FIXUP_FAILED',
    'GIT_FETCH_FAILED_RETRYABLE',
    'INSTALL_PRECONDITION_FAILED'
);

ALTER TABLE public.upgrade
ADD COLUMN failure_code public.upgrade_failure_code NULL;

END;
