-- Migration 20261008172915: statbus_477 key aware generators and code keyed upserts
--
-- STATBUS-477 family C, and the generators made key-aware.
--
-- Family C: legal_rel_type, legal_reorg_type, person_role, power_group_type,
-- region_version. Each carries UNIQUE (code) (<table>_code_key), so a row's
-- identity is its code alone: one row per code, owned by one kind (system or
-- custom), and a custom override of a system code is impossible by schema.
-- No new key and no dedupe: UNIQUE (code) already forbids the duplicate.
-- Their upserts conflicted on (enabled, code) WHERE <t>.id = EXCLUDED.id: the
-- predicate never fires (identity id), so a corrected re-upload was
-- INSERT 0 0, and (enabled, code) cannot see a disabled row, so a system
-- reload after a custom upload disabled the system rows failed on
-- <table>_code_key.
--
-- Key-aware generators. admin.generate_code_upsert_function and
-- admin.generate_path_upsert_function no longer hardcode a conflict target per
-- family: admin.batch_api_identity_key(table_properties) returns the columns of
-- the identity key the table ACTUALLY has, in this order of preference:
--   (code) or (path)          when the table has a unique key on it alone:
--                             one row per code/path, owned by one kind;
--   (code, custom)            when the table has that unique key: one
--                             system row and at most one custom override;
--   otherwise the default the key generator then creates: (code, custom)
--   for code tables with custom (family B), (path) for path tables (family
--   D: the path upsert derives parent_id by path, so a path table with a
--   (path, custom) identity is refused by the generator, not mis-generated).
-- Where identity is the code/path alone, the generated upsert refuses a
-- code/path owned by the other kind with an actionable error (as family D).
-- Every column a generated view accepts is written (description included).
--
-- All 24 generated upserts (families B, C, D and legal_form of family A) are
-- regenerated by the fixed generators, so the installed functions are exactly
-- what a newly generated table gets. The hand-written upserts
-- (legal_form_custom_only, sector_custom_only, activity_category_*,
-- upsert_country) are not generated and are not touched here.
BEGIN;

CREATE FUNCTION admin.batch_api_identity_key(table_properties admin.batch_api_table_properties)
RETURNS text[]
LANGUAGE plpgsql
STABLE
AS $batch_api_identity_key$
DECLARE
    _key_column text;
    _table regclass := format('%I.%I', table_properties.schema_name, table_properties.table_name)::regclass;
BEGIN
    -- STATBUS-477: the identity key a generated upsert must conflict on is the
    -- one the table really has. A unique key on the code/path ALONE wins (one
    -- row per code/path); otherwise (code/path, custom). Non-partial unique
    -- indexes only: a partial index (e.g. WHERE enabled) cannot be an
    -- ON CONFLICT target for every row.
    IF table_properties.has_path THEN
        _key_column := 'path';
    ELSIF table_properties.has_code THEN
        _key_column := 'code';
    ELSE
        RAISE EXCEPTION 'STATBUS-477: % has neither path nor code, so it has no batch API identity key', _table;
    END IF;

    IF EXISTS (
        SELECT 1
          FROM pg_catalog.pg_index AS i
         WHERE i.indrelid = _table
           AND i.indisunique
           AND i.indpred IS NULL
           AND i.indnkeyatts = 1
           AND i.indkey[0] = (SELECT a.attnum FROM pg_catalog.pg_attribute AS a
                               WHERE a.attrelid = _table AND a.attname = _key_column))
    THEN
        RETURN ARRAY[_key_column];
    END IF;

    IF table_properties.has_custom AND EXISTS (
        SELECT 1
          FROM pg_catalog.pg_index AS i
         WHERE i.indrelid = _table
           AND i.indisunique
           AND i.indpred IS NULL
           AND i.indnkeyatts = 2
           AND (SELECT array_agg(a.attname::text ORDER BY a.attname)
                  FROM pg_catalog.pg_attribute AS a
                 WHERE a.attrelid = _table AND a.attnum = ANY (i.indkey::int2[]))
               = (SELECT array_agg(c ORDER BY c) FROM unnest(ARRAY[_key_column, 'custom']) AS c))
    THEN
        RETURN ARRAY[_key_column, 'custom'];
    END IF;

    -- No identity key yet: the default admin.generate_active_code_custom_unique_constraint
    -- creates. Code tables with custom get (code, custom) (one system row and
    -- at most one custom override, STATBUS-477 B); path tables get (path),
    -- since the path upsert derives parent_id by path and needs one row per path.
    IF _key_column = 'code' AND table_properties.has_custom THEN
        RETURN ARRAY['code', 'custom'];
    END IF;
    RETURN ARRAY[_key_column];
END;
$batch_api_identity_key$;

CREATE OR REPLACE FUNCTION admin.generate_active_code_custom_unique_constraint(table_properties admin.batch_api_table_properties)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
    constraint_sql text;
    unique_columns text[];
    index_name text;
    identity_columns text[];
BEGIN
    -- Get the unique columns based on table properties
    unique_columns := admin.get_unique_columns(table_properties);

    -- Construct index name by joining columns with underscores
    index_name := 'ix_' || table_properties.table_name || '_' || array_to_string(unique_columns, '_');

    -- Ensure there are columns to create a constraint for
    IF array_length(unique_columns, 1) IS NOT NULL THEN
        -- Create a unique index for the determined unique columns
        constraint_sql := format($$
CREATE UNIQUE INDEX %I ON public.%I USING btree (%s);
$$, index_name, table_properties.table_name, array_to_string(unique_columns, ', '));

        EXECUTE constraint_sql;
        RAISE NOTICE 'Created unique constraint on (%) for table %', array_to_string(unique_columns, ', '), table_properties.table_name;
    END IF;

    -- STATBUS-477: ensure the identity key the generated upserts conflict on
    -- (admin.batch_api_identity_key) exists: (code) / (path) or
    -- (code, custom). It is a table constraint that outlives the generated
    -- views, so it is created only when absent: drop + regenerate stays
    -- idempotent.
    IF (table_properties.has_code OR table_properties.has_path) THEN
        identity_columns := admin.batch_api_identity_key(table_properties);
        index_name := table_properties.table_name || '_' || array_to_string(identity_columns, '_') || '_key';
        IF NOT EXISTS (
            SELECT 1
              FROM pg_catalog.pg_index AS i
             WHERE i.indrelid = format('%I.%I', table_properties.schema_name, table_properties.table_name)::regclass
               AND i.indisunique
               AND i.indpred IS NULL
               AND i.indnkeyatts = array_length(identity_columns, 1)
               AND (SELECT array_agg(a.attname::text ORDER BY a.attname)
                      FROM pg_catalog.pg_attribute AS a
                     WHERE a.attrelid = i.indrelid AND a.attnum = ANY (i.indkey::int2[]))
                   = (SELECT array_agg(c ORDER BY c) FROM unnest(identity_columns) AS c))
        THEN
            EXECUTE format('ALTER TABLE %I.%I ADD CONSTRAINT %I UNIQUE (%s)'
                , table_properties.schema_name, table_properties.table_name, index_name
                , (SELECT string_agg(quote_ident(c), ', ') FROM unnest(identity_columns) AS c));
            RAISE NOTICE 'Created identity key % for table %', index_name, table_properties.table_name;
        END IF;
    END IF;
END;
$function$
;

CREATE OR REPLACE FUNCTION admin.generate_code_upsert_function(table_properties admin.batch_api_table_properties, view_type admin.view_type_enum)
 RETURNS regprocedure
 LANGUAGE plpgsql
AS $functionx$
DECLARE
    function_schema text := 'admin';
    function_name_str text;
    function_name regprocedure;
    function_sql text;
    custom_value boolean;
    schema_name_str text := table_properties.schema_name;
    table_name_str text := table_properties.table_name;
    content_columns text := 'name';
    content_values text := 'NEW.name';
    content_update_sets text := 'name = NEW.name';
    unique_columns text[];
    kind_guard text := '';
    kind text;
    other_kind text;
BEGIN
    -- Determine custom value based on view type
    IF view_type = 'system' THEN
        custom_value := false;
    ELSIF view_type = 'custom' THEN
        custom_value := true;
    ELSE
        RAISE EXCEPTION 'Invalid view type: %', view_type;
    END IF;

    -- STATBUS-477: conflict on the identity key the table actually has:
    -- (code) when the code alone is unique (one row per code, owned by one
    -- kind), else (code, custom) (one system row and at most one custom
    -- override). Never (enabled, code), which cannot see a disabled row and
    -- treats an enabled custom override and an enabled system row as one, and
    -- never an id = EXCLUDED.id predicate, which cannot fire for an identity id.
    unique_columns := admin.batch_api_identity_key(table_properties);

    -- Utilize has_description from table_properties
    IF table_properties.has_description THEN
        content_columns := content_columns || ', description';
        content_values := content_values || ', NEW.description';
        content_update_sets := content_update_sets || ', description = NEW.description';
    END IF;

    IF table_properties.has_enabled THEN
        content_columns := content_columns || ', enabled';
        -- A custom upload enables its row. A system load enables a NEW system
        -- row unless an enabled custom override of the code exists, and on
        -- update corrects the label only, never the enabled flag (the custom
        -- upload disables system rows on purpose).
        IF view_type = 'custom' THEN
            content_values := content_values || ', TRUE';
            content_update_sets := content_update_sets || ', enabled = TRUE';
        ELSIF unique_columns = ARRAY['code'] THEN
            content_values := content_values || ', TRUE';
        ELSE
            content_values := content_values || format(
                ', NOT EXISTS (SELECT 1 FROM %I.%I AS override WHERE override.code = NEW.code AND override.custom AND override.enabled)'
                , table_properties.schema_name, table_properties.table_name);
        END IF;
    END IF;

    -- Where identity is the code alone, a code belongs to one kind: refuse a
    -- code owned by the other kind with an error the operator can act on.
    IF unique_columns = ARRAY['code'] AND table_properties.has_custom THEN
        IF custom_value THEN
            kind := 'custom';
            other_kind := 'system (standard)';
        ELSE
            kind := 'system (standard)';
            other_kind := 'custom';
        END IF;
        kind_guard := format($guard$
    IF EXISTS (SELECT 1 FROM %1$I.%2$I AS t WHERE t.code = NEW.code AND t.custom IS DISTINCT FROM %3$L) THEN
        RAISE EXCEPTION %4$L, NEW.code
            USING ERRCODE = 'unique_violation', HINT = %5$L;
    END IF;
$guard$
        , table_properties.schema_name, table_properties.table_name, custom_value
        , table_name_str || ' code "%" already exists as a ' || other_kind
          || ' entry, so this ' || kind || ' upload cannot add or change it'
        , CASE WHEN custom_value
               THEN 'A custom entry cannot replace a standard one with the same code. Use a code that is not in the standard list.'
               ELSE 'The standard list cannot overwrite an entry an operator uploaded. Remove or rename the custom entry first.'
          END);
    END IF;

    function_name_str := 'upsert_' || table_name_str || '_' || view_type::text;

    -- Construct the SQL statement for the upsert function
function_sql := format($function$
CREATE FUNCTION %1$I.%2$I()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
DECLARE
    row RECORD;
    _constraint text;
    _detail text;
BEGIN%10$s
    BEGIN
        INSERT INTO %3$I.%4$I (code, %5$s, custom, updated_at)
        VALUES (NEW.code, %6$s, %7$L, statement_timestamp())
        ON CONFLICT (%9$s) DO UPDATE SET
            %8$s,
            updated_at = statement_timestamp()
        RETURNING * INTO row;
    EXCEPTION WHEN unique_violation THEN
        -- Any other unique key (e.g. name) collides: say which, for this row.
        GET STACKED DIAGNOSTICS _constraint = CONSTRAINT_NAME, _detail = PG_EXCEPTION_DETAIL;
        RAISE EXCEPTION %11$L, NEW.code, _detail
            USING ERRCODE = 'unique_violation', CONSTRAINT = _constraint, HINT = %12$L;
    END;

    RAISE DEBUG 'UPSERTED %%', to_json(row);

    -- Report the written row, so the statement's row count is what was stored.
    RETURN NEW;
END;
$body$;
$function$
, function_schema              -- %1$: Function schema name
, function_name_str            -- %2$: Function name
, table_properties.schema_name -- %3$: Schema name for the table
, table_properties.table_name  -- %4$: Table name
, content_columns              -- %5$: Columns to be inserted/updated
, content_values               -- %6$: Values to be inserted
, custom_value                 -- %7$: Boolean indicating system or custom
, content_update_sets          -- %8$: SET clause for the ON CONFLICT update
, array_to_string(unique_columns, ', ') -- %9$: the identity key to conflict on
, kind_guard                   -- %10$: refusal of a code owned by the other kind
, table_name_str || ' code "%" cannot be stored: another entry already has a value that must be unique (%)'
                               -- %11$: message for a collision on any other unique key
, 'Each value in a unique column (such as name) may be used by only one entry. Change the uploaded value, or change the existing entry first.'
                               -- %12$: what the operator can do
);
    EXECUTE function_sql;

    function_name := format('%I.%I()', function_schema, function_name_str)::regprocedure;
    RAISE NOTICE 'Created code-based upsert function: %', function_name;

    RETURN function_name;
END;
$functionx$
;

CREATE OR REPLACE FUNCTION admin.generate_path_upsert_function(table_properties admin.batch_api_table_properties, view_type admin.view_type_enum)
 RETURNS regprocedure
 LANGUAGE plpgsql
AS $functionx$
DECLARE
    function_schema text := 'admin';
    function_name_str text;
    function_name regprocedure;
    function_sql text;
    custom_value boolean;
    schema_name_str text := table_properties.schema_name;
    table_name_str text := table_properties.table_name;
    unique_columns text[];
    insert_enabled text;
    update_enabled text := '';
    description_column text := '';
    description_value text := '';
    description_update text := '';
    kind text;
    other_kind text;
    collision_message text;
    collision_hint text;
BEGIN
    function_name_str := 'upsert_' || table_name_str || '_' || view_type::text;

    -- Determine custom value based on view type
    IF view_type = 'system' THEN
        custom_value := false;
    ELSIF view_type = 'custom' THEN
        custom_value := true;
    ELSE
        RAISE EXCEPTION 'Invalid view type: %', view_type;
    END IF;

    -- STATBUS-477: a path table's identity key is resolved, not assumed:
    -- admin.batch_api_identity_key returns (path) when the path alone is
    -- unique (sector, tag: one row per path, owned by one kind) and
    -- (path, custom) otherwise. The upsert conflicts on it, and where identity
    -- is the path alone it updates only a row of its own kind and refuses a
    -- path the other kind owns with an error the operator can act on.
    -- (enabled, path) missed disabled rows (a system reload after a
    -- custom-only upload failed on the path key), and the id = EXCLUDED.id
    -- predicate never fired.
    unique_columns := admin.batch_api_identity_key(table_properties);
    IF unique_columns <> ARRAY['path'] THEN
        RAISE EXCEPTION 'STATBUS-477: %.% has identity key (%), but generated path upserts need one row per path (they derive parent_id by path); give the table UNIQUE (path)'
            , schema_name_str, table_name_str, array_to_string(unique_columns, ', ');
    END IF;

    -- A custom upload is visible: it inserts and keeps its row enabled. (The
    -- template used NOT custom_value, so generated custom rows were invisible.)
    -- A system load inserts enabled and on update corrects the labels only,
    -- never the enabled flag (a custom-only upload disables system rows).
    IF custom_value THEN
        insert_enabled := 'TRUE';
        update_enabled := ',' || E'\n        ' || 'enabled = TRUE';
        kind := 'custom';
        other_kind := 'system (standard)';
        collision_hint := 'A custom entry cannot replace a standard one with the same path. Use a path that is not in the standard list.';
    ELSE
        insert_enabled := 'TRUE';
        kind := 'system (standard)';
        other_kind := 'custom';
        collision_hint := 'The standard list cannot overwrite an entry an operator uploaded. Remove or rename the custom entry first.';
    END IF;
    collision_message := table_name_str || ' path "%" already exists as a ' || other_kind
        || ' entry, so this ' || kind || ' upload cannot add or change it';

    -- Write every column the generated views accept: the views expose
    -- description when the table has it, and it was silently dropped.
    IF table_properties.has_description THEN
        description_column := ', description';
        description_value := ', NEW.description';
        description_update := ',' || E'\n        ' || 'description = EXCLUDED.description';
    END IF;

    -- Construct the SQL statement for the upsert function
    function_sql := format($function$
CREATE FUNCTION %1$I.%2$I()
RETURNS TRIGGER AS $body$
DECLARE
    existing_custom boolean;
BEGIN
    SELECT t.custom INTO existing_custom
      FROM %3$I.%4$I AS t
     WHERE t.path OPERATOR(public.=) NEW.path
       AND %13$L;
    IF FOUND AND existing_custom IS DISTINCT FROM %5$L THEN
        RAISE EXCEPTION %6$L, NEW.path
            USING ERRCODE = 'unique_violation', HINT = %7$L;
    END IF;

    WITH parent AS (
        SELECT id
        FROM %3$I.%4$I
        WHERE path OPERATOR(public.=) public.subpath(NEW.path, 0, public.nlevel(NEW.path) - 1)
    )
    INSERT INTO %3$I.%4$I (path, parent_id, name%8$s, enabled, custom, updated_at)
    VALUES (NEW.path, (SELECT id FROM parent), NEW.name%9$s, %10$s, %5$L, statement_timestamp())
    ON CONFLICT (%14$s) DO UPDATE SET
        parent_id = (SELECT id FROM parent),
        name = EXCLUDED.name%11$s%12$s,
        updated_at = statement_timestamp();
    -- Report the written row, so the statement's row count is what was stored.
    RETURN NEW;
END;
$body$ LANGUAGE plpgsql;
$function$
, function_schema              -- %1$: Function schema name
, function_name_str            -- %2$: Function name
, schema_name_str              -- %3$: Schema name for the target table
, table_name_str               -- %4$: Table name
, custom_value                 -- %5$: custom value of the rows this upsert owns
, collision_message            -- %6$: error when the other kind owns the path
, collision_hint               -- %7$: what the operator can do
, description_column           -- %8$: description column, if the table has it
, description_value            -- %9$: description value
, insert_enabled               -- %10$: enabled on insert
, description_update           -- %11$: description on update
, update_enabled               -- %12$: enabled on update (custom only)
, unique_columns = ARRAY['path'] -- %13$: identity is the path alone, so a path has one owning kind
, array_to_string(unique_columns, ', ') -- %14$: the identity key to conflict on
);

    EXECUTE function_sql;

    function_name := format('%I.%I()', function_schema, function_name_str)::regprocedure;
    RAISE NOTICE 'Created path-based upsert function: %', function_name;

    RETURN function_name;
END;
$functionx$
;

-- Every generated batch-API upsert, regenerated by the fixed generators so
-- the installed functions are exactly what a newly generated table gets.
-- The view triggers are recreated on the same function names, so the
-- generated views keep working in the same transaction.
DO $regenerate_batch_api_upserts$
DECLARE
    _table text;
    _variant admin.view_type_enum;
    _properties admin.batch_api_table_properties;
BEGIN
    FOREACH _table IN ARRAY ARRAY[
        'legal_form', 'data_source', 'foreign_participation', 'unit_size', 'status',
        'legal_rel_type', 'legal_reorg_type', 'person_role', 'power_group_type', 'region_version',
        'sector', 'tag']
    LOOP
        _properties := admin.detect_batch_api_table_properties(format('public.%I', _table)::regclass);
        FOREACH _variant IN ARRAY ARRAY['custom', 'system']::admin.view_type_enum[] LOOP
            EXECUTE format('DROP TRIGGER %I ON public.%I', 'upsert_' || _table || '_' || _variant, _table || '_' || _variant);
            EXECUTE format('DROP FUNCTION admin.%I()', 'upsert_' || _table || '_' || _variant);
            IF _properties.has_path THEN
                PERFORM admin.generate_path_upsert_function(_properties, _variant);
            ELSE
                PERFORM admin.generate_code_upsert_function(_properties, _variant);
            END IF;
            EXECUTE format('CREATE TRIGGER %I INSTEAD OF INSERT ON public.%I FOR EACH ROW EXECUTE FUNCTION admin.%I()'
                , 'upsert_' || _table || '_' || _variant, _table || '_' || _variant, 'upsert_' || _table || '_' || _variant);
        END LOOP;
    END LOOP;
END;
$regenerate_batch_api_upserts$;

-- The identity keys the regenerated upserts conflict on. Family C keys on the
-- code alone; verify each such key exists (it is relied on, never assumed).
DO $assert_identity_keys$
DECLARE
    _table text;
    _key text[];
    _expected text[];
BEGIN
    FOR _table, _expected IN
        SELECT t.table_name, t.key
          FROM (VALUES
                ('legal_form', ARRAY['code', 'custom']), ('data_source', ARRAY['code', 'custom'])
              , ('foreign_participation', ARRAY['code', 'custom']), ('unit_size', ARRAY['code', 'custom'])
              , ('status', ARRAY['code', 'custom'])
              , ('legal_rel_type', ARRAY['code']), ('legal_reorg_type', ARRAY['code'])
              , ('person_role', ARRAY['code']), ('power_group_type', ARRAY['code'])
              , ('region_version', ARRAY['code'])
              , ('sector', ARRAY['path']), ('tag', ARRAY['path'])) AS t(table_name, key)
    LOOP
        _key := admin.batch_api_identity_key(admin.detect_batch_api_table_properties(format('public.%I', _table)::regclass));
        IF _key IS DISTINCT FROM _expected THEN
            RAISE EXCEPTION 'STATBUS-477: public.% resolves identity key %, expected %', _table, _key, _expected;
        END IF;
    END LOOP;
END;
$assert_identity_keys$;

END;
