// Flat ESLint config (Next.js 16 native flat config). STATBUS-177: introduced
// minimal-first — Next's baseline (core-web-vitals: React + hooks + Next rules, which
// also registers the @typescript-eslint plugin/parser WITHOUT enabling its rule set)
// PLUS a single hard gate: @typescript-eslint/no-explicit-any as an ERROR. We
// deliberately do NOT enable the full @typescript-eslint recommended set here — that
// would bury the `any` gate under hundreds of stylistic findings. Additional rules are
// future tickets, each landing with its own burn-down.
import nextCoreWebVitals from "eslint-config-next/core-web-vitals";

export default [
  {
    // Generated / vendored / build output — never linted.
    ignores: [
      ".next/**",
      "vendor/**",
      "coverage/**",
      "next-env.d.ts",
      "src/lib/database.types.ts", // generated by `./sb types generate`
    ],
  },
  ...nextCoreWebVitals,
  {
    // The @typescript-eslint plugin is registered by core-web-vitals above; enable
    // ONLY the no-explicit-any gate on TS/TSX. No other @typescript-eslint rules.
    files: ["**/*.ts", "**/*.tsx"],
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
    },
  },
  {
    // STATBUS-177 minimal-first: the ONLY hard error gate is no-explicit-any (above).
    // next/core-web-vitals also ships these as errors — real correctness rules, but
    // OUT OF this ticket's `any` burn-down. Downgraded to warn so they stay VISIBLE
    // (each is a future burn-down ticket) without burying/blocking the `any` gate.
    rules: {
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/refs": "warn",
      "react-hooks/immutability": "warn",
      "react/no-unescaped-entities": "warn",
    },
  },
];

