// next.config.js
const dotenv = require('dotenv');
if (process.env.NODE_ENV !== 'production' && !process.env.ENV_LOADED) {
  const envFilePath = '../.env';
  dotenv.config({ path: envFilePath });
  process.env.ENV_LOADED = 'true';
  console.log(`Development Environment file ${envFilePath} loaded successfully.`);
}

// Environment Variable Loading Strategy:
// 1. Local Development (NODE_ENV !== 'production', e.g., `pnpm run dev`):
//    - The `dotenv.config({ path: '../.env' })` block above explicitly loads variables
//      from the project root's `.env` file (which is typically generated by `../devops/manage.cr`).
//    - This ensures local development running directly on the host (outside Docker)
//      has access to necessary configurations.
// 2. Production Builds & Dockerized Environments (NODE_ENV === 'production'):
//    - The `dotenv.config()` block above is SKIPPED because `NODE_ENV` will be 'production'.
//    - Environment variables are primarily sourced from the Docker environment,
//      as defined in `docker-compose.app.yml` (which itself reads from the root `.env` file).
//    - Next.js's built-in support for files like `.env.production` within the `app` directory
//      would also apply if those files exist, but Docker-provided variables typically take precedence.

const isDevelopment = process.env.NODE_ENV === 'development';

// Report DEBUG and PUBLIC_DEBUG status once per process lifecycle, if they are true.
if (!process.env.DEBUG_STATUS_REPORTED) {
  if (process.env.DEBUG === 'true') {
    console.log("next.config.js: DEBUG environment variable is true.");
  }
  if (process.env.PUBLIC_DEBUG === 'true') {
    console.log("next.config.js: PUBLIC_DEBUG environment variable is true.");
  }
  if (process.env.NODE_ENV === 'development') {
   console.log(`next.config.js: NODE_ENV environment variable is: ${process.env.NODE_ENV}`);
  }
  // Set the flag after the first check to prevent repeated logging
  // in subsequent times this config file might be processed.
  process.env.DEBUG_STATUS_REPORTED = 'true';
}

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  // Keep @protobi/exceljs as a Node.js require (not bundled by webpack) so the
  // worker thread's require('@protobi/exceljs') resolves from node_modules
  // in standalone output. This is more robust than the void-expression trick.
  serverExternalPackages: ['@protobi/exceljs'],
  // PUBLIC_* env vars are read server-side by layout.tsx and injected into
  // the HTML as window.__STATBUS_CONFIG__. Client code reads from there.
  // output: 'standalone' is primarily for production builds.
  // Set it conditionally to avoid potential interference with dev server features like proxying.
  ...(isDevelopment && {
    allowedDevOrigins: ['local.statbus.org'],
  }),
};

if (!isDevelopment) {
  nextConfig.output = 'standalone';
}

// Add API proxying in development mode
if (isDevelopment) {
  // This block runs ONCE to set up the dev proxy.
  // In dev, layout.tsx reads PUBLIC_BROWSER_REST_URL to inject into __STATBUS_CONFIG__.
  // We override it to point at the local Next.js server, which proxies to Caddy.
  if (!process.env.PROXY_ENV_VARS_CONFIGURED) {
    const originalBrowserRestUrl = process.env.PUBLIC_BROWSER_REST_URL;
    if (!originalBrowserRestUrl) {
      throw new Error('PUBLIC_BROWSER_REST_URL is not set in .env. Run: ./sb config generate');
    }
    process.env.INTERNAL_CADDY_REWRITE_TARGET = originalBrowserRestUrl.startsWith('http')
      ? originalBrowserRestUrl
      : `http://${originalBrowserRestUrl}`;

    const localAppPort = process.env.PORT || 3000;
    const actualLocalAppUrl = `http://local.statbus.org:${localAppPort}`;
    process.env.INTERNAL_LOCAL_APP_URL = actualLocalAppUrl;

    // Override so layout.tsx injects the local proxy URL into __STATBUS_CONFIG__
    process.env.PUBLIC_BROWSER_REST_URL = actualLocalAppUrl;

    console.log(`Dev proxy: ${actualLocalAppUrl}/rest/* → ${process.env.INTERNAL_CADDY_REWRITE_TARGET}/rest/*`);
    process.env.PROXY_ENV_VARS_CONFIGURED = 'true';
  }

  // This part runs EVERY TIME the config is processed by Next.js.
  // It reads the Caddy target URL that was determined and stored in the "run once" block.
  const caddyTargetForRewriteRule = process.env.INTERNAL_CADDY_REWRITE_TARGET;
  
  nextConfig.rewrites = async () => {
    if (!caddyTargetForRewriteRule) {
      // This condition should ideally not be met if the logic above is sound.
      // If it is, the proxy setup is critically flawed.
      console.error("next.config.js: CRITICAL - INTERNAL_CADDY_REWRITE_TARGET is not set. Proxy will not be configured.");
      return []; // Return no rewrites to prevent errors.
    }
    return [
      {
        source: '/rest/:path*',
        destination: `${caddyTargetForRewriteRule}/rest/:path*`,
      },
    ];
  };
}

module.exports = nextConfig;
