BEGIN;
\i test/setup.sql

\echo '----------------------------------------------------------------------------'
\echo 'Test: Set-based functions with composite and surrogate entity keys'
\echo '----------------------------------------------------------------------------'
SET client_min_messages TO NOTICE;

-- Setup: Create necessary schema and tables for this test
CREATE SCHEMA IF NOT EXISTS set_test_composite;

-- Parent tables
CREATE TABLE set_test_composite.stat_definition (
    id INT PRIMARY KEY,
    name TEXT
);
CREATE TABLE set_test_composite.legal_unit (
    id INT NOT NULL,
    valid_after DATE NOT NULL,
    valid_to DATE NOT NULL,
    name TEXT,
    PRIMARY KEY (id, valid_after)
);
SELECT sql_saga.add_era('set_test_composite.legal_unit', 'valid_after', 'valid_to');
SELECT sql_saga.add_unique_key('set_test_composite.legal_unit', ARRAY['id'], 'valid', 'legal_unit_id_uk');

CREATE TABLE set_test_composite.establishment (
    id INT NOT NULL,
    valid_after DATE NOT NULL,
    valid_to DATE NOT NULL,
    name TEXT,
    PRIMARY KEY (id, valid_after)
);
SELECT sql_saga.add_era('set_test_composite.establishment', 'valid_after', 'valid_to');
SELECT sql_saga.add_unique_key('set_test_composite.establishment', ARRAY['id'], 'valid', 'establishment_id_uk');

-- Target table: stat_for_unit (models public.stat_for_unit)
CREATE TABLE set_test_composite.stat_for_unit (
    stat_definition_id INT NOT NULL,
    establishment_id INT,
    legal_unit_id INT,
    valid_after DATE NOT NULL,
    valid_to DATE NOT NULL,
    value BIGINT,
    edit_comment TEXT, -- Ephemeral column
    -- No single primary key, temporal key is composite + valid_after
    CONSTRAINT one_and_only_one_unit_must_be_set
        CHECK ((establishment_id IS NOT NULL AND legal_unit_id IS NULL) OR (establishment_id IS NULL AND legal_unit_id IS NOT NULL))
);
SELECT sql_saga.add_era('set_test_composite.stat_for_unit', 'valid_after', 'valid_to');
-- The composite keys that identify conceptual entities over time
SELECT sql_saga.add_unique_key('set_test_composite.stat_for_unit', ARRAY['stat_definition_id', 'establishment_id'], 'valid', 'stat_for_unit_est_uk');
SELECT sql_saga.add_unique_key('set_test_composite.stat_for_unit', ARRAY['stat_definition_id', 'legal_unit_id'], 'valid', 'stat_for_unit_lu_uk');

-- Target table that models stat_for_unit even more closely with a surrogate ID
CREATE TABLE set_test_composite.stat_for_unit_with_id (
    id SERIAL PRIMARY KEY, -- Surrogate key with a default
    stat_definition_id INT NOT NULL,
    establishment_id INT,
    valid_after DATE NOT NULL,
    valid_to DATE NOT NULL,
    value BIGINT,
    edit_comment TEXT
);
SELECT sql_saga.add_era('set_test_composite.stat_for_unit_with_id', 'valid_after', 'valid_to');
SELECT sql_saga.add_unique_key('set_test_composite.stat_for_unit_with_id', ARRAY['stat_definition_id', 'establishment_id'], 'valid', 'stat_for_unit_with_id_uk');

-- Target table with surrogate key using IDENTITY, also modeling stat_for_unit
CREATE TABLE set_test_composite.stat_for_unit_with_identity (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- Surrogate key with IDENTITY
    stat_definition_id INT NOT NULL,
    establishment_id INT,
    valid_after DATE NOT NULL,
    valid_to DATE NOT NULL,
    value BIGINT,
    edit_comment TEXT
);
SELECT sql_saga.add_era('set_test_composite.stat_for_unit_with_identity', 'valid_after', 'valid_to');
SELECT sql_saga.add_unique_key('set_test_composite.stat_for_unit_with_identity', ARRAY['stat_definition_id', 'establishment_id'], 'valid', 'stat_for_unit_with_identity_uk');

-- Target table mimicking stat_for_unit (id is NOT NULL w/ DEFAULT, but NOT a PK)
CREATE SEQUENCE set_test_composite.stat_for_unit_no_pk_id_seq;
CREATE TABLE set_test_composite.stat_for_unit_no_pk (
    id INT NOT NULL DEFAULT nextval('set_test_composite.stat_for_unit_no_pk_id_seq'),
    stat_definition_id INT NOT NULL,
    establishment_id INT,
    valid_after DATE NOT NULL,
    valid_to DATE NOT NULL,
    value BIGINT,
    edit_comment TEXT,
    UNIQUE (id, valid_after) -- Mimics unique constraint on stat_for_unit
);
SELECT sql_saga.add_era('set_test_composite.stat_for_unit_no_pk', 'valid_after', 'valid_to');
SELECT sql_saga.add_unique_key('set_test_composite.stat_for_unit_no_pk', ARRAY['stat_definition_id', 'establishment_id'], 'valid', 'stat_for_unit_no_pk_uk');

-- FKs to parent tables
ALTER TABLE set_test_composite.stat_for_unit
    ADD CONSTRAINT stat_definition_fk FOREIGN KEY (stat_definition_id) REFERENCES set_test_composite.stat_definition(id);
SELECT sql_saga.add_foreign_key('set_test_composite.stat_for_unit', ARRAY['establishment_id'], 'valid', 'establishment_id_uk');
SELECT sql_saga.add_foreign_key('set_test_composite.stat_for_unit', ARRAY['legal_unit_id'], 'valid', 'legal_unit_id_uk');

-- Helper procedure to reset the target table for a new scenario
CREATE OR REPLACE PROCEDURE set_test_composite.reset_target() AS $$
BEGIN
    TRUNCATE set_test_composite.stat_definition, set_test_composite.legal_unit, set_test_composite.establishment, set_test_composite.stat_for_unit, set_test_composite.stat_for_unit_with_id, set_test_composite.stat_for_unit_with_identity, set_test_composite.stat_for_unit_no_pk RESTART IDENTITY CASCADE;
    -- Add parent data with more realistic IDs
    INSERT INTO set_test_composite.stat_definition (id, name) VALUES
    (10, 'Total Employees');
    INSERT INTO set_test_composite.legal_unit (id, valid_after, valid_to, name) VALUES
    (200, '1900-01-01', 'infinity', 'LU 200');
    INSERT INTO set_test_composite.establishment (id, valid_after, valid_to, name) VALUES
    (100, '1900-01-01', 'infinity', 'EST 100');
END;
$$ LANGUAGE plpgsql;

-- Parameters for the set-based function
\set target_schema 'set_test_composite'
\set target_table 'stat_for_unit'
\set entity_id_cols '{stat_definition_id, establishment_id}'
\set source_schema 'pg_temp'
\set ephemeral_cols '{edit_comment}'

--------------------------------------------------------------------------------
-- Test `set_insert_or_replace` with a composite key
--------------------------------------------------------------------------------
\echo 'Test Case 1: `set_insert_or_replace` with a composite key (`during` split)'
CALL set_test_composite.reset_target();
INSERT INTO set_test_composite.stat_for_unit (stat_definition_id, establishment_id, legal_unit_id, valid_after, valid_to, value, edit_comment) VALUES
(10, 100, NULL, '2024-01-01', '2024-12-31', 50, 'Original Value');

CREATE TEMP TABLE temp_source (
    row_id INT, stat_definition_id INT, establishment_id INT, legal_unit_id INT, valid_after DATE NOT NULL, valid_to DATE NOT NULL, value BIGINT, edit_comment TEXT
) ON COMMIT DROP;
INSERT INTO temp_source VALUES (1, 10, 100, NULL, '2024-04-01', '2024-08-31', 55, 'Corrected value for mid-year');

\echo 'Calling orchestrator...'
SELECT source_row_id, target_entity_ids, status, error_message FROM import.set_insert_or_replace_generic_valid_time_table(
    :'target_schema',
    :'target_table',
    :'source_schema',
    'temp_source',
    :'entity_id_cols'::TEXT[],
    NULL,
    :'ephemeral_cols'::TEXT[]
);
\echo 'Final state of target table (expected):'
SELECT * FROM (VALUES
    (10, 100, NULL::INT, '2024-01-01'::DATE, '2024-04-01'::DATE, 50::BIGINT, 'Original Value'::TEXT),
    (10, 100, NULL::INT, '2024-04-01'::DATE, '2024-08-31'::DATE, 55::BIGINT, 'Corrected value for mid-year'::TEXT),
    (10, 100, NULL::INT, '2024-08-31'::DATE, '2024-12-31'::DATE, 50::BIGINT, 'Original Value'::TEXT)
) AS t (stat_definition_id, establishment_id, legal_unit_id, valid_after, valid_to, value, edit_comment);
\echo 'Actual state of target table:'
SELECT stat_definition_id, establishment_id, legal_unit_id, valid_after, valid_to, value, edit_comment FROM set_test_composite.stat_for_unit WHERE stat_definition_id = 10 AND establishment_id = 100 ORDER BY valid_after;
DROP TABLE temp_source;

--------------------------------------------------------------------------------
-- Test `set_insert_or_update` with a composite key
--------------------------------------------------------------------------------
\echo 'Test Case 2: `set_insert_or_update` with a composite key (`during` split)'
CALL set_test_composite.reset_target();
INSERT INTO set_test_composite.stat_for_unit (stat_definition_id, establishment_id, legal_unit_id, valid_after, valid_to, value, edit_comment) VALUES
(10, 100, NULL, '2024-01-01', '2024-12-31', 50, 'Original Value');

CREATE TEMP TABLE temp_source_update (
    row_id INT, stat_definition_id INT, establishment_id INT, legal_unit_id INT, valid_after DATE NOT NULL, valid_to DATE NOT NULL, value BIGINT, edit_comment TEXT
) ON COMMIT DROP;
-- Source has a NULL value for 'edit_comment'. In UPDATE mode, this should NOT overwrite the existing value.
INSERT INTO temp_source_update VALUES (1, 10, 100, NULL, '2024-04-01', '2024-08-31', 55, NULL);

\echo 'Calling orchestrator for UPDATE...'
SELECT source_row_id, target_entity_ids, status, error_message FROM import.set_insert_or_update_generic_valid_time_table(
    :'target_schema',
    :'target_table',
    :'source_schema',
    'temp_source_update',
    :'entity_id_cols'::TEXT[],
    NULL,
    :'ephemeral_cols'::TEXT[]
);
\echo 'Final state of target table (expected):'
SELECT * FROM (VALUES
    (10, 100, NULL::INT, '2024-01-01'::DATE, '2024-04-01'::DATE, 50::BIGINT, 'Original Value'::TEXT),
    (10, 100, NULL::INT, '2024-04-01'::DATE, '2024-08-31'::DATE, 55::BIGINT, 'Original Value'::TEXT),
    (10, 100, NULL::INT, '2024-08-31'::DATE, '2024-12-31'::DATE, 50::BIGINT, 'Original Value'::TEXT)
) AS t (stat_definition_id, establishment_id, legal_unit_id, valid_after, valid_to, value, edit_comment);
\echo 'Actual state of target table:'
SELECT stat_definition_id, establishment_id, legal_unit_id, valid_after, valid_to, value, edit_comment FROM set_test_composite.stat_for_unit WHERE stat_definition_id = 10 AND establishment_id = 100 ORDER BY valid_after;
DROP TABLE temp_source_update;


--------------------------------------------------------------------------------
-- Test `set_insert_or_replace` with a composite key and mismatched source columns
--------------------------------------------------------------------------------
\echo 'Test Case 3: `set_insert_or_replace` with mismatched source/target columns'
CALL set_test_composite.reset_target();
INSERT INTO set_test_composite.stat_for_unit (stat_definition_id, establishment_id, legal_unit_id, valid_after, valid_to, value, edit_comment) VALUES
(10, 100, NULL, '2024-01-01', '2024-12-31', 50, 'Original Value');

-- Source table has an extra column `source_metadata` that is not in the target.
-- The planner should ignore this column and only use common columns for the data payload.
CREATE TEMP TABLE temp_source_mismatched (
    row_id INT, stat_definition_id INT, establishment_id INT, legal_unit_id INT, valid_after DATE NOT NULL, valid_to DATE NOT NULL, value BIGINT, edit_comment TEXT, source_metadata TEXT
) ON COMMIT DROP;
INSERT INTO temp_source_mismatched VALUES (1, 10, 100, NULL, '2024-04-01', '2024-08-31', 55, 'Corrected value for mid-year', 'some extra data');

\echo 'Calling orchestrator with mismatched source...'
SELECT source_row_id, target_entity_ids, status, error_message FROM import.set_insert_or_replace_generic_valid_time_table(
    :'target_schema',
    :'target_table',
    :'source_schema',
    'temp_source_mismatched',
    :'entity_id_cols'::TEXT[],
    NULL,
    :'ephemeral_cols'::TEXT[]
);
\echo 'Final state of target table (expected):'
SELECT * FROM (VALUES
    (10, 100, NULL::INT, '2024-01-01'::DATE, '2024-04-01'::DATE, 50::BIGINT, 'Original Value'::TEXT),
    (10, 100, NULL::INT, '2024-04-01'::DATE, '2024-08-31'::DATE, 55::BIGINT, 'Corrected value for mid-year'::TEXT),
    (10, 100, NULL::INT, '2024-08-31'::DATE, '2024-12-31'::DATE, 50::BIGINT, 'Original Value'::TEXT)
) AS t (stat_definition_id, establishment_id, legal_unit_id, valid_after, valid_to, value, edit_comment);
\echo 'Actual state of target table:'
SELECT stat_definition_id, establishment_id, legal_unit_id, valid_after, valid_to, value, edit_comment FROM set_test_composite.stat_for_unit WHERE stat_definition_id = 10 AND establishment_id = 100 ORDER BY valid_after;
DROP TABLE temp_source_mismatched;


--------------------------------------------------------------------------------
-- Test `set_insert_or_replace` with a surrogate key that is not an entity key
--------------------------------------------------------------------------------
\echo 'Test Case 4: `set_insert_or_replace` with surrogate key on target'
CALL set_test_composite.reset_target();
-- Target table stat_for_unit_with_id has a surrogate PK `id` that should be auto-populated.
-- Source table does not have an `id` column.
CREATE TEMP TABLE temp_source_surrogate (
    row_id INT, stat_definition_id INT, establishment_id INT, valid_after DATE NOT NULL, valid_to DATE NOT NULL, value BIGINT, edit_comment TEXT
) ON COMMIT DROP;
INSERT INTO temp_source_surrogate VALUES (1, 10, 100, '2024-01-01', '2024-12-31', 100, 'Initial Value');

\echo 'Calling orchestrator for table with surrogate key...'
SELECT source_row_id, target_entity_ids, status, error_message FROM import.set_insert_or_replace_generic_valid_time_table(
    'set_test_composite',
    'stat_for_unit_with_id',
    :'source_schema',
    'temp_source_surrogate',
    '{stat_definition_id, establishment_id}'::TEXT[],
    NULL,
    :'ephemeral_cols'::TEXT[]
);
\echo 'Final state of target table (expected):'
SELECT * FROM (VALUES
    (1, 10, 100, '2024-01-01'::DATE, '2024-12-31'::DATE, 100::BIGINT, 'Initial Value'::TEXT)
) AS t (id, stat_definition_id, establishment_id, valid_after, valid_to, value, edit_comment);
\echo 'Actual state of target table:'
SELECT id, stat_definition_id, establishment_id, valid_after, valid_to, value, edit_comment FROM set_test_composite.stat_for_unit_with_id WHERE stat_definition_id = 10 AND establishment_id = 100 ORDER BY valid_after;
DROP TABLE temp_source_surrogate;


--------------------------------------------------------------------------------
-- Test `set_insert_or_replace` with a surrogate key using IDENTITY
--------------------------------------------------------------------------------
\echo 'Test Case 5: `set_insert_or_replace` with IDENTITY surrogate key on target'
CALL set_test_composite.reset_target();
-- Target table stat_for_unit_with_identity has a surrogate PK `id` that should be auto-populated.
-- Source table does not have an `id` column.
CREATE TEMP TABLE temp_source_identity (
    row_id INT, stat_definition_id INT, establishment_id INT, valid_after DATE NOT NULL, valid_to DATE NOT NULL, value BIGINT, edit_comment TEXT
) ON COMMIT DROP;
INSERT INTO temp_source_identity VALUES (1, 10, 100, '2024-01-01', '2024-12-31', 100, 'Initial Value');

\echo 'Calling orchestrator for table with IDENTITY surrogate key...'
SELECT source_row_id, target_entity_ids, status, error_message FROM import.set_insert_or_replace_generic_valid_time_table(
    'set_test_composite',
    'stat_for_unit_with_identity',
    :'source_schema',
    'temp_source_identity',
    '{stat_definition_id, establishment_id}'::TEXT[],
    NULL,
    :'ephemeral_cols'::TEXT[]
);
\echo 'Final state of target table (expected):'
SELECT * FROM (VALUES
    (1, 10, 100, '2024-01-01'::DATE, '2024-12-31'::DATE, 100::BIGINT, 'Initial Value'::TEXT)
) AS t (id, stat_definition_id, establishment_id, valid_after, valid_to, value, edit_comment);
\echo 'Actual state of target table:'
SELECT id, stat_definition_id, establishment_id, valid_after, valid_to, value, edit_comment FROM set_test_composite.stat_for_unit_with_identity WHERE stat_definition_id = 10 AND establishment_id = 100 ORDER BY valid_after;
DROP TABLE temp_source_identity;


\echo '--- Test Case 6 (UPDATE): `SERIAL` surrogate key on target table'
CALL set_test_composite.reset_target();
CREATE TEMP TABLE temp_source_stats_serial (
    row_id INT, stat_definition_id INT, establishment_id INT, valid_after DATE NOT NULL, valid_to DATE NOT NULL, value BIGINT, edit_comment TEXT
) ON COMMIT DROP;
INSERT INTO temp_source_stats_serial VALUES (104, 10, 100, '2023-12-31', '2024-12-31', 100, 'Initial stat');
\echo 'Calling orchestrator for table with surrogate key...'
SELECT source_row_id, target_entity_ids, status, error_message FROM import.set_insert_or_update_generic_valid_time_table('set_test_composite', 'stat_for_unit_with_id', 'pg_temp', 'temp_source_stats_serial', '{stat_definition_id, establishment_id}'::TEXT[], NULL, '{edit_comment}'::TEXT[]);
\echo 'Final state of target table (expected):'
SELECT * FROM (VALUES
    (1, 10, 100, '2023-12-31'::DATE, '2024-12-31'::DATE, 100::BIGINT, 'Initial stat'::TEXT)
) AS t (id, stat_definition_id, establishment_id, valid_after, valid_to, value, edit_comment);
\echo 'Actual state of target table:'
SELECT id, stat_definition_id, establishment_id, valid_after, valid_to, value, edit_comment FROM set_test_composite.stat_for_unit_with_id WHERE establishment_id = 100 and stat_definition_id = 10 ORDER BY valid_after;
DROP TABLE temp_source_stats_serial;

\echo '--- Test Case 7 (UPDATE): `IDENTITY` surrogate key on target table'
CALL set_test_composite.reset_target();
CREATE TEMP TABLE temp_source_stats_identity (
    row_id INT, stat_definition_id INT, establishment_id INT, valid_after DATE NOT NULL, valid_to DATE NOT NULL, value BIGINT, edit_comment TEXT
) ON COMMIT DROP;
INSERT INTO temp_source_stats_identity VALUES (105, 10, 100, '2023-12-31', '2024-12-31', 100, 'Initial stat');
\echo 'Calling orchestrator for table with IDENTITY surrogate key...'
SELECT source_row_id, target_entity_ids, status, error_message FROM import.set_insert_or_update_generic_valid_time_table('set_test_composite', 'stat_for_unit_with_identity', 'pg_temp', 'temp_source_stats_identity', '{stat_definition_id, establishment_id}'::TEXT[], NULL, '{edit_comment}'::TEXT[]);
\echo 'Final state of target table (expected):'
SELECT * FROM (VALUES
    (1, 10, 100, '2023-12-31'::DATE, '2024-12-31'::DATE, 100::BIGINT, 'Initial stat'::TEXT)
) AS t (id, stat_definition_id, establishment_id, valid_after, valid_to, value, edit_comment);
\echo 'Actual state of target table:'
SELECT id, stat_definition_id, establishment_id, valid_after, valid_to, value, edit_comment FROM set_test_composite.stat_for_unit_with_identity WHERE establishment_id = 100 and stat_definition_id = 10 ORDER BY valid_after;
DROP TABLE temp_source_stats_identity;


\echo '--- Test Case 8 (REPLACE): Table with non-PK surrogate key (mimics stat_for_unit)'
CALL set_test_composite.reset_target();
CREATE TEMP TABLE temp_source_no_pk (
    row_id INT, stat_definition_id INT, establishment_id INT, valid_after DATE NOT NULL, valid_to DATE NOT NULL, value BIGINT, edit_comment TEXT
) ON COMMIT DROP;
INSERT INTO temp_source_no_pk VALUES (1, 10, 100, '2024-01-01', '2024-12-31', 100, 'Initial Value');

\echo 'Calling orchestrator for table with non-PK surrogate key...'
SELECT source_row_id, target_entity_ids, status, error_message FROM import.set_insert_or_replace_generic_valid_time_table(
    p_target_schema_name => 'set_test_composite',
    p_target_table_name => 'stat_for_unit_no_pk',
    p_source_schema_name => :'source_schema',
    p_source_table_name => 'temp_source_no_pk',
    p_entity_id_column_names => '{stat_definition_id, establishment_id}'::TEXT[],
    p_source_row_ids => NULL,
    p_ephemeral_columns => :'ephemeral_cols'::TEXT[],
    p_insert_defaulted_columns => ARRAY['id']
);
\echo 'Final state of target table (expected):'
SELECT * FROM (VALUES
    (1, 10, 100, '2024-01-01'::DATE, '2024-12-31'::DATE, 100::BIGINT, 'Initial Value'::TEXT)
) AS t (id, stat_definition_id, establishment_id, valid_after, valid_to, value, edit_comment);
\echo 'Actual state of target table:'
SELECT id, stat_definition_id, establishment_id, valid_after, valid_to, value, edit_comment FROM set_test_composite.stat_for_unit_no_pk WHERE stat_definition_id = 10 AND establishment_id = 100 ORDER BY valid_after;
DROP TABLE temp_source_no_pk;

-- Cleanup
DROP PROCEDURE set_test_composite.reset_target();
DROP TABLE set_test_composite.stat_for_unit;
DROP TABLE set_test_composite.stat_for_unit_with_id;
DROP TABLE set_test_composite.stat_for_unit_with_identity;
DROP TABLE set_test_composite.stat_for_unit_no_pk;
DROP TABLE set_test_composite.establishment;
DROP TABLE set_test_composite.legal_unit;
DROP TABLE set_test_composite.stat_definition;
DROP SCHEMA set_test_composite CASCADE;

SET client_min_messages TO NOTICE;
ROLLBACK;
