--
-- Test 403: Cross-border power group renders its foreign (UTLA) members
--
-- STATBUS-121 NORTH STAR: a cross-border power group renders fully.
--
-- Real Norwegian konsern data (Aker Solutions ASA, org 913748174) contains many
-- "Utenlandsk enhet" (UTLA = foreign) members. A foreign member is representable
-- ONLY as an ordinary legal_unit row: both legal_relationship endpoints
-- (influencing_id, influenced_id) are hard temporal FKs to legal_unit, with no
-- external-party escape hatch. legal_unit has no country flag of its own; country
-- lives in location.country_id and surfaces as statistical_unit.physical_country_iso_2.
--
-- The legal_relationship import step (import.analyse_legal_relationship) does NOT
-- materialize endpoints -- it only RESOLVES them (external_ident -> legal_unit).
-- An endpoint tax_ident with no existing legal_unit is flagged unknown_influencing
-- / unknown_influenced -> state='error', action='skip'. That is correct tier-1
-- validation: the relationship step legitimately cannot invent a legal_unit.
--
-- So the foreign members must be materialized FIRST, via the ordinary hovedenhet
-- (enheter) import, which maps forretningsadresse.landkode -> physical_country_iso_2.
-- A UTLA enhet record carries its foreign country there (e.g. AKER SOLUTIONS KOREA
-- -> "KR"). This test loads the real Aker konsern (23 members, 14 foreign across 9
-- countries) through the SAME pipeline as samples/norway/brreg/brreg-import-selection.sh
-- and asserts the foreign members render as legal_units with physical_country_iso_2
-- != 'NO' (domestic=false), inside the konsern power group.
--
-- Fixtures (generated by samples/norway/brreg/fetch-konsern-fixture.py, committed):
--   samples/norway/legal_unit/konsern-enheter.csv        (23 members, hovedenhet format)
--   samples/norway/legal_relationship/konsern-roller.csv  (22 HFOR edges, roller format)
--

-- ============================================================================
-- PHASE 0: SETUP
-- ============================================================================
-- Note: No reset needed - 4xx tests run in isolated databases from template
\echo 'Pausing background worker for test duration'
SELECT worker.pause('1 hour'::interval);

-- ============================================================================
-- PHASE 1: SETUP (in transaction so setup.sql helpers work)
-- ============================================================================
BEGIN;

\i test/setup.sql

-- Suppress the verbatim echo/output of the shared setup includes. Their content
-- is not what this test asserts, and echoing it makes the expected file both
-- churn-prone (any edit to getting-started.sql / the definitions would break it)
-- and flaky (the `\i` echo has been observed to intermittently drop under the
-- harness). Only this test's own queries below contribute to the expected output.
\echo "Setting up Statbus (Norway) and BRREG import definitions (output suppressed)"
\o /dev/null
\set ECHO none
\i samples/norway/getting-started.sql
\i samples/norway/brreg/create-import-definition-hovedenhet-2024.sql
\i samples/norway/brreg/seed-legal-rel-types.sql
\i samples/norway/brreg/create-import-definition-roller-2025.sql
\o
\set ECHO all

\echo "Switch to test admin user"
CALL test.set_user_from_email('test.admin@statbus.org');

\echo "Verify import definitions exist and are valid"
SELECT slug, mode, valid
  FROM public.import_definition
 WHERE slug IN ('brreg_hovedenhet_2024','brreg_roller_2025')
 ORDER BY slug;

-- ============================================================================
-- Create import jobs - LU (konsern members) FIRST, then relationships.
-- Upload order = processing priority; the roller step resolves tax_idents to
-- legal_units, so the LU job must complete before the roller job is analysed.
-- ============================================================================
\echo "Create import job for konsern legal units (hovedenhet) - uploaded FIRST"
WITH def AS (SELECT id FROM public.import_definition WHERE slug = 'brreg_hovedenhet_2024')
INSERT INTO public.import_job (definition_id, slug, default_valid_from, default_valid_to, description, note, user_id, review)
SELECT def.id, 'import_403_konsern_lu', '2025-01-01'::date, 'infinity'::date,
       'Test 403: Aker konsern legal units', 'Cross-border power group members',
       (SELECT id FROM public.user WHERE email = 'test.admin@statbus.org'), false
FROM def
ON CONFLICT (slug) DO NOTHING
RETURNING slug, state;

\echo "Load konsern legal-unit data FIRST"
\copy public.import_403_konsern_lu_upload FROM 'samples/norway/legal_unit/konsern-enheter.csv' WITH CSV HEADER

\echo "Create import job for konsern relationships (roller) - uploaded SECOND"
WITH def AS (SELECT id FROM public.import_definition WHERE slug = 'brreg_roller_2025')
INSERT INTO public.import_job (definition_id, slug, default_valid_from, default_valid_to, description, note, user_id, review)
SELECT def.id, 'import_403_konsern_rel', '2025-01-01'::date, 'infinity'::date,
       'Test 403: Aker konsern relationships', 'Cross-border ownership edges',
       (SELECT id FROM public.user WHERE email = 'test.admin@statbus.org'), false
FROM def
ON CONFLICT (slug) DO NOTHING
RETURNING slug, state;

\echo "Load konsern relationship data SECOND (lower priority than LU)"
\copy public.import_403_konsern_rel_upload FROM 'samples/norway/legal_relationship/konsern-roller.csv' WITH CSV HEADER

COMMIT;

-- ============================================================================
-- PHASE 2: PROCESSING (outside transaction - worker commits per task)
-- ============================================================================
\echo "Processing import jobs (LU first due to upload order, then relationships)"
CALL worker.process_tasks(p_queue => 'import');

\echo "Deriving analytics (statistical_unit country surfacing)"
CALL worker.process_tasks(p_queue => 'analytics');
CALL worker.process_tasks();

-- ============================================================================
-- PHASE 3: VERIFICATION
-- ============================================================================
BEGIN;

\echo 'Import job states (both must be completed, no errors)'
SELECT slug, state, error IS NOT NULL AS failed, total_rows, imported_rows
  FROM public.import_job
 WHERE slug LIKE 'import_403_%'
 ORDER BY slug;

\echo 'Import data row states (all rows should be non-error)'
SELECT 'lu' AS job, state, count(*) FROM public.import_403_konsern_lu_data GROUP BY state ORDER BY state;
SELECT 'rel' AS job, state, count(*) FROM public.import_403_konsern_rel_data GROUP BY state ORDER BY state;

\echo 'Any error rows (should be none)'
SELECT row_id, errors FROM public.import_403_konsern_lu_data WHERE state = 'error' ORDER BY row_id LIMIT 10;
SELECT row_id, errors FROM public.import_403_konsern_rel_data WHERE state = 'error' ORDER BY row_id LIMIT 10;

\echo '=== AC#1/AC#2: all 23 konsern members materialized as legal_units ==='
SELECT count(*) AS konsern_legal_units
FROM public.legal_unit AS lu
JOIN public.external_ident AS ei ON ei.legal_unit_id = lu.id
JOIN public.external_ident_type AS eit ON eit.id = ei.type_id AND eit.code = 'tax_ident'
WHERE ei.ident IN (
  '893821872','913192192','913748174','914634377','914635233','914635888','914636191',
  '920882749','920882803','924801026','929196732','929196899','929877950','933627209',
  '934060199','987903066','991374329','996864359','997822986','997822994','997839145',
  '997839161','999151477'
);

\echo '=== AC#3: foreign (UTLA) members render with physical_country_iso_2 != NO, domestic=false ==='
SELECT
    su.external_idents->>'tax_ident' AS tax_ident,
    su.name,
    su.physical_country_iso_2,
    su.domestic
FROM public.statistical_unit AS su
WHERE su.unit_type = 'legal_unit'
  AND su.external_idents->>'tax_ident' IN (
    '893821872','914634377','914635233','914635888','914636191',
    '920882749','920882803','929196732','929196899',
    '997822986','997822994','997839145','997839161','999151477'
  )
ORDER BY su.physical_country_iso_2, tax_ident;

\echo '=== Cross-border summary: member count by country, domestic flag ==='
SELECT
    su.physical_country_iso_2,
    su.domestic,
    count(*) AS members
FROM public.statistical_unit AS su
WHERE su.unit_type = 'legal_unit'
  AND su.external_idents->>'tax_ident' IN (
    '893821872','913192192','913748174','914634377','914635233','914635888','914636191',
    '920882749','920882803','924801026','929196732','929196899','929877950','933627209',
    '934060199','987903066','991374329','996864359','997822986','997822994','997839145',
    '997839161','999151477'
  )
GROUP BY su.physical_country_iso_2, su.domestic
ORDER BY su.domestic DESC, su.physical_country_iso_2;

\echo '=== The konsern power group spans domestic + foreign members ==='
SELECT
    pg.ident AS power_group_ident,
    count(*) AS total_members,
    count(*) FILTER (WHERE su.domestic) AS domestic_members,
    count(*) FILTER (WHERE NOT su.domestic) AS foreign_members
FROM public.power_group_membership AS pgm
JOIN public.power_group AS pg ON pg.id = pgm.power_group_id
JOIN public.statistical_unit AS su ON su.unit_type = 'legal_unit' AND su.unit_id = pgm.legal_unit_id
GROUP BY pg.ident
ORDER BY pg.ident;

COMMIT;

-- ============================================================================
-- PHASE 4: CLEANUP
-- ============================================================================
\echo 'Resuming background worker'
SELECT worker.resume();

\i test/cleanup_unless_persist_is_specified.sql
