package cmd

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	"github.com/statisticsnorway/statbus/cli/internal/migrate"
)

// STATBUS-481: generated artifacts must not depend on how the database was
// built. app/src/lib/database.types.ts is generated by `./sb types generate`
// from a MIGRATED seed, but CI and every installed box run on a RESTORED one,
// and pg_restore assigns OIDs in dump order rather than migration order. The
// generator ordered function overloads by OID, so after STATBUS-460 (the first
// overloads taking different table row types) a restored seed generated a
// different file and test 016 failed in CI only.
//
// seedRestoredTypesCheck closes that class: the seed build already holds a
// RESTORED copy of the seed (round trip 1), so it generates the types from it
// with the very generator `./sb types generate` uses and requires them to equal
// the committed file. Skipped (loudly) when the build context does not carry
// the generator and the committed file, as in the hermetic image build, where
// test 016 on the restored CI seed remains the check.
func seedRestoredTypesCheck(projDir, restoredDb string) error {
	generator := filepath.Join(projDir, "cli", "sql", "generate_database_types.sql")
	committedPath := filepath.Join(projDir, "app", "src", "lib", "database.types.ts")
	committed, errCommitted := os.ReadFile(committedPath)
	sqlFile, errGenerator := os.Open(generator)
	if errCommitted != nil || errGenerator != nil {
		if sqlFile != nil {
			_ = sqlFile.Close()
		}
		fmt.Printf("seed round trip (STATBUS-481): restored-seed types check SKIPPED (no %s or %s in this build context)\n",
			"cli/sql/generate_database_types.sql", "app/src/lib/database.types.ts")
		return nil
	}
	defer func() { _ = sqlFile.Close() }()

	psqlPath, prefix, env, err := migrate.PsqlCommand(projDir)
	if err != nil {
		return err
	}
	// An empty output_path makes the generator's `\o` write to stdout.
	args := append(append([]string(nil), prefix...), "-X", "-q", "-d", restoredDb, "-v", "output_path=")
	c, err := migrate.Command(projDir, psqlPath, args...)
	if err != nil {
		return fmt.Errorf("construct restored-seed type generation: %w", err)
	}
	var out, stderr bytes.Buffer
	c.Env = env
	c.Stdin = sqlFile
	c.Stdout = &out
	c.Stderr = &stderr
	if err := c.Run(); err != nil {
		return fmt.Errorf("generate types from restored seed %s: %w\n%s", restoredDb, err, stderr.String())
	}
	if !bytes.Equal(out.Bytes(), committed) {
		diffPath := filepath.Join(projDir, ".db-seed", "restored-seed.database.types.ts")
		_ = os.WriteFile(diffPath, out.Bytes(), 0644)
		return fmt.Errorf("seed round trip FAILED: types generated from the RESTORED seed (%d bytes, written to %s) differ from the committed app/src/lib/database.types.ts (%d bytes): the generator's output depends on how the database was built, or the committed file is stale",
			out.Len(), diffPath, len(committed))
	}
	fmt.Println("seed round trip (STATBUS-481): types generated from the restored seed equal the committed database.types.ts")
	return nil
}
