namespace nscreg.Utilities
{
    public class CommonSettings
    {
        public string ConnectionString { get; set; }
        public bool UseInMemoryDataBase { get; set; }
        public int StatUnitAnalysisServiceDequeueInterval { get; set; }
        public int DataUploadServiceDequeueInterval { get; set; }
        public int DataUploadServiceCleanupTimeout { get; set; }
        public string[] Localizations { get; set; }
        public string DefaultLocalization { get; set; }
        public bool AddressesAddressId {get;set;}
        public bool AddressesAddressPart1 {get;set;}
        public bool AddressesAddressPart2 {get;set;}
        public bool AddressesAddressPart3 {get;set;}
        public bool AddressesGeographicalCodes {get;set;}
        public bool AddressesGpsCoordinates {get;set;}
        public bool StatUnitRegId {get;set;}
        public bool StatUnitRegIdDate {get;set;}
        public bool StatUnitStatId {get;set;}
        public bool StatUnitStatIdDate {get;set;}
        public bool StatUnitTaxRegId {get;set;}
        public bool StatUnitTaxRegDate {get;set;}
        public bool StatUnitExternalId {get;set;}
        public bool StatUnitExternalIdType {get;set;}
        public bool StatUnitExternalIdDate {get;set;}
        public bool StatUnitDataSource {get;set;}
        public bool StatUnitRefNo {get;set;}
        public bool StatUnitName {get;set;}
        public bool StatUnitShortName {get;set;}
        public bool StatUnitAddressId {get;set;}
        public bool StatUnitPostalAddressId {get;set;}
        public bool StatUnitTelephoneNo {get;set;}
        public bool StatUnitEmailAddress {get;set;}
        public bool StatUnitWebAddress {get;set;}
        public bool StatUnitRegMainActivity {get;set;}
        public bool StatUnitRegistrationDate {get;set;}
        public bool StatUnitRegistrationReason {get;set;}
        public bool StatUnitLiqDate {get;set;}
        public bool StatUnitLiqReason {get;set;}
        public bool StatUnitSuspensionStart {get;set;}
        public bool StatUnitSuspensionEnd {get;set;}
        public bool StatUnitReorgTypeCode {get;set;}
        public bool StatUnitReorgDate {get;set;}
        public bool StatUnitReorgReferences {get;set;}
        public bool StatUnitActualAddressId {get;set;}
        public bool StatUnitContactPerson {get;set;}
        public bool StatUnitEmployees {get;set;}
        public bool StatUnitNumOfPeopleEmp {get;set;}
        public bool StatUnitEmployeesYear {get;set;}
        public bool StatUnitEmployeesDate {get;set;}
        public bool StatUnitTurnover {get;set;}
        public bool StatUnitTurnoverYear {get;set;}
        public bool StatUnitTurnoverDate {get;set;}
        public bool StatUnitStatus {get;set;}
        public bool StatUnitStatusDate {get;set;}
        public bool StatUnitNotes {get;set;}
        public bool StatUnitFreeEconZone {get;set;}
        public bool StatUnitForeignParticipation {get;set;}
        public bool StatUnitClassified {get;set;}
        public bool StatUnitForeignParticipationCountry {get;set;}
        public bool StatUnitOrgLink {get;set;}
        public bool LegalUnitEnterpriseRegId {get;set;}
        public bool LegalUnitEnterpriseRegIdDate {get;set;}
        public bool LegalUnitFounders {get;set;}
        public bool LegalUnitOwner {get;set;}
        public bool LegalUnitMarket {get;set;}
        public bool LegalUnitLegalForm {get;set;}
        public bool LegalUnitInstSectorCode {get;set;}
        public bool LegalUnitTotalCapital {get;set;}
        public bool LegalUnitMunCapitalShare {get;set;}
        public bool LegalUnitStateCapitalShare {get;set;}
        public bool LegalUnitPrivCapitalShare {get;set;}
        public bool LegalUnitForeignCapitalShare {get;set;}
        public bool LegalUnitForeignCapitalCurrency {get;set;}
        public bool EnterpriseEnterpriseGroupId {get;set;}
        public bool EnterpriseEnterpriseGroupIdDate {get;set;}
        public bool EnterpriseCommercial {get;set;}
        public bool EnterpriseInstSectorCode {get;set;}
        public bool EnterpriseTotalCapital {get;set;}
        public bool EnterpriseMunCapitalShare {get;set;}
        public bool EnterpriseStateCapitalShare {get;set;}
        public bool EnterprisePrivCapitalShare {get;set;}
        public bool EnterpriseForeignCapitalShare {get;set;}
        public bool EnterpriseForeignCapitalCurrency {get;set;}
        public bool EnterpriseActualMainActivityDate {get;set;}
        public bool EnterpriseEnterpriseGroupRole {get;set;}
        public bool LocalUnitLegalUnitId {get;set;}
        public bool LocalUnitLegalUnitIdDate {get;set;}
        public bool EnterpriseGroupRegId {get;set;}
        public bool EnterpriseGroupRegIdDate {get;set;}
        public bool EnterpriseGroupStatId {get;set;}
        public bool EnterpriseGroupStatIdDate {get;set;}
        public bool EnterpriseGroupTaxRegId {get;set;}
        public bool EnterpriseGroupTaxRegDate {get;set;}
        public bool EnterpriseGroupExternalId {get;set;}
        public bool EnterpriseGroupExternalIdType {get;set;}
        public bool EnterpriseGroupExternalIdDate {get;set;}
        public bool EnterpriseGroupDataSource {get;set;}
        public bool EnterpriseGroupName {get;set;}
        public bool EnterpriseGroupShortName {get;set;}
        public bool EnterpriseGroupAddressId {get;set;}
        public bool EnterpriseGroupPostalAddressId {get;set;}
        public bool EnterpriseGroupTelephoneNo {get;set;}
        public bool EnterpriseGroupEmailAddress {get;set;}
        public bool EnterpriseGroupWebAddress {get;set;}
        public bool EnterpriseGroupEnterpriseGroupType {get;set;}
        public bool EnterpriseGroupRegistrationDate {get;set;}
        public bool EnterpriseGroupRegistrationReason {get;set;}
        public bool EnterpriseGroupLiqDateStart {get;set;}
        public bool EnterpriseGroupLiqDateEnd {get;set;}
        public bool EnterpriseGroupLiqDateReason {get;set;}
        public bool EnterpriseGroupSuspensionStart {get;set;}
        public bool EnterpriseGroupSuspensionEnd {get;set;}
        public bool EnterpriseGroupReorgTypeCode {get;set;}
        public bool EnterpriseGroupReorgDate {get;set;}
        public bool EnterpriseGroupReorgReferences {get;set;}
        public bool EnterpriseGroupActualAddressId {get;set;}
        public bool EnterpriseGroupContactPerson {get;set;}
        public bool EnterpriseGroupEmployees {get;set;}
        public bool EnterpriseGroupNumOfPeopleEmp {get;set;}
        public bool EnterpriseGroupEmployeesYear {get;set;}
        public bool EnterpriseGroupEmployeesDate {get;set;}
        public bool EnterpriseGroupTurnover {get;set;}
        public bool EnterpriseGroupTurnoverYear {get;set;}
        public bool EnterpriseGroupTurnoverDate {get;set;}
        public bool EnterpriseGroupStatus {get;set;}
        public bool EnterpriseGroupStatusDate {get;set;}
        public bool EnterpriseGroupNotes {get;set;}
        public bool PersonId {get;set;}
        public bool PersonIdDate {get;set;}
        public bool PersonPersonalId {get;set;}
        public bool PersonUnitId {get;set;}
        public bool PersonGivenName {get;set;}
        public bool PersonSurname {get;set;}
        public bool PersonBirthDate {get;set;}
        public bool PersonSex {get;set;}
        public bool PersonRole {get;set;}
        public bool PersonNationalityCode {get;set;}
        public bool PersonTelephone1 {get;set;}
        public bool PersonTelephone2 {get;set;}
        public bool PersonAddress {get;set;}
        public bool ActivityActivityId {get;set;}
        public bool ActivityActivityIdDate {get;set;}
        public bool ActivityActivityUnitId {get;set;}
        public bool ActivityActivityRevx {get;set;}
        public bool ActivityActivityRevy {get;set;}
        public bool ActivityActivityYear {get;set;}
        public bool ActivityActivityType {get;set;}
        public bool ActivityEmployees {get;set;}
        public bool ActivityTurnover {get;set;}
        public bool ActivityUpdatedBy {get;set;}
        public bool ActivityUpdatedDate {get;set;}
    }
}