// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nscreg.Data;

namespace nscreg.Data.Migrations
{
    [DbContext(typeof(NSCRegDbContext))]
    [Migration("20200521064141_CreateEntGroupTypeTable")]
    partial class CreateEntGroupTypeTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("nscreg.Data.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivityCategoryId")
                        .HasColumnName("ActivityCategoryId");

                    b.Property<int>("ActivityType")
                        .HasColumnName("Activity_Type");

                    b.Property<int>("ActivityYear")
                        .HasColumnName("Activity_Year");

                    b.Property<int?>("Employees")
                        .HasColumnName("Employees");

                    b.Property<DateTime>("IdDate")
                        .HasColumnName("Id_Date");

                    b.Property<decimal?>("Turnover")
                        .HasColumnName("Turnover");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnName("Updated_By");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnName("Updated_Date");

                    b.HasKey("Id");

                    b.HasIndex("ActivityCategoryId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("nscreg.Data.Entities.ActivityCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ActivityCategoryLevel");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int?>("DicParentId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("NameLanguage1");

                    b.Property<string>("NameLanguage2");

                    b.Property<int?>("ParentId");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int>("VersionId");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ActivityCategories");
                });

            modelBuilder.Entity("nscreg.Data.Entities.ActivityCategoryUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnName("User_Id");

                    b.Property<int>("ActivityCategoryId")
                        .HasColumnName("ActivityCategory_Id");

                    b.HasKey("UserId", "ActivityCategoryId");

                    b.HasIndex("ActivityCategoryId");

                    b.ToTable("ActivityCategoryUsers");
                });

            modelBuilder.Entity("nscreg.Data.Entities.ActivityStatisticalUnit", b =>
                {
                    b.Property<int>("UnitId")
                        .HasColumnName("Unit_Id");

                    b.Property<int>("ActivityId")
                        .HasColumnName("Activity_Id");

                    b.HasKey("UnitId", "ActivityId");

                    b.HasIndex("ActivityId");

                    b.ToTable("ActivityStatisticalUnits");
                });

            modelBuilder.Entity("nscreg.Data.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Address_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressPart1")
                        .HasColumnName("Address_part1");

                    b.Property<string>("AddressPart2")
                        .HasColumnName("Address_part2");

                    b.Property<string>("AddressPart3")
                        .HasColumnName("Address_part3");

                    b.Property<double?>("Latitude")
                        .HasColumnName("Latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnName("Longitude");

                    b.Property<int>("RegionId")
                        .HasColumnName("Region_id");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("AddressPart1", "AddressPart2", "AddressPart3", "RegionId", "Latitude", "Longitude");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("nscreg.Data.Entities.AnalysisLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnalysisQueueId");

                    b.Property<int>("AnalyzedUnitId");

                    b.Property<int>("AnalyzedUnitType");

                    b.Property<string>("ErrorValues");

                    b.Property<DateTime>("IssuedAt");

                    b.Property<DateTime?>("ResolvedAt");

                    b.Property<string>("SummaryMessages");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisQueueId");

                    b.ToTable("AnalysisLogs");
                });

            modelBuilder.Entity("nscreg.Data.Entities.AnalysisQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<DateTime?>("ServerEndPeriod");

                    b.Property<DateTime?>("ServerStartPeriod");

                    b.Property<DateTime>("UserEndPeriod");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.Property<DateTime>("UserStartPeriod");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AnalysisQueues");
                });

            modelBuilder.Entity("nscreg.Data.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("IsoCode");

                    b.Property<string>("Name");

                    b.Property<string>("NameLanguage1");

                    b.Property<string>("NameLanguage2");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("nscreg.Data.Entities.CountryStatisticalUnit", b =>
                {
                    b.Property<int>("UnitId")
                        .HasColumnName("Unit_Id");

                    b.Property<int>("CountryId")
                        .HasColumnName("Country_Id");

                    b.HasKey("UnitId", "CountryId");

                    b.HasIndex("CountryId");

                    b.ToTable("CountryStatisticalUnits");
                });

            modelBuilder.Entity("nscreg.Data.Entities.CustomAnalysisCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(64);

                    b.Property<string>("Query")
                        .HasMaxLength(2048);

                    b.Property<string>("TargetUnitTypes")
                        .HasMaxLength(16);

                    b.HasKey("Id");

                    b.ToTable("CustomAnalysisChecks");
                });

            modelBuilder.Entity("nscreg.Data.Entities.DataSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AllowedOperations");

                    b.Property<string>("AttributesToCheck");

                    b.Property<string>("CsvDelimiter");

                    b.Property<int>("CsvSkipCount");

                    b.Property<int>("DataSourceUploadType");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Priority");

                    b.Property<string>("Restrictions");

                    b.Property<int>("StatUnitType");

                    b.Property<string>("UserId");

                    b.Property<string>("VariablesMapping");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("DataSourceUploads");
                });

            modelBuilder.Entity("nscreg.Data.Entities.DataSourceClassification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<string>("NameLanguage1");

                    b.Property<string>("NameLanguage2");

                    b.HasKey("Id");

                    b.ToTable("DataSourceClassifications");
                });

            modelBuilder.Entity("nscreg.Data.Entities.DataSourceQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DataSourceFileName")
                        .IsRequired();

                    b.Property<int>("DataSourceId");

                    b.Property<string>("DataSourcePath")
                        .IsRequired();

                    b.Property<string>("Description");

                    b.Property<DateTime?>("EndImportDate");

                    b.Property<string>("Note");

                    b.Property<DateTime?>("StartImportDate");

                    b.Property<int>("Status");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("UserId");

                    b.ToTable("DataSourceQueues");
                });

            modelBuilder.Entity("nscreg.Data.Entities.DataUploadingLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DataSourceQueueId");

                    b.Property<DateTime?>("EndImportDate");

                    b.Property<string>("Errors");

                    b.Property<string>("Note");

                    b.Property<string>("SerializedRawUnit");

                    b.Property<string>("SerializedUnit");

                    b.Property<DateTime?>("StartImportDate");

                    b.Property<string>("StatUnitName");

                    b.Property<int>("Status");

                    b.Property<string>("Summary");

                    b.Property<string>("TargetStatId");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceQueueId");

                    b.ToTable("DataUploadingLogs");
                });

            modelBuilder.Entity("nscreg.Data.Entities.DictionaryVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("VersionId");

                    b.Property<string>("VersionName");

                    b.HasKey("Id");

                    b.HasIndex("VersionId", "VersionName")
                        .IsUnique()
                        .HasFilter("[VersionName] IS NOT NULL");

                    b.ToTable("DictionaryVersions");
                });

            modelBuilder.Entity("nscreg.Data.Entities.EnterpriseGroup", b =>
                {
                    b.Property<int>("RegId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ActualAddressId");

                    b.Property<int?>("AddressId");

                    b.Property<int>("ChangeReason")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("ContactPerson");

                    b.Property<string>("DataSource");

                    b.Property<int?>("DataSourceClassificationId");

                    b.Property<string>("EditComment");

                    b.Property<string>("EmailAddress");

                    b.Property<int?>("Employees");

                    b.Property<DateTime?>("EmployeesDate");

                    b.Property<int?>("EmployeesYear");

                    b.Property<DateTime>("EndPeriod");

                    b.Property<int?>("EntGroupTypeId");

                    b.Property<string>("ExternalId");

                    b.Property<DateTime?>("ExternalIdDate");

                    b.Property<string>("ExternalIdType");

                    b.Property<string>("HistoryEnterpriseUnitIds");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LiqDateEnd");

                    b.Property<DateTime?>("LiqDateStart");

                    b.Property<string>("LiqReason");

                    b.Property<string>("Name")
                        .HasMaxLength(400);

                    b.Property<string>("Notes");

                    b.Property<int?>("NumOfPeopleEmp");

                    b.Property<int?>("PostalAddressId");

                    b.Property<DateTime>("RegIdDate");

                    b.Property<DateTime>("RegistrationDate");

                    b.Property<int?>("RegistrationReasonId");

                    b.Property<DateTime?>("ReorgDate");

                    b.Property<string>("ReorgReferences");

                    b.Property<string>("ReorgTypeCode");

                    b.Property<int?>("ReorgTypeId");

                    b.Property<string>("ShortName");

                    b.Property<int?>("SizeId");

                    b.Property<DateTime>("StartPeriod");

                    b.Property<string>("StatId");

                    b.Property<DateTime?>("StatIdDate");

                    b.Property<DateTime>("StatusDate");

                    b.Property<string>("SuspensionEnd");

                    b.Property<string>("SuspensionStart");

                    b.Property<DateTime?>("TaxRegDate");

                    b.Property<string>("TaxRegId");

                    b.Property<string>("TelephoneNo");

                    b.Property<decimal?>("Turnover");

                    b.Property<DateTime?>("TurnoverDate");

                    b.Property<int?>("TurnoverYear");

                    b.Property<int?>("UnitStatusId");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.Property<string>("WebAddress");

                    b.HasKey("RegId");

                    b.HasIndex("ActualAddressId");

                    b.HasIndex("AddressId");

                    b.HasIndex("DataSourceClassificationId");

                    b.HasIndex("EntGroupTypeId");

                    b.HasIndex("Name");

                    b.HasIndex("PostalAddressId");

                    b.HasIndex("RegistrationReasonId");

                    b.HasIndex("ReorgTypeId");

                    b.HasIndex("SizeId");

                    b.HasIndex("StartPeriod");

                    b.HasIndex("UnitStatusId");

                    b.ToTable("EnterpriseGroups");
                });

            modelBuilder.Entity("nscreg.Data.Entities.EnterpriseGroupType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<string>("NameLanguage1");

                    b.Property<string>("NameLanguage2");

                    b.HasKey("Id");

                    b.ToTable("EnterpriseGroupTypes");
                });

            modelBuilder.Entity("nscreg.Data.Entities.ForeignParticipation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<string>("NameLanguage1");

                    b.Property<string>("NameLanguage2");

                    b.HasKey("Id");

                    b.ToTable("ForeignParticipations");
                });

            modelBuilder.Entity("nscreg.Data.Entities.History.ActivityStatisticalUnitHistory", b =>
                {
                    b.Property<int>("UnitId")
                        .HasColumnName("Unit_Id");

                    b.Property<int>("ActivityId")
                        .HasColumnName("Activity_Id");

                    b.HasKey("UnitId", "ActivityId");

                    b.HasIndex("ActivityId");

                    b.ToTable("ActivityStatisticalUnitHistory");
                });

            modelBuilder.Entity("nscreg.Data.Entities.History.CountryStatisticalUnitHistory", b =>
                {
                    b.Property<int>("UnitId")
                        .HasColumnName("Unit_Id");

                    b.Property<int>("CountryId")
                        .HasColumnName("Country_Id");

                    b.HasKey("UnitId", "CountryId");

                    b.HasIndex("CountryId");

                    b.ToTable("CountryStatisticalUnitHistory");
                });

            modelBuilder.Entity("nscreg.Data.Entities.History.EnterpriseGroupHistory", b =>
                {
                    b.Property<int>("RegId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ActualAddressId");

                    b.Property<int?>("AddressId");

                    b.Property<int>("ChangeReason")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("ContactPerson");

                    b.Property<string>("DataSource");

                    b.Property<int?>("DataSourceClassificationId");

                    b.Property<string>("EditComment");

                    b.Property<string>("EmailAddress");

                    b.Property<int?>("Employees");

                    b.Property<DateTime?>("EmployeesDate");

                    b.Property<int?>("EmployeesYear");

                    b.Property<DateTime>("EndPeriod");

                    b.Property<string>("EntGroupType");

                    b.Property<string>("ExternalId");

                    b.Property<DateTime?>("ExternalIdDate");

                    b.Property<string>("ExternalIdType");

                    b.Property<string>("HistoryEnterpriseUnitIds");

                    b.Property<int?>("InstSectorCodeId");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("LegalFormId");

                    b.Property<DateTime?>("LiqDateEnd");

                    b.Property<DateTime?>("LiqDateStart");

                    b.Property<string>("LiqReason");

                    b.Property<string>("Name")
                        .HasMaxLength(400);

                    b.Property<string>("Notes");

                    b.Property<int?>("NumOfPeopleEmp");

                    b.Property<int?>("ParentId");

                    b.Property<int?>("PostalAddressId");

                    b.Property<DateTime>("RegIdDate");

                    b.Property<int?>("RegMainActivityId");

                    b.Property<DateTime>("RegistrationDate");

                    b.Property<int?>("RegistrationReasonId");

                    b.Property<DateTime?>("ReorgDate");

                    b.Property<string>("ReorgReferences");

                    b.Property<string>("ReorgTypeCode");

                    b.Property<int?>("ReorgTypeId");

                    b.Property<string>("ShortName");

                    b.Property<int?>("SizeId");

                    b.Property<DateTime>("StartPeriod");

                    b.Property<string>("StatId");

                    b.Property<DateTime?>("StatIdDate");

                    b.Property<string>("Status");

                    b.Property<DateTime>("StatusDate");

                    b.Property<string>("SuspensionEnd");

                    b.Property<string>("SuspensionStart");

                    b.Property<DateTime?>("TaxRegDate");

                    b.Property<string>("TaxRegId");

                    b.Property<string>("TelephoneNo");

                    b.Property<decimal?>("Turnover");

                    b.Property<DateTime?>("TurnoverDate");

                    b.Property<int?>("TurnoverYear");

                    b.Property<int?>("UnitStatusId");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.Property<string>("WebAddress");

                    b.HasKey("RegId");

                    b.HasIndex("ActualAddressId");

                    b.HasIndex("AddressId");

                    b.HasIndex("DataSourceClassificationId");

                    b.HasIndex("Name");

                    b.HasIndex("PostalAddressId");

                    b.HasIndex("RegistrationReasonId");

                    b.HasIndex("SizeId");

                    b.HasIndex("StartPeriod");

                    b.ToTable("EnterpriseGroupsHistory");
                });

            modelBuilder.Entity("nscreg.Data.Entities.History.PersonStatisticalUnitHistory", b =>
                {
                    b.Property<int>("UnitId")
                        .HasColumnName("Unit_Id");

                    b.Property<int?>("PersonId")
                        .HasColumnName("Person_Id");

                    b.Property<int?>("EnterpriseGroupId")
                        .HasColumnName("GroupUnit_Id");

                    b.Property<int?>("PersonTypeId");

                    b.HasKey("UnitId", "PersonId");

                    b.HasIndex("EnterpriseGroupId");

                    b.HasIndex("PersonId");

                    b.HasIndex("PersonTypeId", "UnitId", "PersonId")
                        .IsUnique()
                        .HasFilter("[PersonTypeId] IS NOT NULL");

                    b.ToTable("PersonStatisticalUnitHistory");
                });

            modelBuilder.Entity("nscreg.Data.Entities.History.StatisticalUnitHistory", b =>
                {
                    b.Property<int>("RegId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ActualAddressId");

                    b.Property<int?>("AddressId");

                    b.Property<int>("ChangeReason")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<bool?>("Classified");

                    b.Property<string>("DataSource");

                    b.Property<int?>("DataSourceClassificationId");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("EditComment");

                    b.Property<string>("EmailAddress");

                    b.Property<int?>("Employees");

                    b.Property<DateTime?>("EmployeesDate");

                    b.Property<int?>("EmployeesYear");

                    b.Property<DateTime>("EndPeriod");

                    b.Property<string>("ExternalId");

                    b.Property<DateTime?>("ExternalIdDate");

                    b.Property<string>("ExternalIdType");

                    b.Property<int?>("ForeignParticipationId");

                    b.Property<bool>("FreeEconZone");

                    b.Property<int?>("InstSectorCodeId");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("LegalFormId");

                    b.Property<DateTime?>("LiqDate");

                    b.Property<string>("LiqReason");

                    b.Property<string>("Name")
                        .HasMaxLength(400);

                    b.Property<string>("Notes");

                    b.Property<int?>("NumOfPeopleEmp");

                    b.Property<int?>("ParentId");

                    b.Property<int?>("ParentOrgLink");

                    b.Property<int?>("PostalAddressId");

                    b.Property<string>("RefNo")
                        .HasMaxLength(25);

                    b.Property<DateTime>("RegIdDate");

                    b.Property<DateTime>("RegistrationDate");

                    b.Property<int?>("RegistrationReasonId");

                    b.Property<DateTime?>("ReorgDate");

                    b.Property<int?>("ReorgReferences");

                    b.Property<string>("ReorgTypeCode");

                    b.Property<int?>("ReorgTypeId");

                    b.Property<string>("ShortName");

                    b.Property<int?>("SizeId");

                    b.Property<DateTime>("StartPeriod");

                    b.Property<string>("StatId")
                        .HasMaxLength(15);

                    b.Property<DateTime?>("StatIdDate");

                    b.Property<DateTime?>("StatusDate");

                    b.Property<DateTime?>("SuspensionEnd");

                    b.Property<DateTime?>("SuspensionStart");

                    b.Property<DateTime?>("TaxRegDate");

                    b.Property<string>("TaxRegId");

                    b.Property<string>("TelephoneNo");

                    b.Property<decimal?>("Turnover");

                    b.Property<DateTime?>("TurnoverDate");

                    b.Property<int?>("TurnoverYear");

                    b.Property<int?>("UnitStatusId");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.Property<string>("WebAddress");

                    b.HasKey("RegId");

                    b.HasIndex("ActualAddressId");

                    b.HasIndex("AddressId");

                    b.HasIndex("DataSourceClassificationId");

                    b.HasIndex("InstSectorCodeId");

                    b.HasIndex("LegalFormId");

                    b.HasIndex("Name");

                    b.HasIndex("ParentId");

                    b.HasIndex("PostalAddressId");

                    b.HasIndex("RegistrationReasonId");

                    b.HasIndex("SizeId");

                    b.HasIndex("StartPeriod");

                    b.HasIndex("StatId");

                    b.ToTable("StatisticalUnitHistory");

                    b.HasDiscriminator<string>("Discriminator").HasValue("StatisticalUnitHistory");
                });

            modelBuilder.Entity("nscreg.Data.Entities.LegalForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("NameLanguage1");

                    b.Property<string>("NameLanguage2");

                    b.Property<int?>("ParentId");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("LegalForms");
                });

            modelBuilder.Entity("nscreg.Data.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<DateTime?>("BirthDate");

                    b.Property<int>("CountryId");

                    b.Property<string>("GivenName")
                        .HasMaxLength(150);

                    b.Property<DateTime>("IdDate");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(150);

                    b.Property<string>("PersonalId");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("PhoneNumber1");

                    b.Property<byte?>("Sex");

                    b.Property<string>("Surname")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("GivenName", "Surname");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("nscreg.Data.Entities.PersonStatisticalUnit", b =>
                {
                    b.Property<int>("UnitId")
                        .HasColumnName("Unit_Id");

                    b.Property<int?>("PersonId")
                        .HasColumnName("Person_Id");

                    b.Property<int?>("EnterpriseGroupId")
                        .HasColumnName("GroupUnit_Id");

                    b.Property<int?>("PersonTypeId");

                    b.HasKey("UnitId", "PersonId");

                    b.HasIndex("EnterpriseGroupId");

                    b.HasIndex("PersonId");

                    b.HasIndex("PersonTypeId", "UnitId", "PersonId")
                        .IsUnique()
                        .HasFilter("[PersonTypeId] IS NOT NULL");

                    b.ToTable("PersonStatisticalUnits");
                });

            modelBuilder.Entity("nscreg.Data.Entities.PersonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<string>("NameLanguage1");

                    b.Property<string>("NameLanguage2");

                    b.HasKey("Id");

                    b.ToTable("PersonTypes");
                });

            modelBuilder.Entity("nscreg.Data.Entities.PostalIndex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<string>("NameLanguage1");

                    b.Property<string>("NameLanguage2");

                    b.HasKey("Id");

                    b.ToTable("PostalIndices");
                });

            modelBuilder.Entity("nscreg.Data.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminstrativeCenter");

                    b.Property<string>("Code");

                    b.Property<string>("FullPath");

                    b.Property<string>("FullPathLanguage1");

                    b.Property<string>("FullPathLanguage2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("NameLanguage1");

                    b.Property<string>("NameLanguage2");

                    b.Property<int?>("ParentId");

                    b.Property<int?>("RegionLevel");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.HasIndex("ParentId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("nscreg.Data.Entities.RegistrationReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("NameLanguage1");

                    b.Property<string>("NameLanguage2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.ToTable("RegistrationReasons");
                });

            modelBuilder.Entity("nscreg.Data.Entities.ReorgType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<string>("NameLanguage1");

                    b.Property<string>("NameLanguage2");

                    b.HasKey("Id");

                    b.ToTable("ReorgTypes");
                });

            modelBuilder.Entity("nscreg.Data.Entities.ReportTree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ParentNodeId");

                    b.Property<int?>("ReportId");

                    b.Property<string>("ReportUrl");

                    b.Property<string>("ResourceGroup");

                    b.Property<string>("Title");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("ReportTree");
                });

            modelBuilder.Entity("nscreg.Data.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessToSystemFunctions");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.Property<string>("SqlWalletUser");

                    b.Property<string>("StandardDataAccess");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("nscreg.Data.Entities.SampleFrame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<DateTime?>("EditingDate");

                    b.Property<string>("Fields")
                        .IsRequired();

                    b.Property<string>("FilePath");

                    b.Property<DateTime?>("GeneratedDateTime");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Predicate")
                        .IsRequired();

                    b.Property<int>("Status");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SampleFrames");
                });

            modelBuilder.Entity("nscreg.Data.Entities.SectorCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("NameLanguage1");

                    b.Property<string>("NameLanguage2");

                    b.Property<int?>("ParentId");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.HasIndex("ParentId");

                    b.ToTable("SectorCodes");
                });

            modelBuilder.Entity("nscreg.Data.Entities.StatUnitSearchView", b =>
                {
                    b.Property<int>("RegId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressPart1");

                    b.Property<string>("AddressPart2");

                    b.Property<string>("AddressPart3");

                    b.Property<int>("ChangeReason");

                    b.Property<int?>("DataSourceClassificationId");

                    b.Property<int?>("Employees");

                    b.Property<string>("ExternalId");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("LegalFormId");

                    b.Property<DateTime?>("LiqDate");

                    b.Property<string>("LiqReason");

                    b.Property<string>("Name");

                    b.Property<int?>("RegionId");

                    b.Property<int?>("SectorCodeId");

                    b.Property<DateTime>("StartPeriod");

                    b.Property<string>("StatId");

                    b.Property<string>("TaxRegId");

                    b.Property<decimal?>("Turnover");

                    b.Property<int>("UnitType");

                    b.HasKey("RegId");

                    b.ToTable("V_StatUnitSearch");
                });

            modelBuilder.Entity("nscreg.Data.Entities.StatisticalUnit", b =>
                {
                    b.Property<int>("RegId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ActualAddressId");

                    b.Property<int?>("AddressId");

                    b.Property<int>("ChangeReason")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<bool?>("Classified");

                    b.Property<string>("DataSource");

                    b.Property<int?>("DataSourceClassificationId");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("EditComment");

                    b.Property<string>("EmailAddress");

                    b.Property<int?>("Employees");

                    b.Property<DateTime?>("EmployeesDate");

                    b.Property<int?>("EmployeesYear");

                    b.Property<DateTime>("EndPeriod");

                    b.Property<string>("ExternalId");

                    b.Property<DateTime?>("ExternalIdDate");

                    b.Property<string>("ExternalIdType");

                    b.Property<int?>("ForeignParticipationId");

                    b.Property<bool>("FreeEconZone");

                    b.Property<int?>("InstSectorCodeId");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("LegalFormId");

                    b.Property<DateTime?>("LiqDate");

                    b.Property<string>("LiqReason");

                    b.Property<string>("Name")
                        .HasMaxLength(400);

                    b.Property<string>("Notes");

                    b.Property<int?>("NumOfPeopleEmp");

                    b.Property<int?>("ParentOrgLink");

                    b.Property<int?>("PostalAddressId");

                    b.Property<string>("RefNo")
                        .HasMaxLength(25);

                    b.Property<DateTime>("RegIdDate");

                    b.Property<DateTime>("RegistrationDate");

                    b.Property<int?>("RegistrationReasonId");

                    b.Property<DateTime?>("ReorgDate");

                    b.Property<int?>("ReorgReferences");

                    b.Property<string>("ReorgTypeCode");

                    b.Property<int?>("ReorgTypeId");

                    b.Property<string>("ShortName");

                    b.Property<int?>("SizeId");

                    b.Property<DateTime>("StartPeriod");

                    b.Property<string>("StatId")
                        .HasMaxLength(15);

                    b.Property<DateTime?>("StatIdDate");

                    b.Property<DateTime?>("StatusDate");

                    b.Property<DateTime?>("SuspensionEnd");

                    b.Property<DateTime?>("SuspensionStart");

                    b.Property<DateTime?>("TaxRegDate");

                    b.Property<string>("TaxRegId");

                    b.Property<string>("TelephoneNo");

                    b.Property<decimal?>("Turnover");

                    b.Property<DateTime?>("TurnoverDate");

                    b.Property<int?>("TurnoverYear");

                    b.Property<int?>("UnitStatusId");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.Property<string>("WebAddress");

                    b.HasKey("RegId");

                    b.HasIndex("ActualAddressId");

                    b.HasIndex("AddressId");

                    b.HasIndex("DataSourceClassificationId");

                    b.HasIndex("ForeignParticipationId");

                    b.HasIndex("InstSectorCodeId");

                    b.HasIndex("LegalFormId");

                    b.HasIndex("Name");

                    b.HasIndex("PostalAddressId");

                    b.HasIndex("RegistrationReasonId");

                    b.HasIndex("ReorgTypeId");

                    b.HasIndex("SizeId");

                    b.HasIndex("StartPeriod");

                    b.HasIndex("StatId");

                    b.HasIndex("UnitStatusId");

                    b.ToTable("StatisticalUnits");

                    b.HasDiscriminator<string>("Discriminator").HasValue("StatisticalUnit");
                });

            modelBuilder.Entity("nscreg.Data.Entities.UnitSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<string>("NameLanguage1");

                    b.Property<string>("NameLanguage2");

                    b.HasKey("Id");

                    b.ToTable("UnitsSize");
                });

            modelBuilder.Entity("nscreg.Data.Entities.UnitStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<string>("NameLanguage1");

                    b.Property<string>("NameLanguage2");

                    b.HasKey("Id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("nscreg.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("DataAccess");

                    b.Property<string>("Description");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("Name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<int>("Status");

                    b.Property<DateTime?>("SuspensionDate");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("nscreg.Data.Entities.UserRegion", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnName("User_Id");

                    b.Property<int>("RegionId")
                        .HasColumnName("Region_Id");

                    b.HasKey("UserId", "RegionId");

                    b.HasIndex("RegionId");

                    b.ToTable("UserRegions");
                });

            modelBuilder.Entity("nscreg.Data.Entities.UserRole", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("nscreg.Data.Entities.History.EnterpriseUnitHistory", b =>
                {
                    b.HasBaseType("nscreg.Data.Entities.History.StatisticalUnitHistory");

                    b.Property<bool>("Commercial");

                    b.Property<int?>("EntGroupId");

                    b.Property<DateTime>("EntGroupIdDate");

                    b.Property<string>("EntGroupRole");

                    b.Property<string>("ForeignCapitalCurrency")
                        .HasColumnName("ForeignCapitalCurrency");

                    b.Property<string>("ForeignCapitalShare")
                        .HasColumnName("ForeignCapitalShare");

                    b.Property<string>("HistoryLegalUnitIds");

                    b.Property<string>("MunCapitalShare")
                        .HasColumnName("MunCapitalShare");

                    b.Property<string>("PrivCapitalShare")
                        .HasColumnName("PrivCapitalShare");

                    b.Property<string>("StateCapitalShare")
                        .HasColumnName("StateCapitalShare");

                    b.Property<string>("TotalCapital")
                        .HasColumnName("TotalCapital");

                    b.HasIndex("EntGroupId");

                    b.ToTable("EnterpriseUnitsHistory");

                    b.HasDiscriminator().HasValue("EnterpriseUnitHistory");
                });

            modelBuilder.Entity("nscreg.Data.Entities.History.LegalUnitHistory", b =>
                {
                    b.HasBaseType("nscreg.Data.Entities.History.StatisticalUnitHistory");

                    b.Property<DateTime?>("EntRegIdDate");

                    b.Property<int?>("EnterpriseUnitRegId");

                    b.Property<string>("ForeignCapitalCurrency")
                        .HasColumnName("ForeignCapitalCurrency");

                    b.Property<string>("ForeignCapitalShare")
                        .HasColumnName("ForeignCapitalShare");

                    b.Property<string>("HistoryLocalUnitIds");

                    b.Property<bool>("Market");

                    b.Property<string>("MunCapitalShare")
                        .HasColumnName("MunCapitalShare");

                    b.Property<string>("PrivCapitalShare")
                        .HasColumnName("PrivCapitalShare");

                    b.Property<string>("StateCapitalShare")
                        .HasColumnName("StateCapitalShare");

                    b.Property<string>("TotalCapital")
                        .HasColumnName("TotalCapital");

                    b.HasIndex("EnterpriseUnitRegId");

                    b.ToTable("LegalUnitsHistory");

                    b.HasDiscriminator().HasValue("LegalUnitHistory");
                });

            modelBuilder.Entity("nscreg.Data.Entities.History.LocalUnitHistory", b =>
                {
                    b.HasBaseType("nscreg.Data.Entities.History.StatisticalUnitHistory");

                    b.Property<int?>("LegalUnitId");

                    b.Property<DateTime>("LegalUnitIdDate");

                    b.HasIndex("LegalUnitId");

                    b.ToTable("LocalUnitsHistory");

                    b.HasDiscriminator().HasValue("LocalUnitHistory");
                });

            modelBuilder.Entity("nscreg.Data.Entities.EnterpriseUnit", b =>
                {
                    b.HasBaseType("nscreg.Data.Entities.StatisticalUnit");

                    b.Property<bool>("Commercial");

                    b.Property<int?>("EntGroupId");

                    b.Property<DateTime>("EntGroupIdDate");

                    b.Property<string>("EntGroupRole");

                    b.Property<string>("ForeignCapitalCurrency")
                        .HasColumnName("ForeignCapitalCurrency");

                    b.Property<string>("ForeignCapitalShare")
                        .HasColumnName("ForeignCapitalShare");

                    b.Property<string>("HistoryLegalUnitIds");

                    b.Property<string>("MunCapitalShare")
                        .HasColumnName("MunCapitalShare");

                    b.Property<string>("PrivCapitalShare")
                        .HasColumnName("PrivCapitalShare");

                    b.Property<string>("StateCapitalShare")
                        .HasColumnName("StateCapitalShare");

                    b.Property<string>("TotalCapital")
                        .HasColumnName("TotalCapital");

                    b.HasIndex("EntGroupId");

                    b.ToTable("EnterpriseUnits");

                    b.HasDiscriminator().HasValue("EnterpriseUnit");
                });

            modelBuilder.Entity("nscreg.Data.Entities.LegalUnit", b =>
                {
                    b.HasBaseType("nscreg.Data.Entities.StatisticalUnit");

                    b.Property<DateTime?>("EntRegIdDate");

                    b.Property<int?>("EnterpriseUnitRegId");

                    b.Property<string>("ForeignCapitalCurrency")
                        .HasColumnName("ForeignCapitalCurrency");

                    b.Property<string>("ForeignCapitalShare")
                        .HasColumnName("ForeignCapitalShare");

                    b.Property<string>("HistoryLocalUnitIds");

                    b.Property<bool>("Market");

                    b.Property<string>("MunCapitalShare")
                        .HasColumnName("MunCapitalShare");

                    b.Property<string>("PrivCapitalShare")
                        .HasColumnName("PrivCapitalShare");

                    b.Property<string>("StateCapitalShare")
                        .HasColumnName("StateCapitalShare");

                    b.Property<string>("TotalCapital")
                        .HasColumnName("TotalCapital");

                    b.HasIndex("EnterpriseUnitRegId");

                    b.ToTable("LegalUnits");

                    b.HasDiscriminator().HasValue("LegalUnit");
                });

            modelBuilder.Entity("nscreg.Data.Entities.LocalUnit", b =>
                {
                    b.HasBaseType("nscreg.Data.Entities.StatisticalUnit");

                    b.Property<int?>("LegalUnitId");

                    b.Property<DateTime>("LegalUnitIdDate");

                    b.HasIndex("LegalUnitId");

                    b.ToTable("LocalUnits");

                    b.HasDiscriminator().HasValue("LocalUnit");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("nscreg.Data.Entities.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("nscreg.Data.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("nscreg.Data.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("nscreg.Data.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("nscreg.Data.Entities.Activity", b =>
                {
                    b.HasOne("nscreg.Data.Entities.ActivityCategory", "ActivityCategory")
                        .WithMany()
                        .HasForeignKey("ActivityCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("nscreg.Data.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("nscreg.Data.Entities.ActivityCategoryUser", b =>
                {
                    b.HasOne("nscreg.Data.Entities.ActivityCategory", "ActivityCategory")
                        .WithMany("ActivityCategoryUsers")
                        .HasForeignKey("ActivityCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("nscreg.Data.Entities.User", "User")
                        .WithMany("ActivitysCategoryUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("nscreg.Data.Entities.ActivityStatisticalUnit", b =>
                {
                    b.HasOne("nscreg.Data.Entities.Activity", "Activity")
                        .WithMany("ActivitiesUnits")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("nscreg.Data.Entities.StatisticalUnit", "Unit")
                        .WithMany("ActivitiesUnits")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("nscreg.Data.Entities.Address", b =>
                {
                    b.HasOne("nscreg.Data.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("nscreg.Data.Entities.AnalysisLog", b =>
                {
                    b.HasOne("nscreg.Data.Entities.AnalysisQueue", "AnalysisQueue")
                        .WithMany("AnalysisLogs")
                        .HasForeignKey("AnalysisQueueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("nscreg.Data.Entities.AnalysisQueue", b =>
                {
                    b.HasOne("nscreg.Data.Entities.User", "User")
                        .WithMany("AnalysisQueues")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("nscreg.Data.Entities.CountryStatisticalUnit", b =>
                {
                    b.HasOne("nscreg.Data.Entities.Country", "Country")
                        .WithMany("CountriesUnits")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("nscreg.Data.Entities.StatisticalUnit", "Unit")
                        .WithMany("ForeignParticipationCountriesUnits")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("nscreg.Data.Entities.DataSource", b =>
                {
                    b.HasOne("nscreg.Data.Entities.User", "User")
                        .WithMany("DataSources")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("nscreg.Data.Entities.DataSourceQueue", b =>
                {
                    b.HasOne("nscreg.Data.Entities.DataSource", "DataSource")
                        .WithMany("DataSourceQueuedUploads")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("nscreg.Data.Entities.User", "User")
                        .WithMany("DataSourceQueues")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("nscreg.Data.Entities.DataUploadingLog", b =>
                {
                    b.HasOne("nscreg.Data.Entities.DataSourceQueue", "DataSourceQueue")
                        .WithMany("DataUploadingLogs")
                        .HasForeignKey("DataSourceQueueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("nscreg.Data.Entities.EnterpriseGroup", b =>
                {
                    b.HasOne("nscreg.Data.Entities.Address", "ActualAddress")
                        .WithMany()
                        .HasForeignKey("ActualAddressId");

                    b.HasOne("nscreg.Data.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("nscreg.Data.Entities.DataSourceClassification", "DataSourceClassification")
                        .WithMany()
                        .HasForeignKey("DataSourceClassificationId");

                    b.HasOne("nscreg.Data.Entities.EnterpriseGroupType", "EntGroupType")
                        .WithMany("EnterpriseGroups")
                        .HasForeignKey("EntGroupTypeId");

                    b.HasOne("nscreg.Data.Entities.Address", "PostalAddress")
                        .WithMany()
                        .HasForeignKey("PostalAddressId");

                    b.HasOne("nscreg.Data.Entities.RegistrationReason", "RegistrationReason")
                        .WithMany()
                        .HasForeignKey("RegistrationReasonId");

                    b.HasOne("nscreg.Data.Entities.ReorgType", "ReorgType")
                        .WithMany()
                        .HasForeignKey("ReorgTypeId");

                    b.HasOne("nscreg.Data.Entities.UnitSize", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId");

                    b.HasOne("nscreg.Data.Entities.UnitStatus", "UnitStatus")
                        .WithMany()
                        .HasForeignKey("UnitStatusId");
                });

            modelBuilder.Entity("nscreg.Data.Entities.History.ActivityStatisticalUnitHistory", b =>
                {
                    b.HasOne("nscreg.Data.Entities.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("nscreg.Data.Entities.History.StatisticalUnitHistory", "Unit")
                        .WithMany("ActivitiesUnits")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("nscreg.Data.Entities.History.CountryStatisticalUnitHistory", b =>
                {
                    b.HasOne("nscreg.Data.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("nscreg.Data.Entities.History.StatisticalUnitHistory", "Unit")
                        .WithMany("ForeignParticipationCountriesUnits")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("nscreg.Data.Entities.History.EnterpriseGroupHistory", b =>
                {
                    b.HasOne("nscreg.Data.Entities.Address", "ActualAddress")
                        .WithMany()
                        .HasForeignKey("ActualAddressId");

                    b.HasOne("nscreg.Data.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("nscreg.Data.Entities.DataSourceClassification", "DataSourceClassification")
                        .WithMany()
                        .HasForeignKey("DataSourceClassificationId");

                    b.HasOne("nscreg.Data.Entities.Address", "PostalAddress")
                        .WithMany()
                        .HasForeignKey("PostalAddressId");

                    b.HasOne("nscreg.Data.Entities.RegistrationReason", "RegistrationReason")
                        .WithMany()
                        .HasForeignKey("RegistrationReasonId");

                    b.HasOne("nscreg.Data.Entities.UnitSize", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId");
                });

            modelBuilder.Entity("nscreg.Data.Entities.History.PersonStatisticalUnitHistory", b =>
                {
                    b.HasOne("nscreg.Data.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("nscreg.Data.Entities.PersonType", "PersonType")
                        .WithMany()
                        .HasForeignKey("PersonTypeId");

                    b.HasOne("nscreg.Data.Entities.History.StatisticalUnitHistory", "Unit")
                        .WithMany("PersonsUnits")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("nscreg.Data.Entities.History.StatisticalUnitHistory", b =>
                {
                    b.HasOne("nscreg.Data.Entities.Address", "ActualAddress")
                        .WithMany()
                        .HasForeignKey("ActualAddressId");

                    b.HasOne("nscreg.Data.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("nscreg.Data.Entities.DataSourceClassification", "DataSourceClassification")
                        .WithMany()
                        .HasForeignKey("DataSourceClassificationId");

                    b.HasOne("nscreg.Data.Entities.SectorCode", "InstSectorCode")
                        .WithMany()
                        .HasForeignKey("InstSectorCodeId");

                    b.HasOne("nscreg.Data.Entities.LegalForm", "LegalForm")
                        .WithMany()
                        .HasForeignKey("LegalFormId");

                    b.HasOne("nscreg.Data.Entities.StatisticalUnit", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("nscreg.Data.Entities.Address", "PostalAddress")
                        .WithMany()
                        .HasForeignKey("PostalAddressId");

                    b.HasOne("nscreg.Data.Entities.RegistrationReason", "RegistrationReason")
                        .WithMany()
                        .HasForeignKey("RegistrationReasonId");

                    b.HasOne("nscreg.Data.Entities.UnitSize", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId");
                });

            modelBuilder.Entity("nscreg.Data.Entities.LegalForm", b =>
                {
                    b.HasOne("nscreg.Data.Entities.LegalForm", "Parent")
                        .WithMany("LegalForms")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("nscreg.Data.Entities.Person", b =>
                {
                    b.HasOne("nscreg.Data.Entities.Country", "NationalityCode")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("nscreg.Data.Entities.PersonStatisticalUnit", b =>
                {
                    b.HasOne("nscreg.Data.Entities.EnterpriseGroup", "EnterpriseGroup")
                        .WithMany("PersonsUnits")
                        .HasForeignKey("EnterpriseGroupId");

                    b.HasOne("nscreg.Data.Entities.Person", "Person")
                        .WithMany("PersonsUnits")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("nscreg.Data.Entities.PersonType", "PersonType")
                        .WithMany()
                        .HasForeignKey("PersonTypeId");

                    b.HasOne("nscreg.Data.Entities.StatisticalUnit", "Unit")
                        .WithMany("PersonsUnits")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("nscreg.Data.Entities.Region", b =>
                {
                    b.HasOne("nscreg.Data.Entities.Region", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("nscreg.Data.Entities.SampleFrame", b =>
                {
                    b.HasOne("nscreg.Data.Entities.User", "User")
                        .WithMany("SampleFrames")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("nscreg.Data.Entities.SectorCode", b =>
                {
                    b.HasOne("nscreg.Data.Entities.SectorCode", "Parent")
                        .WithMany("SectorCodes")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("nscreg.Data.Entities.StatisticalUnit", b =>
                {
                    b.HasOne("nscreg.Data.Entities.Address", "ActualAddress")
                        .WithMany()
                        .HasForeignKey("ActualAddressId");

                    b.HasOne("nscreg.Data.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("nscreg.Data.Entities.DataSourceClassification", "DataSourceClassification")
                        .WithMany()
                        .HasForeignKey("DataSourceClassificationId");

                    b.HasOne("nscreg.Data.Entities.ForeignParticipation", "ForeignParticipation")
                        .WithMany()
                        .HasForeignKey("ForeignParticipationId");

                    b.HasOne("nscreg.Data.Entities.SectorCode", "InstSectorCode")
                        .WithMany()
                        .HasForeignKey("InstSectorCodeId");

                    b.HasOne("nscreg.Data.Entities.LegalForm", "LegalForm")
                        .WithMany()
                        .HasForeignKey("LegalFormId");

                    b.HasOne("nscreg.Data.Entities.Address", "PostalAddress")
                        .WithMany()
                        .HasForeignKey("PostalAddressId");

                    b.HasOne("nscreg.Data.Entities.RegistrationReason", "RegistrationReason")
                        .WithMany()
                        .HasForeignKey("RegistrationReasonId");

                    b.HasOne("nscreg.Data.Entities.ReorgType", "ReorgType")
                        .WithMany()
                        .HasForeignKey("ReorgTypeId");

                    b.HasOne("nscreg.Data.Entities.UnitSize", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId");

                    b.HasOne("nscreg.Data.Entities.UnitStatus", "UnitStatus")
                        .WithMany()
                        .HasForeignKey("UnitStatusId");
                });

            modelBuilder.Entity("nscreg.Data.Entities.UserRegion", b =>
                {
                    b.HasOne("nscreg.Data.Entities.Region", "Region")
                        .WithMany("UserRegions")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("nscreg.Data.Entities.User", "User")
                        .WithMany("UserRegions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("nscreg.Data.Entities.UserRole", b =>
                {
                    b.HasOne("nscreg.Data.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("nscreg.Data.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("nscreg.Data.Entities.EnterpriseUnit", b =>
                {
                    b.HasOne("nscreg.Data.Entities.EnterpriseGroup", "EnterpriseGroup")
                        .WithMany("EnterpriseUnits")
                        .HasForeignKey("EntGroupId");
                });

            modelBuilder.Entity("nscreg.Data.Entities.LegalUnit", b =>
                {
                    b.HasOne("nscreg.Data.Entities.EnterpriseUnit", "EnterpriseUnit")
                        .WithMany("LegalUnits")
                        .HasForeignKey("EnterpriseUnitRegId");
                });

            modelBuilder.Entity("nscreg.Data.Entities.LocalUnit", b =>
                {
                    b.HasOne("nscreg.Data.Entities.LegalUnit", "LegalUnit")
                        .WithMany("LocalUnits")
                        .HasForeignKey("LegalUnitId");
                });
#pragma warning restore 612, 618
        }
    }
}
