version: "3.8"
name: ${COMPOSE_INSTANCE_NAME}
# Expose wanted ports
# Not that docker-compose.erase-ports.yml used the `!reset []` syntax
# to remove the ports from docker-compose.yml and here we
# can add new values
services:
  studio:
    container_name: ${COMPOSE_INSTANCE_NAME}-studio
  kong:
    container_name: ${COMPOSE_INSTANCE_NAME}-kong
    ports:
      - ${SUPABASE_BIND_ADDRESS}:8000/tcp
  auth:
    container_name: ${COMPOSE_INSTANCE_NAME}-auth
  rest:
    container_name: ${COMPOSE_INSTANCE_NAME}-rest
  realtime:
    # This container name looks inconsistent but is correct because realtime constructs tenant id by parsing the subdomain
    container_name: ${COMPOSE_INSTANCE_NAME}-realtime
  storage:
    container_name: ${COMPOSE_INSTANCE_NAME}-storage
  imgproxy:
    container_name: ${COMPOSE_INSTANCE_NAME}-imgproxy
  meta:
    container_name: ${COMPOSE_INSTANCE_NAME}-meta
  functions:
    container_name: ${COMPOSE_INSTANCE_NAME}-edge-functions
  analytics:
    container_name: ${COMPOSE_INSTANCE_NAME}-analytics
    ports: !reset []
  db:
    container_name: ${COMPOSE_INSTANCE_NAME}-db
    image: ghcr.io/veridit/supabase_postgres:latest
    #image: veridit/supabase_postgres:latest
    shm_size: 1g
    ports:
      - ${DB_PUBLIC_LOCALHOST_PORT}:5432
  vector:
    container_name: ${COMPOSE_INSTANCE_NAME}-vector

# Use a consistent network, for configuration of http forwarding
networks:
  statbus:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.64.0/24
