version: "3.8"
# Prevent internet exposure by resetting the ports
# Due to docker compose design, new values may not be provided
# and can instead be found in the docker-compose.customise.yml file
services:
  kong:
    ports: !reset []
  analytics:
    ports: !reset []
  db:
    ports: !reset []
