//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nscreg.Resources.Languages {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resource() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nscreg.Resources.Languages.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to nsreg.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Access to system functions.
        /// </summary>
        public static string AccessToSystemFunctions {
            get {
                return ResourceManager.GetString("AccessToSystemFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to AccountEdit.
        /// </summary>
        public static string AccountEdit {
            get {
                return ResourceManager.GetString("AccountEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to AccountView.
        /// </summary>
        public static string AccountView {
            get {
                return ResourceManager.GetString("AccountView", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Activity.
        /// </summary>
        public static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Actual address.
        /// </summary>
        public static string ActualAddress {
            get {
                return ResourceManager.GetString("ActualAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ActualAddressId.
        /// </summary>
        public static string ActualAddressId {
            get {
                return ResourceManager.GetString("ActualAddressId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Actual main activity1.
        /// </summary>
        public static string ActualMainActivity1 {
            get {
                return ResourceManager.GetString("ActualMainActivity1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Actual main activity 2.
        /// </summary>
        public static string ActualMainActivity2 {
            get {
                return ResourceManager.GetString("ActualMainActivity2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Actual main activity date.
        /// </summary>
        public static string ActualMainActivityDate {
            get {
                return ResourceManager.GetString("ActualMainActivityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error: Address already exists in data base for.
        /// </summary>
        public static string AddressExcistsInDataBaseForError {
            get {
                return ResourceManager.GetString("AddressExcistsInDataBaseForError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to AddressId.
        /// </summary>
        public static string AddressId {
            get {
                return ResourceManager.GetString("AddressId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Administrative tools.
        /// </summary>
        public static string AdministrativeTools {
            get {
                return ResourceManager.GetString("AdministrativeTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Any type.
        /// </summary>
        public static string AnyType {
            get {
                return ResourceManager.GetString("AnyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Are you sure.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Assigned roles.
        /// </summary>
        public static string AssignedRoles {
            get {
                return ResourceManager.GetString("AssignedRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Back to home.
        /// </summary>
        public static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Choose at least one item.
        /// </summary>
        public static string ChooseAtLeastOne {
            get {
                return ResourceManager.GetString("ChooseAtLeastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Classified.
        /// </summary>
        public static string Classified {
            get {
                return ResourceManager.GetString("Classified", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Commercial.
        /// </summary>
        public static string Commercial {
            get {
                return ResourceManager.GetString("Commercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Contact person.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error while create Enterprise Group.
        /// </summary>
        public static string CreateEnterpriseGroupError {
            get {
                return ResourceManager.GetString("CreateEnterpriseGroupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error while create Enterprise Unit.
        /// </summary>
        public static string CreateEnterpriseUnitError {
            get {
                return ResourceManager.GetString("CreateEnterpriseUnitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error while create Legal Unit.
        /// </summary>
        public static string CreateLegalUnitError {
            get {
                return ResourceManager.GetString("CreateLegalUnitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error while create Local Unit.
        /// </summary>
        public static string CreateLocalUnitError {
            get {
                return ResourceManager.GetString("CreateLocalUnitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Creation new role.
        /// </summary>
        public static string CreateNewRole {
            get {
                return ResourceManager.GetString("CreateNewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Create new user.
        /// </summary>
        public static string CreateNewUser {
            get {
                return ResourceManager.GetString("CreateNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Create role.
        /// </summary>
        public static string CreateRoleButton {
            get {
                return ResourceManager.GetString("CreateRoleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to CreateStatUnit.
        /// </summary>
        public static string CreateStatUnit {
            get {
                return ResourceManager.GetString("CreateStatUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Create user.
        /// </summary>
        public static string CreateUserButton {
            get {
                return ResourceManager.GetString("CreateUserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Field &apos;Current password&apos; is required.
        /// </summary>
        public static string CurrentPasswordIsRequired {
            get {
                return ResourceManager.GetString("CurrentPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Current password is wrong.
        /// </summary>
        public static string CurrentPasswordisWrong {
            get {
                return ResourceManager.GetString("CurrentPasswordisWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Data access.
        /// </summary>
        public static string DataAccess {
            get {
                return ResourceManager.GetString("DataAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Data source.
        /// </summary>
        public static string DataSource {
            get {
                return ResourceManager.GetString("DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Can&apos;t delete very last system administrator.
        /// </summary>
        public static string DeleteLastSysAdminError {
            get {
                return ResourceManager.GetString("DeleteLastSysAdminError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Can&apos;t delete role with existing users.
        /// </summary>
        public static string DeleteRoleError {
            get {
                return ResourceManager.GetString("DeleteRoleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Delete role.
        /// </summary>
        public static string DeleteRoleMessage {
            get {
                return ResourceManager.GetString("DeleteRoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Delete Statistic unit.
        /// </summary>
        public static string DeleteStatUnitMessage {
            get {
                return ResourceManager.GetString("DeleteStatUnitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Can&apos;t delete system administrator role.
        /// </summary>
        public static string DeleteSysAdminRoleError {
            get {
                return ResourceManager.GetString("DeleteSysAdminRoleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Delete user.
        /// </summary>
        public static string DeleteUserMessage {
            get {
                return ResourceManager.GetString("DeleteUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Edit account.
        /// </summary>
        public static string EditAccount {
            get {
                return ResourceManager.GetString("EditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Editing role.
        /// </summary>
        public static string EditRole {
            get {
                return ResourceManager.GetString("EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Editing user.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to EmailAddress.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Field &apos;EmailIsRequired&apos; is required.
        /// </summary>
        public static string EmailIsRequired {
            get {
                return ResourceManager.GetString("EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Email value required.
        /// </summary>
        public static string EmailValueRequired {
            get {
                return ResourceManager.GetString("EmailValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Employees.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Employees date.
        /// </summary>
        public static string EmployeesDate {
            get {
                return ResourceManager.GetString("EmployeesDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to EmployeesFte.
        /// </summary>
        public static string EmployeesFte {
            get {
                return ResourceManager.GetString("EmployeesFte", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Number of employees from is larger than &apos;number of employees to&apos;.
        /// </summary>
        public static string EmployeesNumberFromErrorLarge {
            get {
                return ResourceManager.GetString("EmployeesNumberFromErrorLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Number of employees from shouldn&apos;t be negative.
        /// </summary>
        public static string EmployeesNumberFromErrorNegative {
            get {
                return ResourceManager.GetString("EmployeesNumberFromErrorNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Number of employees to is less than &apos;number of employees from&apos;.
        /// </summary>
        public static string EmployeesNumberToErrorLess {
            get {
                return ResourceManager.GetString("EmployeesNumberToErrorLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Number of employees to shouldn&apos;t be negative.
        /// </summary>
        public static string EmployeesNumberToErrorNegative {
            get {
                return ResourceManager.GetString("EmployeesNumberToErrorNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Employees year.
        /// </summary>
        public static string EmployeesYear {
            get {
                return ResourceManager.GetString("EmployeesYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to EndPeriod.
        /// </summary>
        public static string EndPeriod {
            get {
                return ResourceManager.GetString("EndPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Enterprise group.
        /// </summary>
        public static string EnterpriseGroup {
            get {
                return ResourceManager.GetString("EnterpriseGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Field is required.
        /// </summary>
        public static string EnterpriseGroupIsRequired {
            get {
                return ResourceManager.GetString("EnterpriseGroupIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Enterprise group is not supported yet.
        /// </summary>
        public static string EnterpriseGroupNotSupportError {
            get {
                return ResourceManager.GetString("EnterpriseGroupNotSupportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Enterprise Group.
        /// </summary>
        public static string EnterpriseGroupRegId {
            get {
                return ResourceManager.GetString("EnterpriseGroupRegId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Field is required.
        /// </summary>
        public static string EnterpriseIsRequired {
            get {
                return ResourceManager.GetString("EnterpriseIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Enterprise registration id.
        /// </summary>
        public static string EnterpriseRegId {
            get {
                return ResourceManager.GetString("EnterpriseRegId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Enterprise unit.
        /// </summary>
        public static string EnterpriseUnit {
            get {
                return ResourceManager.GetString("EnterpriseUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to At least one enterprise unit is required.
        /// </summary>
        public static string EnterpriseUnitIsRequired {
            get {
                return ResourceManager.GetString("EnterpriseUnitIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to EnterpriseUnitRegId.
        /// </summary>
        public static string EnterpriseUnitRegId {
            get {
                return ResourceManager.GetString("EnterpriseUnitRegId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to EnterpriseUnits.
        /// </summary>
        public static string EnterpriseUnits {
            get {
                return ResourceManager.GetString("EnterpriseUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Enterprise group id.
        /// </summary>
        public static string EntGroupId {
            get {
                return ResourceManager.GetString("EntGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Enterprise group id date.
        /// </summary>
        public static string EntGroupIdDate {
            get {
                return ResourceManager.GetString("EntGroupIdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Enterprise  group role.
        /// </summary>
        public static string EntGroupRole {
            get {
                return ResourceManager.GetString("EntGroupRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to EntGroupType.
        /// </summary>
        public static string EntGroupType {
            get {
                return ResourceManager.GetString("EntGroupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Enterprise registration id date.
        /// </summary>
        public static string EntRegIdDate {
            get {
                return ResourceManager.GetString("EntRegIdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You don&apos;t have enough rights for this. Please, sign out and try to sign in again..
        /// </summary>
        public static string Error403 {
            get {
                return ResourceManager.GetString("Error403", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to External id.
        /// </summary>
        public static string ExternalId {
            get {
                return ResourceManager.GetString("ExternalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to External id date.
        /// </summary>
        public static string ExternalIdDate {
            get {
                return ResourceManager.GetString("ExternalIdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to External id type.
        /// </summary>
        public static string ExternalIdType {
            get {
                return ResourceManager.GetString("ExternalIdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Fetching standard data access.
        /// </summary>
        public static string FetchingStandardDataAccess {
            get {
                return ResourceManager.GetString("FetchingStandardDataAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error fetching users.
        /// </summary>
        public static string FetchingUsersError {
            get {
                return ResourceManager.GetString("FetchingUsersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Field is required.
        /// </summary>
        public static string FieldIsRequired {
            get {
                return ResourceManager.GetString("FieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Foreign capital currency.
        /// </summary>
        public static string ForeignCapitalCurrency {
            get {
                return ResourceManager.GetString("ForeignCapitalCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Foreign capital share.
        /// </summary>
        public static string ForeignCapitalShare {
            get {
                return ResourceManager.GetString("ForeignCapitalShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Foreign participation.
        /// </summary>
        public static string ForeignParticipation {
            get {
                return ResourceManager.GetString("ForeignParticipation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Founders.
        /// </summary>
        public static string Founders {
            get {
                return ResourceManager.GetString("Founders", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Free economic zone.
        /// </summary>
        public static string FreeEconZone {
            get {
                return ResourceManager.GetString("FreeEconZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Welcome.
        /// </summary>
        public static string HomeText {
            get {
                return ResourceManager.GetString("HomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Include liquidated.
        /// </summary>
        public static string Includeliquidated {
            get {
                return ResourceManager.GetString("Includeliquidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value can&apos;t be less than 0.
        /// </summary>
        public static string IncorrectIntegerValue {
            get {
                return ResourceManager.GetString("IncorrectIntegerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value must be greater than 0 and less than {0}.
        /// </summary>
        public static string IncorrectIntegerValueExt {
            get {
                return ResourceManager.GetString("IncorrectIntegerValueExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value can&apos;t be empty and greater than {0} symbols.
        /// </summary>
        public static string IncorrectStringValue {
            get {
                return ResourceManager.GetString("IncorrectStringValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Institutional sector code.
        /// </summary>
        public static string InstSectorCode {
            get {
                return ResourceManager.GetString("InstSectorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Is deleted.
        /// </summary>
        public static string IsDeleted {
            get {
                return ResourceManager.GetString("IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Kyrgyz.
        /// </summary>
        public static string LanguageKyrgyz {
            get {
                return ResourceManager.GetString("LanguageKyrgyz", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Russian.
        /// </summary>
        public static string LanguageRussian {
            get {
                return ResourceManager.GetString("LanguageRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Last change from value is later than &apos;last change to&apos;.
        /// </summary>
        public static string LastChangeFromError {
            get {
                return ResourceManager.GetString("LastChangeFromError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Last change to value is earlier than &apos;last change from&apos;.
        /// </summary>
        public static string LastChangeToError {
            get {
                return ResourceManager.GetString("LastChangeToError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Legal form.
        /// </summary>
        public static string LegalForm {
            get {
                return ResourceManager.GetString("LegalForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Legal unit.
        /// </summary>
        public static string LegalUnit {
            get {
                return ResourceManager.GetString("LegalUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Legal unit id.
        /// </summary>
        public static string LegalUnitId {
            get {
                return ResourceManager.GetString("LegalUnitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Legal unit id date.
        /// </summary>
        public static string LegalUnitIdDate {
            get {
                return ResourceManager.GetString("LegalUnitIdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to At least one legal unit is required.
        /// </summary>
        public static string LegalUnitIsRequired {
            get {
                return ResourceManager.GetString("LegalUnitIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to LegalUnits.
        /// </summary>
        public static string LegalUnits {
            get {
                return ResourceManager.GetString("LegalUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Links.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Liquidation date.
        /// </summary>
        public static string LiqDate {
            get {
                return ResourceManager.GetString("LiqDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to LiqDateEnd.
        /// </summary>
        public static string LiqDateEnd {
            get {
                return ResourceManager.GetString("LiqDateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to LiqDateStart.
        /// </summary>
        public static string LiqDateStart {
            get {
                return ResourceManager.GetString("LiqDateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Liquidation  reason.
        /// </summary>
        public static string LiqReason {
            get {
                return ResourceManager.GetString("LiqReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Local unit.
        /// </summary>
        public static string LocalUnit {
            get {
                return ResourceManager.GetString("LocalUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to LocalUnits.
        /// </summary>
        public static string LocalUnits {
            get {
                return ResourceManager.GetString("LocalUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This local unit doesn&apos;t have link to legal unit.
        /// </summary>
        public static string LogicalChecksLocalNoLegal {
            get {
                return ResourceManager.GetString("LogicalChecksLocalNoLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Address is not linked with this record.
        /// </summary>
        public static string LogicalChecksNoAddress {
            get {
                return ResourceManager.GetString("LogicalChecksNoAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Login is already taken.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Log in failed.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Market.
        /// </summary>
        public static string Market {
            get {
                return ResourceManager.GetString("Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Mun Capital Share.
        /// </summary>
        public static string MunCapitalShare {
            get {
                return ResourceManager.GetString("MunCapitalShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Name is already taken.
        /// </summary>
        public static string NameError {
            get {
                return ResourceManager.GetString("NameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Field &apos;Name&apos; is required.
        /// </summary>
        public static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Name value required.
        /// </summary>
        public static string NameValueRequired {
            get {
                return ResourceManager.GetString("NameValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to New password (leave it empty if you won&apos;t change password).
        /// </summary>
        public static string NewPassword_LeaveItEmptyIfYouWillNotChangePassword {
            get {
                return ResourceManager.GetString("NewPassword_LeaveItEmptyIfYouWillNotChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Statistical Business Register.
        /// </summary>
        public static string NSCRegistry {
            get {
                return ResourceManager.GetString("NSCRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to e.g. NSO employee.
        /// </summary>
        public static string NSO_Employee {
            get {
                return ResourceManager.GetString("NSO_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Number of employees from.
        /// </summary>
        public static string NumberOfEmployeesFrom {
            get {
                return ResourceManager.GetString("NumberOfEmployeesFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Number of employees to.
        /// </summary>
        public static string NumberOfEmployeesTo {
            get {
                return ResourceManager.GetString("NumberOfEmployeesTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Number of people.
        /// </summary>
        public static string NumOfPeople {
            get {
                return ResourceManager.GetString("NumOfPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to e.g. Ordinary website user.
        /// </summary>
        public static string OrdinaryWebsiteUser {
            get {
                return ResourceManager.GetString("OrdinaryWebsiteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Page num can not  be negative.
        /// </summary>
        public static string PageError {
            get {
                return ResourceManager.GetString("PageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Page not found.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Page size must be greater than 0.
        /// </summary>
        public static string PageSizeError {
            get {
                return ResourceManager.GetString("PageSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Parrent.
        /// </summary>
        public static string Parrent {
            get {
                return ResourceManager.GetString("Parrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ParrentId.
        /// </summary>
        public static string ParrentId {
            get {
                return ResourceManager.GetString("ParrentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error while updating password.
        /// </summary>
        public static string PasswordUpdateError {
            get {
                return ResourceManager.GetString("PasswordUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Phone value required.
        /// </summary>
        public static string PhoneValueRequired {
            get {
                return ResourceManager.GetString("PhoneValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Postal address id.
        /// </summary>
        public static string PostalAddressId {
            get {
                return ResourceManager.GetString("PostalAddressId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Private capital share.
        /// </summary>
        public static string PrivCapitalShare {
            get {
                return ResourceManager.GetString("PrivCapitalShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Read.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Reference№.
        /// </summary>
        public static string RefNo {
            get {
                return ResourceManager.GetString("RefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Registration id.
        /// </summary>
        public static string RegId {
            get {
                return ResourceManager.GetString("RegId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Registration id date.
        /// </summary>
        public static string RegIdDate {
            get {
                return ResourceManager.GetString("RegIdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Add new region.
        /// </summary>
        public static string RegionAdd {
            get {
                return ResourceManager.GetString("RegionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to All regions.
        /// </summary>
        public static string RegionAll {
            get {
                return ResourceManager.GetString("RegionAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This region name already exists in database.
        /// </summary>
        public static string RegionAlreadyExistsError {
            get {
                return ResourceManager.GetString("RegionAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Can&apos;t delete Region, possible is it using by user.
        /// </summary>
        public static string RegionDeleteError {
            get {
                return ResourceManager.GetString("RegionDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Delete region.
        /// </summary>
        public static string RegionDeleteMessage {
            get {
                return ResourceManager.GetString("RegionDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Region name.
        /// </summary>
        public static string RegionName {
            get {
                return ResourceManager.GetString("RegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Name region is mandatory field.
        /// </summary>
        public static string RegionNameIsRequiredError {
            get {
                return ResourceManager.GetString("RegionNameIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Region Id doesn&apos;t exists in database.
        /// </summary>
        public static string RegionNotExistsError {
            get {
                return ResourceManager.GetString("RegionNotExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to None.
        /// </summary>
        public static string RegionNotSelected {
            get {
                return ResourceManager.GetString("RegionNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Regions.
        /// </summary>
        public static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Restore region.
        /// </summary>
        public static string RegionUndeleteMessage {
            get {
                return ResourceManager.GetString("RegionUndeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Registration date.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Registration reason.
        /// </summary>
        public static string RegistrationReason {
            get {
                return ResourceManager.GetString("RegistrationReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Registration main activity.
        /// </summary>
        public static string RegMainActivity {
            get {
                return ResourceManager.GetString("RegMainActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to RegMainActivityId.
        /// </summary>
        public static string RegMainActivityId {
            get {
                return ResourceManager.GetString("RegMainActivityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Reorganization date.
        /// </summary>
        public static string ReorgDate {
            get {
                return ResourceManager.GetString("ReorgDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Reorganization references.
        /// </summary>
        public static string ReorgReferences {
            get {
                return ResourceManager.GetString("ReorgReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Reorganization type code.
        /// </summary>
        public static string ReorgTypeCode {
            get {
                return ResourceManager.GetString("ReorgTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Request failed.
        /// </summary>
        public static string RequestFailed {
            get {
                return ResourceManager.GetString("RequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Request started.
        /// </summary>
        public static string RequestStarted {
            get {
                return ResourceManager.GetString("RequestStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Request succeeded.
        /// </summary>
        public static string RequestSucceeded {
            get {
                return ResourceManager.GetString("RequestSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to RoleCreate.
        /// </summary>
        public static string RoleCreate {
            get {
                return ResourceManager.GetString("RoleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to RoleDelete.
        /// </summary>
        public static string RoleDelete {
            get {
                return ResourceManager.GetString("RoleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Role description.
        /// </summary>
        public static string RoleDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("RoleDescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to RoleEdit.
        /// </summary>
        public static string RoleEdit {
            get {
                return ResourceManager.GetString("RoleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Delete role.
        /// </summary>
        public static string RoleList_DeleteRole {
            get {
                return ResourceManager.GetString("RoleList_DeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Edit role.
        /// </summary>
        public static string RoleList_EditRole {
            get {
                return ResourceManager.GetString("RoleList_EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to RoleListView.
        /// </summary>
        public static string RoleListView {
            get {
                return ResourceManager.GetString("RoleListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Role name.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Role name.
        /// </summary>
        public static string RoleNamePlaceholder {
            get {
                return ResourceManager.GetString("RoleNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Role not found.
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to All roles.
        /// </summary>
        public static string RolesAll {
            get {
                return ResourceManager.GetString("RolesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Roles list.
        /// </summary>
        public static string RolesList {
            get {
                return ResourceManager.GetString("RolesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error while updating roles.
        /// </summary>
        public static string RoleUpdateError {
            get {
                return ResourceManager.GetString("RoleUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to RoleView.
        /// </summary>
        public static string RoleView {
            get {
                return ResourceManager.GetString("RoleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to About.
        /// </summary>
        public static string route_about {
            get {
                return ResourceManager.GetString("route_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Account.
        /// </summary>
        public static string route_account {
            get {
                return ResourceManager.GetString("route_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Create.
        /// </summary>
        public static string route_create {
            get {
                return ResourceManager.GetString("route_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Edit.
        /// </summary>
        public static string route_edit {
            get {
                return ResourceManager.GetString("route_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Home.
        /// </summary>
        public static string route_home {
            get {
                return ResourceManager.GetString("route_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Regions.
        /// </summary>
        public static string route_regions {
            get {
                return ResourceManager.GetString("route_regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Roles.
        /// </summary>
        public static string route_roles {
            get {
                return ResourceManager.GetString("route_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to StatUnits.
        /// </summary>
        public static string route_statunits {
            get {
                return ResourceManager.GetString("route_statunits", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Users.
        /// </summary>
        public static string route_users {
            get {
                return ResourceManager.GetString("route_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to View.
        /// </summary>
        public static string route_view {
            get {
                return ResourceManager.GetString("route_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Search statistical units.
        /// </summary>
        public static string SearchStatisticalUnits {
            get {
                return ResourceManager.GetString("SearchStatisticalUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Search wildcard.
        /// </summary>
        public static string SearchWildcard {
            get {
                return ResourceManager.GetString("SearchWildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Select or search roles....
        /// </summary>
        public static string SelectOrSearchRoles {
            get {
                return ResourceManager.GetString("SelectOrSearchRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Select or search standard data access.
        /// </summary>
        public static string SelectOrSearchStandardDataAccess {
            get {
                return ResourceManager.GetString("SelectOrSearchStandardDataAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Select or search system functions.
        /// </summary>
        public static string SelectOrSearchSystemFunctions {
            get {
                return ResourceManager.GetString("SelectOrSearchSystemFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Short name.
        /// </summary>
        public static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Standard data access.
        /// </summary>
        public static string StandardDataAccess {
            get {
                return ResourceManager.GetString("StandardDataAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to StartPeriod.
        /// </summary>
        public static string StartPeriod {
            get {
                return ResourceManager.GetString("StartPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to State capital share.
        /// </summary>
        public static string StateCapitalShare {
            get {
                return ResourceManager.GetString("StateCapitalShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Statistical id.
        /// </summary>
        public static string StatId {
            get {
                return ResourceManager.GetString("StatId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Statistical id date.
        /// </summary>
        public static string StatIdDate {
            get {
                return ResourceManager.GetString("StatIdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Statistical unit doesn&apos;t exist.
        /// </summary>
        public static string StatisticalUnitNotExistError {
            get {
                return ResourceManager.GetString("StatisticalUnitNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Statistical unit type.
        /// </summary>
        public static string StatisticalUnitType {
            get {
                return ResourceManager.GetString("StatisticalUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to StatUnit.
        /// </summary>
        public static string StatUnit {
            get {
                return ResourceManager.GetString("StatUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Statistical Unit Create.
        /// </summary>
        public static string StatUnitCreate {
            get {
                return ResourceManager.GetString("StatUnitCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Statistical Unit Delete.
        /// </summary>
        public static string StatUnitDelete {
            get {
                return ResourceManager.GetString("StatUnitDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Statistical Unit Edit.
        /// </summary>
        public static string StatUnitEdit {
            get {
                return ResourceManager.GetString("StatUnitEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Statistical Unit List View.
        /// </summary>
        public static string StatUnitListView {
            get {
                return ResourceManager.GetString("StatUnitListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Stat units.
        /// </summary>
        public static string StatUnits {
            get {
                return ResourceManager.GetString("StatUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Stat units list.
        /// </summary>
        public static string StatUnitsList {
            get {
                return ResourceManager.GetString("StatUnitsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Statistical Unit View.
        /// </summary>
        public static string StatUnitView {
            get {
                return ResourceManager.GetString("StatUnitView", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Status date.
        /// </summary>
        public static string StatusDate {
            get {
                return ResourceManager.GetString("StatusDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Suspended.
        /// </summary>
        public static string Suspended {
            get {
                return ResourceManager.GetString("Suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Suspension end.
        /// </summary>
        public static string SuspensionEnd {
            get {
                return ResourceManager.GetString("SuspensionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Suspension start.
        /// </summary>
        public static string SuspensionStart {
            get {
                return ResourceManager.GetString("SuspensionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to System administrator role is missing.
        /// </summary>
        public static string SysAdminRoleMissingError {
            get {
                return ResourceManager.GetString("SysAdminRoleMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tax registration date.
        /// </summary>
        public static string TaxRegDate {
            get {
                return ResourceManager.GetString("TaxRegDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tax registration id.
        /// </summary>
        public static string TaxRegId {
            get {
                return ResourceManager.GetString("TaxRegId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Telephone№.
        /// </summary>
        public static string TelephoneNo {
            get {
                return ResourceManager.GetString("TelephoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Total capital.
        /// </summary>
        public static string TotalCapital {
            get {
                return ResourceManager.GetString("TotalCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Total pages.
        /// </summary>
        public static string TotalPages {
            get {
                return ResourceManager.GetString("TotalPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Total roles.
        /// </summary>
        public static string TotalRoles {
            get {
                return ResourceManager.GetString("TotalRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Total users.
        /// </summary>
        public static string TotalUsers {
            get {
                return ResourceManager.GetString("TotalUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Try reload regions.
        /// </summary>
        public static string TryReloadRegions {
            get {
                return ResourceManager.GetString("TryReloadRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Try reload roles.
        /// </summary>
        public static string TryReloadRoles {
            get {
                return ResourceManager.GetString("TryReloadRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Turnover date.
        /// </summary>
        public static string TurnoveDate {
            get {
                return ResourceManager.GetString("TurnoveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Turnover.
        /// </summary>
        public static string Turnover {
            get {
                return ResourceManager.GetString("Turnover", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Turnover from.
        /// </summary>
        public static string TurnoverFrom {
            get {
                return ResourceManager.GetString("TurnoverFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Turnover from is larger than &apos;turnover to&apos;.
        /// </summary>
        public static string TurnoverFromErrorLarger {
            get {
                return ResourceManager.GetString("TurnoverFromErrorLarger", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Turnover from shouldn&apos;t be negative.
        /// </summary>
        public static string TurnoverFromErrorNegative {
            get {
                return ResourceManager.GetString("TurnoverFromErrorNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Turnover to.
        /// </summary>
        public static string TurnoverTo {
            get {
                return ResourceManager.GetString("TurnoverTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Turnover to is less than &apos;turnover from&apos;.
        /// </summary>
        public static string TurnoverToErrorLess {
            get {
                return ResourceManager.GetString("TurnoverToErrorLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Turnover to shouldn&apos;t be negative.
        /// </summary>
        public static string TurnoverToErrorNegative {
            get {
                return ResourceManager.GetString("TurnoverToErrorNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Turnover year.
        /// </summary>
        public static string TurnoverYear {
            get {
                return ResourceManager.GetString("TurnoverYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Type new password again.
        /// </summary>
        public static string TypeNewPasswordAgain {
            get {
                return ResourceManager.GetString("TypeNewPasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Type password again.
        /// </summary>
        public static string TypePasswordAgain {
            get {
                return ResourceManager.GetString("TypePasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Type strong password here.
        /// </summary>
        public static string TypeStrongPasswordHere {
            get {
                return ResourceManager.GetString("TypeStrongPasswordHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to UnitType.
        /// </summary>
        public static string UnitType {
            get {
                return ResourceManager.GetString("UnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unknown statistic unit type.
        /// </summary>
        public static string UnknownStatUnitTypeError {
            get {
                return ResourceManager.GetString("UnknownStatUnitTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error while update Enterprise Group.
        /// </summary>
        public static string UpdateEnterpriseGroupError {
            get {
                return ResourceManager.GetString("UpdateEnterpriseGroupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error while update Enterprise Unit.
        /// </summary>
        public static string UpdateEnterpriseUnitError {
            get {
                return ResourceManager.GetString("UpdateEnterpriseUnitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error while update Legal Unit.
        /// </summary>
        public static string UpdateLegalUnitError {
            get {
                return ResourceManager.GetString("UpdateLegalUnitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error while update Local Unit.
        /// </summary>
        public static string UpdateLocalUnitError {
            get {
                return ResourceManager.GetString("UpdateLocalUnitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to UserCreate.
        /// </summary>
        public static string UserCreate {
            get {
                return ResourceManager.GetString("UserCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to UserDelete.
        /// </summary>
        public static string UserDelete {
            get {
                return ResourceManager.GetString("UserDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to UserEdit.
        /// </summary>
        public static string UserEdit {
            get {
                return ResourceManager.GetString("UserEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User email.
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to UserListView.
        /// </summary>
        public static string UserListView {
            get {
                return ResourceManager.GetString("UserListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User login.
        /// </summary>
        public static string UserLogin {
            get {
                return ResourceManager.GetString("UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Field &apos;Name&apos; is required.
        /// </summary>
        public static string UserNameIsRequired {
            get {
                return ResourceManager.GetString("UserNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFoundError {
            get {
                return ResourceManager.GetString("UserNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User password.
        /// </summary>
        public static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User phone.
        /// </summary>
        public static string UserPhone {
            get {
                return ResourceManager.GetString("UserPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Users in.
        /// </summary>
        public static string UsersIn {
            get {
                return ResourceManager.GetString("UsersIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Users list.
        /// </summary>
        public static string UsersList {
            get {
                return ResourceManager.GetString("UsersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User&apos;s new password.
        /// </summary>
        public static string UsersNewPassword {
            get {
                return ResourceManager.GetString("UsersNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User status.
        /// </summary>
        public static string UserStatus {
            get {
                return ResourceManager.GetString("UserStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Any user status.
        /// </summary>
        public static string UserStatusAny {
            get {
                return ResourceManager.GetString("UserStatusAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error while updating user.
        /// </summary>
        public static string UserUpdateError {
            get {
                return ResourceManager.GetString("UserUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to UserView.
        /// </summary>
        public static string UserView {
            get {
                return ResourceManager.GetString("UserView", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ViewEnterpriseGroup.
        /// </summary>
        public static string ViewEnterpriseGroup {
            get {
                return ResourceManager.GetString("ViewEnterpriseGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ViewEnterpriseUnit.
        /// </summary>
        public static string ViewEnterpriseUnit {
            get {
                return ResourceManager.GetString("ViewEnterpriseUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ViewLegalUnit.
        /// </summary>
        public static string ViewLegalUnit {
            get {
                return ResourceManager.GetString("ViewLegalUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ViewLocalUnit.
        /// </summary>
        public static string ViewLocalUnit {
            get {
                return ResourceManager.GetString("ViewLocalUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Web address.
        /// </summary>
        public static string WebAddress {
            get {
                return ResourceManager.GetString("WebAddress", resourceCulture);
            }
        }
    }
}
