name: app build & lint
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'ops/**'  # Ignore any branch prefixed with ops/
  pull_request:
    branches-ignore:
      - 'ops/**'  # Ignore any branch prefixed with ops/

jobs:
  build-app:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    container:
      image: node:20.10-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Build app
        run: |
          docker build --target test -t statbus-app-test -f app/Dockerfile app

      - name: Run App Tests
        run: |
          docker run --rm statbus-app-test
