---
##################################
##################################
## Continuous Delivery workflow ##
##################################
##################################
name: CD
on:
  push:
    branches:
      - AddingDockerSupportCore3.1
  pull_request:
jobs:
  build:
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.gitversion.outputs.FullSemVer }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.x
      - uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7

      - name: Docker meta
        id: docker-meta
        uses: docker/metadata-action@v4
        with:
          github-token: ${{ github.token }}
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nscreg:latest
            ghcr.io/statisticsnorway/nscreg:latest
          tags: |
            type=raw,value=${{ steps.gitversion.outputs.FullSemVer }}
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./src/nscreg.Server/Dockerfile
          push: ${{ {{is_default_branch}} || github.event_name == 'pull_request' }}
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Fetch image
        shell: bash
        run: "echo docker pull ghcr.io/statisticsnorway/nscreg:latest"
      - name: Deploy image
        shell: bash
        run: "echo Deploy 2"
  e2e_test:
    runs-on: ubuntu-20.04
    needs: deploy
    steps:
      - name: run e2e tests
        shell: bash
        run: "echo e2e"
