---
#####################################
#####################################
## Continuous Integration workflow ##
#####################################
#####################################
name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - "!AddingDockerSupportCore3.1"
    paths:
      - src/
      - client/
      - test/
      - .github/workflows/ci-workflow.yaml
      - .github/actions/dotnet-build-test/
  pull_request:
    paths:
      - src/
      - client/
      - test/
      - .github/workflows/ci-workflow.yaml
      - .github/actions/dotnet-build-test/

env:
  ACT: ""
jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dotnet-build-test
        with:
          project: ./src/nscreg.Server/nscreg.Server.csproj
          configuration: Debug
          test_filter: Category=Unit

  build-spa:
    runs-on: ubuntu-20.04
    container:
      image: node:19-bullseye-slim
    steps:
      - uses: actions/checkout@v3
      - run: npm ci --legacy-peer-deps
      - run: npm run lint || true
      - run: npm run build
      - run: npm run test
