name: CI
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'devops/**'  # Ignore any branch prefixed with devops/
  pull_request:
    branches-ignore:
      - 'devops/**'  # Ignore any branch prefixed with devops/

jobs:
  build-app:
    runs-on: ubuntu-20.04
    container:
      image: node:20.10-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Build app
        run: |
          cd app
          npm ci
          npm test -- --ci --silent
          npm run lint -- --quiet
          npm run build -- --no-lint
  pg_regress:
    concurrency:
      group: statbus_test
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
    - name: Run tests on remote server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: niue.statbus.org
        username: statbus_test
        key: ${{ secrets.SSH_KEY }}
        command_timeout: 60m
        script: |
          BRANCH=${{ github.ref_name }}
          COMMIT=${{ github.sha }}
          ./statbus/devops/manage-statbus.sh continous-integration-test $BRANCH $COMMIT
