name: CI
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build-aspnet:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dotnet-build-test
        with:
          project: ./src/nscreg.Server/nscreg.Server.csproj
          configuration: Debug
          test_filter: Category=Unit

  build-app:
    runs-on: ubuntu-20.04
    container:
      image: node:20.10-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Build app
        run: |
          cd app
          npm ci
          npm run lint -- --quiet
          npm run build -- --no-lint
