name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - AddingDockerSupportCore3.1
    paths:
      - src/
      - client/
      - .github/workflows/ci.yaml
  pull_request:
    paths:
      - src/
      - client/
      - .github/workflows/ci.yaml

env:
  ACT: ""
jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dotnet-build-test/
        with:
          project: ./src/nscreg.Server/nscreg.Server.csproj
          configuration: Debug
          test_filter: Category=Unit
