# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "no.statbus.org<-devops/deploy-to-no"
on:
  # Allow manual deployment in github
  workflow_dispatch:
  push:
    branches:
      - devops/deploy-to-no

# Deploys are serial for a deploy branch.
concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: niue.statbus.org
          username: statbus_no
          key: ${{ secrets.SSH_KEY }}
          command_timeout: 60m
          script: statbus/devops/deploy.sh
