# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "dev.statbus.org<-devops/deploy-to-dev"
on:
  # Allow manual deployment in github
  workflow_dispatch:
  push:
    branches:
      - "devops/deploy-to-dev"

# Deploys are serial for a deploy branch.
concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: niue.statbus.org
        username: statbus_dev
        key: ${{ secrets.SSH_KEY }}
        command_timeout: 60m
        script: /usr/local/bin/deploy-statbus.sh