# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "demo.statbus.org<-devops/deploy-to-demo"
on:
  workflow_dispatch:
  push:
    branches:
      - "devops/deploy-to-demo"

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Deploy via upgrade daemon
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: niue.statbus.org
          username: statbus_demo
          key: ${{ secrets.SSH_KEY }}
          command_timeout: 5m
          script: |
            cd ~/statbus
            ./sb upgrade apply "sha-${{ github.sha }}"
