name: pg_regress
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'devops/**'  # Ignore any branch prefixed with devops/
  pull_request:
    branches-ignore:
      - 'devops/**'  # Ignore any branch prefixed with devops/

jobs:
  pg_regress:
    concurrency:
      group: statbus_test
      cancel-in-progress: false
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Run tests on remote server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: niue.statbus.org
        username: statbus_test
        key: ${{ secrets.SSH_KEY }}
        command_timeout: 60m
        script: |
          cd statbus; ./devops/manage-statbus.sh continous-integration-test "${{github.ref_name}}" "${{github.sha}}"
