name: Push production -> ops/cloud/deploy/all
on:
  push:
    branches:
      - "ops/cloud/deploy/production"
  # Allow manual deployment in github
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "ops/cloud/deploy/production"
          ssh-key: ${{ secrets.SSH_KEY }}
      - name: Push for deployment
        run: |
          git push --force origin HEAD:ops/cloud/deploy/demo
          git push --force origin HEAD:ops/cloud/deploy/et
          git push --force origin HEAD:ops/cloud/deploy/jo
          git push --force origin HEAD:ops/cloud/deploy/ma
          git push --force origin HEAD:ops/cloud/deploy/no
          git push --force origin HEAD:ops/cloud/deploy/tcc
          git push --force origin HEAD:ops/cloud/deploy/ug
